### PR TITLE
fix: change download timeout to 5 minutes instead of 20s, fixes #7298

### LINKED ISSUE #7298: Timeout upgrading docker-compose after upgrading ddev to 1.24.5 on slower networks (fixed in v1.24.6)
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

After upgrading DDEV to 1.24.5, each project I start stops with a timeout error:

<summary>The download of docker-compose is slow and fails in time-out after a while (less than 1 minute).</summary>

<details>
After many tries (ran `ddev debug test`, restarted WSL, restarted Windows, cleared docker images, etc.) I downgraded DDEV to 1.24.4 and now docker-compose is (slowly) downloading.

It took about 30 minutes. But now it's working. The slowness is caused by WSL networking settings. I use NAT because Mirroring causes issues starting projects.
</details>

It looks like 1.24.5 has a timeout in the docker-compose download function. Can this be overridden?

### Expected Behavior

ddev start to run normally

### Actual Behavior

```log
❯ ddev start
Network ddev_default created
Starting opigno-test...
docker-compose 1.14 MiB / 70.32 MiB [=>--------------------------------------------------------------------]   1.62% 18s
Your docker-compose version does not exist or is set to an invalid version.
Please use the built-in docker-compose.
Fix with 'ddev config global --required-docker-compose-version="" --use-docker-compose-from-path=false': context deadline exceeded (Client.Timeout or context cancellation while reading body)
```

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

- #7298 

On slower networks, the download of docker-compose times out in just 20s and gives an odd message

## How This PR Solves The Issue

- [x] Increase the timeout
- [x] Improve the message given on failure

## Manual Testing Instructions

I used network conditioning in Parallels to slow the download speed to 20Mbps to reproduce this.

Running TestDockerComposeDownload with the network slowed down shows the failure at 20s, but it succeed with this fix.

### CODE REVIEW

**Comment by rfay** [comment]
New message example:

```
Network ddev_default created 
docker-compose 38.58 MiB / 68.63 MiB [================>------------]  56.22% 19s
Failed to download updated docker-compose binary.
This might be due to network issues or a slow response. 
Please ensure your network is stable and try again:
context deadline exceeded (Client.Timeout or context cancellation while reading body) 
```

**Review by stasadev — APPROVED** [review]
Thank you, looks good to me!

File: pkg/util/network.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ func DownloadFile(destPath string, fileURL string, progressBar bool, shaSumURL s
 	}
 	client.Backoff = retryablehttp.DefaultBackoff
 	client.Logger = nil
-	client.HTTPClient.Timeout = 20 * time.Second
+	client.HTTPClient.Timeout = 5 * time.Minute
```
Comment (GuySartorelli) [inline pkg/util/network.go:46]: Is this change only for downloading images on upgrade? If not, what other scenarios use this timeout?

Comment (rfay) [reply pkg/util/network.go:46]: Has nothing to do with images, only things that use DownloadFile(), which means docker-compose, mutagen, and `ddev add-on get` downloads at this point.

**Comment by rfay** [comment]
OK, going with it. Having this in HEAD may make it easier for some people to test/use it.
