### PR TITLE
fix: ensure help information respects `--json-output` flag, fixes #5567

### LINKED ISSUE #5567: `ddev help` doesn't respect `--json-output`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Running bash [-c /tmp/test_ddev.sh] 
Please try running this in an existing DDEV project directory, preferably the problem project.
It doesn't work in other directories.
Failed running test_ddev.sh: exit status 2
. You can run it manually with `curl -sL -O https://raw.githubusercontent.com/ddev/ddev/master/cmd/ddev/cmd/scripts/test_ddev.sh && bash test_ddev.sh`
```

Which makes sense - this bug report has nothing to do with projects. I don't have any current ddev projects to run the command in, and I don't think the output is relevant so I'm not gonna bother spinning one up unless I really have to.
</details>         

### Expected Behavior

The help information should respect the global `--json-output` or `-j` flag, and output its information in JSON format. This would make the output easy to interpret programmatically.

### Actual Behavior

The output is the same as though you hadn't used the `--json-output` or `-j` flag. This means it is not easy to interpret programmatically.

### Steps To Reproduce

1. Run `ddev help <command> --json-output`
2. Observe that the output is _not_ in JSON format.

### Anything else?

I'm writing a wrapper around DDEV that allows me to further customise the DDEV CLI. Part of this requires being able to programmatically interpret the output from the help command so that my wrapper can use that information to know what flags any given DDEV command will accept, among other things. I'm doing that with REGEX at the moment, but theoretically the way the output is displayed could change tomorrow and break it. If I could get the information as a JSON object, the normal text output could change without breaking my code (along with being easier to fetch the relevant information in the first place).

### PR DESCRIPTION
**Pull request by GuySartorelli**
## The Issue

- #5567

## How This PR Solves The Issue

Replaces the default help function with one that outputs a JSON-formatted representation of a command when the `--json-output` flag is used.

## Manual Testing Instructions

Run any version of the help command or `-h` flag in conjunction with the `--json-output` (or `-j`) flag, e.g:
- `ddev help -j`
- `ddev auth -hj`
- `ddev auth ssh -hj`

## Automated Testing Overview

I haven't added tests yet, because I want to make sure the approach is correct and acceptable before I do so. I wouldn't want to write tests only for them to be entirely invalidated by sweeping changes required in the implementation.

Once a maintainer has told me that the approach for the implementation is good, I'll add some tests.

## Related Issue Link(s)

#5567 

## Release/Deployment Notes

N/A

## Other notes

This is my first time contributing here and my first time writing anything in go - so it's likely I've done things in a completely backwards way - I don't have a good background on go conventions, nor this codebase, nor the cobra codebase or conventions, so please make sure to explain things clearly and in full when requesting changes.

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
Thanks so much for giving this a try! This is looking great. The one thing I'd say is probably structure the json the way all the other commands are structured; take a look at `ddev describe -j` for example, where the `raw` has the json, `msg` has the plain text. SO impressive! Thanks.

**Comment by rfay** [comment]
(And since your head is in this, I'd love it if you'd take a look at 
* https://github.com/ddev/ddev/issues/962

which is our oldest open issue :) )

**Comment by GuySartorelli** [comment]
I've updated this to use `output.UserOut.WithField()` to output the JSON, which seems to be what the describe command is doing... and that's fine for using the help command like so:
```shell
ddev help -j
ddev help list -j
```

But if I try to use the help _flag_, we get the "test" output which indicates the `--json-output` flag is captured correctly, but we _don't_ get any of the data I'm shoving into `raw`:
```shell
ddev -hj
ddev list -h -j
```

Do you know what might be causing the JSON to not be output correctly when `-h` is used as a flag?

**Comment by GuySartorelli** [comment]
Nevermind, I think I found it. `output.LogSetUp()` needs to be called a second time. It's called once in root.init but that's _before_ the `--json-output` flag is parsed. See https://github.com/ddev/ddev/blob/1016bc7b623086cb200137e5d06b1e5665022b80/cmd/ddev/cmd/root.go#L40-L42

Let me know what further changes are required with the implementation as a whole - once you're happy with that I'll get some tests written.

File: cmd/ddev/cmd/root.go [hunk 1]
```diff
@@ -194,6 +195,149 @@ func init() {
...
+			rawResult["Commands"] = jsonCommands
+			rawResult["CommandGroups"] = jsonCommandGroups
+			rawResult["AdditionalCommands"] = jsonAdditionalCommands
+			rawResult["AdditionalHelpCommands"] = jsonAdditionalHelpCommands
+			rawResult["Flags"] = jsonFlags
+			rawResult["GlobalFlags"] = jsonGlobalFlags
+			rawResult["Deprecated"] = command.Deprecated
+			rawResult["Hidden"] = command.Hidden
+
+			output.UserOut.WithField("raw", rawResult).Print()
```
Comment (GuySartorelli) [inline cmd/ddev/cmd/root.go:338]: Note that I can't pass the raw help output into the `Print()` call, since the original help function prints directly to the terminal rather than returning its result.

**Comment by rfay** [comment]
I guess the one thing I don't like right now is that it's inline in the root.go init(). init() is evil anyway, but could you refactor it to put it in a function in root_help_json.go or something?

**Comment by GuySartorelli** [comment]
> could you refactor it to put it in a function in root_help_json.go or something?

I can - but unless you say otherwise I'm going to call it literally `root_help_json.go` - "or something" is too ambiguous for me to do anything with :p

**Comment by rfay** [comment]
I can live without a test on this one, but would love fix and test for the logs one :) (new PR :) )

**Comment by GuySartorelli** [comment]
JSON format for logs is less important to me personally, so I won't promise anything on that front.

**Review by stasadev — APPROVED** [review]
It works good.

The only exceptions I found (for example, `ddev help composer`) do not support the `-j` flag, which is expected:
- https://github.com/ddev/ddev/pull/4283

**Comment by GuySartorelli** [comment]
> I can live without a test on this one

Given this statement, is there anything left to do for this PR? Seems ready to merge, I think?

**Comment by rfay** [comment]
I hope to give it a run.

**Comment by GuySartorelli** [comment]
> I hope to give it a run.

Does that mean you want to try run it locally to test it before merging?
I know you said you're okay without automated tests for this, but if I provided some would that speed things along at all?

**Comment by rfay** [comment]
Sorry I didn't get to test before leaving. Maybe @stasadev will get a chance to look. Thanks for the contribution.

**Review by stasadev — APPROVED** [review]
The code looks fine and doesn't seem to break anything, I'll pull it today.

**Comment by GuySartorelli** [comment]
Thanks!
