### PR TITLE
fix: create mutagen-agents tarball if it doesn't exist, fixes #6421 

### LINKED ISSUE #6421: DownloadMutagenIfNeeded() should check for existence of agent tarball and download if it doesn't exist
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

At `ddev start`, the correct `mutagen` and `mutagen-agents.tar.gz` should be available in ~/.ddev/bin

### Actual Behavior

Slack: https://drupal.slack.com/archives/C5TQRQZRR/p1721753115234839

Something deleted ~/.ddev/mutagen-agents.tar.gz, and as a result mutagen couldn't function, although `mutagen --version` works as a test.

### Steps To Reproduce

Delete ~/.ddev/bin/mutagen-agents.tar.gz and `ddev start`

### Anything else?

Simple workaround is `rm -rf ~/.ddev/bin` and `ddev restart`

We should be able to fix this by just testing in DownloadMutagenIfNeeded to download if the tarball is missing, and perhaps validate at the end of DownloadMutagen() to make sure the tarball arrived.

### PR DESCRIPTION
**Pull request by davearch**
## The Issue

- #6421 

The app is unable to start without a mutagen-agents.tar.gz file in the global bin directory.

## How This PR Solves The Issue
This PR adds a check to make sure the tarbell exists in the DownloadMutagenIfNeeded function, and if it does not, downloads mutagen. It also adds a test to test this functionality works.

## Manual Testing Instructions
Remove the tarbell file in the global bin directory e.g. rm ~/.ddev/bin/mutagen-agents.tar.gz and restart the app e.g. ddev restart

## Automated Testing Overview
Adds the TestDownloadMutagen test which has the same setup as TestMutagenSimple but removes the tarbell if it exists, then starts the app. Then it verifies that the tarbell has been downloaded. Then it removes it again and restarts the app, and finally verifies that the tarbell has been downloaded again.

### CODE REVIEW

**Comment by rfay** [comment]
Thanks!

**Review by stasadev — APPROVED** [review]
Thank you!
Tested, works as it should.

File: pkg/ddevapp/mutagen.go [hunk 1]
```diff
@@ -589,6 +589,14 @@ func DownloadMutagenIfNeeded() error {
...
 		}
 	}
+	// Also make sure the mutagen-agents.tar.gz is in place
+	agentsFile := filepath.Join(globalconfig.GetDDEVBinDir(), "mutagen-agents.tar.gz")
+	if !fileutil.FileExists(agentsFile) {
+		err = DownloadMutagen()
+		if err != nil {
+			return err
+		}
+	}
```
Comment (rfay) [inline pkg/ddevapp/mutagen.go:599]: This is great! How about doing this with one if statement (incorporating it in the "or" above? You can calculate the agentsFile before the if, and add the !FileExists to the OR?

File: pkg/ddevapp/mutagen_test.go [hunk 2]
```diff
@@ -250,3 +250,48 @@ func TestMutagenConfigChange(t *testing.T) {
 
 	util.Debug("origSyncID=%s afterRestartSyncID=%s afterChangeSyncID=%s", origSyncID, afterRestartSyncID, afterChangeSyncID)
 }
+
+// Test app starts despite a missing mutagen-agents.tar.gz file
```
Comment (rfay) [inline pkg/ddevapp/mutagen_test.go:254]: Could this be done at the end of TestMutagenSimple and require less setup that way?

**Review by rfay — CHANGES_REQUESTED** [review]
So impressive, and passed tests right away. I think it could be simplified a bit as mentioned, but thanks for taking this on and solving it, and it will be successful!

File: pkg/ddevapp/mutagen.go (hunk 1 above)
Comment (davearch) [reply pkg/ddevapp/mutagen.go:599]: Yes, makes sense!

File: pkg/ddevapp/mutagen_test.go (hunk 2 above)
Comment (davearch) [reply pkg/ddevapp/mutagen_test.go:254]: Yes, probably lol

File: pkg/ddevapp/mutagen.go [hunk 3]
```diff
@@ -582,8 +582,9 @@ func DownloadMutagenIfNeeded() error {
 	if err != nil {
 		return err
 	}
+	agentsFile := filepath.Join(globalconfig.GetDDEVBinDir(), "mutagen-agents.tar.gz")
 	curVersion, err := version.GetLiveMutagenVersion()
-	if err != nil || curVersion != versionconstants.RequiredMutagenVersion {
+	if err != nil || curVersion != versionconstants.RequiredMutagenVersion || !fileutil.FileExists(agentsFile) {
```
Comment (rfay) [inline pkg/ddevapp/mutagen.go:587]: Thanks, this is perfect.

File: pkg/ddevapp/mutagen_test.go [hunk 4]
```diff
@@ -150,6 +150,26 @@ func TestMutagenSimple(t *testing.T) {
...
+	require.NoError(t, err)
+	// Verify that the mutagen-agents.tar.gz file was downloaded
+	assert.FileExists(filepath.Join(globalconfig.GetDDEVBinDir(), "mutagen-agents.tar.gz"))
+	// Remove the mutagen-agents.tar.gz file again and restart the app
+	err = os.Remove(filepath.Join(globalconfig.GetDDEVBinDir(), "mutagen-agents.tar.gz"))
+	require.NoError(t, err)
+	err = app.Restart()
+	require.NoError(t, err)
+	// Verify again that the mutagen-agents.tar.gz file was downloaded
+	assert.FileExists(filepath.Join(globalconfig.GetDDEVBinDir(), "mutagen-agents.tar.gz"))
```
Comment (rfay) [inline pkg/ddevapp/mutagen_test.go:171]: Why do this a second time? I know you had a reason.

**Review by rfay — APPROVED** [review]
Looking great, thanks! Just had the one question.

File: pkg/ddevapp/mutagen_test.go (hunk 4 above)
Comment (davearch) [reply pkg/ddevapp/mutagen_test.go:171]: I wanted to specifically check that stopping the app and starting again (the restart) would not cause any issues. Mostly because in the stop method there are some mutagen calls (like SyncAndPauseMutagenSession and TerminateMutagenSync). This _may_ not be beneficial because I am not 100% on the details of mutagen but I wanted to sanity check it anyway. I can remove it if you think it is overkill. Probably that last FileExists check might be overkill
