### PR TITLE
fix: Improve clarity in explanation by removing awkward 'normally', fixes #6723

### LINKED ISSUE #6723: Awkward text in  administrative privileges explanation
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

The current explanation reads like this:

> This is normally to add unresolvable hostnames to the hosts file.

which is a bit awkward, I suggest a change to simply:

> This is needed to add unresolvable hostnames to the hosts file.

### Expected Behavior

The explanation should clearly and directly state why administrative privileges are required, without ambiguous qualifying words like 'normally'.

### Actual Behavior

The current text uses 'normally' which makes the explanation unnecessarily ambiguous and less direct about why administrative privileges are required.

### Steps To Reproduce

1. Start a new project

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wazum**
## The Issue

- #6723 

## How This PR Solves The Issue

Text change

### CODE REVIEW

File: pkg/ddevapp/hostname_mgt.go [hunk 1]
```diff
@@ -255,7 +255,7 @@ func runCommandWithSudo(args []string) (out string, err error) {
 		c = []string{"gsudo.exe"}
 	}
 	c = append(c, args...)
-	output.UserOut.Printf("DDEV needs to run with administrative privileges.\nThis is normally to add unresolvable hostnames to the hosts file.\nYou may be required to enter your password for sudo or allow escalation.\nDDEV is about to issue the command:\n  %s\n", strings.Join(c, ` `))
+	output.UserOut.Printf("DDEV needs to run with administrative privileges.\nThis is needed to add unresolvable hostnames to the hosts file.\nYou may be required to enter your password for sudo or allow escalation.\nDDEV is about to issue the command:\n  %s\n", strings.Join(c, ` `))
```
Comment (stasadev) [inline pkg/ddevapp/hostname_mgt.go:258]: Thanks for the suggestion!
However, using "needed" right after "needs" feels a bit repetitive.
I think it would be better with "necessary" or "typically" instead.

**Review by stasadev — CHANGES_REQUESTED** [review]

**Review by rfay — APPROVED** [review]
Thanks, seems ok to me.

**Comment by rfay** [comment]
Oh, please don't use `master` for PRs in your future PRs, as it ties you to your fork's default branch, making things difficult going forward. Use a named branch. We ask for YYYYMMDD_wazum_short_description for the branch name.

**Review by stasadev — APPROVED** [review]
