### PR TITLE
fix: use correct autoloader for XHGui php-profiler, preinstall it in ddev-webserver, fixes #7170

### LINKED ISSUE #7170: Regression: TYPO3 install fails with a variety of stack traces in HEAD (upcoming v1.24.4)
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

======== Output file will be in /var/folders/z5/lhpyjf2n7xj2djl0bw_7kb3m0000gn/T/ddev-debug-test.txt ========

======== Existing project config ========
ddev installation alternate locations:
/usr/local/bin/ddev
/opt/homebrew/bin/ddev
/usr/local/bin/ddev

These config files were loaded for project t3v13: [/Users/rfay/workspace/t3v13/.ddev/config.yaml]
name: t3v13
type: typo3
docroot: public
php_version: 8.3
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:20250307_rfay_xhgui
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.11}
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 22
default_container_timeout: 120

======== existing project customizations ========

======== installed DDEV add-ons ========
No registered add-ons were found.

======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /Users/rfay/workspace/t3v13

unmodified #ddev-generated found in .ddev/mutagen/mutagen.yml

======== Creating dummy project named tryddevproject-9694 in ../tryddevproject-9694 ========
Creating a new DDEV project config in the current directory (/Users/rfay/workspace/tryddevproject-9694)
Once completed, your configuration will be written to /Users/rfay/workspace/tryddevproject-9694/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-9694' with docroot 'web' at '/Users/rfay/workspace/tryddevproject-9694/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.

======== OS Information ========
Darwin rfay-mba-m4.local 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:31:46 PST 2025; root:xnu-11215.81.4~4/RELEASE_ARM64_T8132 arm64
ProductName:		macOS
ProductVersion:		15.3.2
BuildVersion:		24D2082

======== User information ========
uid=501(rfay) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),701(com.apple.sharepoint.group.1),33(_appstore),98(_lpadmin),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)

======== DDEV version ========
 ITEM             VALUE                                                                
 DDEV version     v1.24.3-67-g634b42183                                                
 architecture     arm64                                                                
 cgo_enabled      0                                                                    
 db               ddev/ddev-dbserver-mariadb-10.11:v1.24.3                             
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.24.3                                          
 docker           27.5.1                                                               
 docker-api       1.47                                                                 
 docker-compose   v2.33.1                                                              
 docker-platform  orbstack                                                             
 global-ddev-dir  /Users/rfay/.ddev                                                    
 go-version       go1.24.1                                                             
 mutagen          0.18.1                                                               
 os               darwin                                                               
 router           ddev/ddev-traefik-router:20250318_stasadev_proxy_load_balancer_alias 
 web              ddev/ddev-webserver:20250307_rfay_xhgui                              
 xhgui-image      ddev/ddev-xhgui:20250325_stasadev_xhgui_volume                       

======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''

======== DDEV global info ========
developer-mode=false
fail-on-hook-fail=false
instrumentation-opt-in=true
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.24.3-67-g634b42183
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/Users/rfay/Library/Application Support/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=mutagen
project-tld=ddev.site
required-docker-compose-version=v2.33.1
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=
xhgui-http-port=
xhgui-https-port=
xhprof-mode=

======== DOCKER provider info ========
docker client location: lrwxr-xr-x@ 1 root  wheel  53 Mar 12 11:29 /usr/local/bin/docker -> /Applications/OrbStack.app/Contents/MacOS/xbin/docker

docker client alternate locations:
/usr/local/bin/docker
/usr/local/bin/docker
/Users/rfay/.orbstack/bin/docker

Docker provider: orbstack

======== docker version ========
Client:
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.22.11
 Git commit:        9f9e405
 Built:             Wed Jan 22 13:37:19 2025
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.5.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.11
  Git commit:       4c9b3b0
  Built:            Wed Jan 22 13:40:18 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v2.0.3
  GitCommit:        06b99ca80cdbfbc6cc8bd567021738c9af2b36ce
 runc:
  Version:          1.2.5
  GitCommit:        59923ef18c98053ddb1acf23ecba10344056c28e
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

======== docker context ls ========
NAME            DESCRIPTION                               DOCKER ENDPOINT                                ERROR
default         Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                    
desktop-linux   Docker Desktop                            unix:///Users/rfay/.docker/run/docker.sock     
orbstack *      OrbStack                                  unix:///Users/rfay/.orbstack/run/docker.sock   

DOCKER_HOST=unix:///Users/rfay/.orbstack/run/docker.sock
DOCKER_DEFAULT_PLATFORM=notset
Version: 1.10.3 (1100300)
Commit: 2b5dd5f580d80a3d2494b7b40dde2ef46813cfc5 (v1.10.3)

======== ddev debug dockercheck ========
Docker platform: orbstack
Using Docker context: default (unix:///Users/rfay/.orbstack/run/docker.sock)
docker-compose: v2.33.1
Using DOCKER_HOST=unix:///Users/rfay/.orbstack/run/docker.sock
Docker version: 27.5.1
Docker API version: 1.47
Able to run simple container that mounts a volume.
Able to use internet inside container.

Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                   1.2T     11.0G      1.2T   1% /

======== Existing docker containers ========
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

======== docker system df ========
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          46        0         8.508GB   8.508GB (100%)
Containers      0         0         0B        0B
Local Volumes   57        0         2.299GB   2.299GB (100%)
Build Cache     302       0         50.47MB   50.47MB

  Tips:
  1. Periodically check your Docker filesystem usage with 'docker system df'
  2. Use 'docker builder prune' to remove unused Docker build cache (it doesn't remove your data)
  3. To remove all containers and images (it doesn't remove your data):
    ```
    ddev poweroff
    docker rm -f $(docker ps -aq) || true
    docker rmi -f $(docker images -q)
    ```
    (DDEV images will be downloaded again on 'ddev start')

======== mkcert information ========
/opt/homebrew/bin/mkcert
CAROOT= WSLENV= JAVA_HOME=
/Users/rfay/Library/Application Support/mkcert
total 16
-r--------@ 1 rfay  staff  2488 Mar 12 11:55 rootCA-key.pem
-rw-r--r--@ 1 rfay  staff  1773 Mar 12 11:55 rootCA.pem

======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.053 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.053/0.053/0.053/0.000 ms

======== curl information ========
/usr/bin/curl

======== ddev debug rebuild ========
Rebuilding project images...
Rebuilding project tryddevproject-9694 with `/Users/rfay/.ddev/bin/docker-compose -f /Users/rfay/workspace/tryddevproject-9694/.ddev/.ddev-docker-compose-full.yaml --progress plain build web --no-cache`
#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.67kB done
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/ddev/ddev-webserver:20250307_rfay_xhgui
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web  1/11] FROM docker.io/ddev/ddev-webserver:20250307_rfay_xhgui
#4 CACHED

#5 [web  2/11] RUN getent group tty || groupadd tty
#5 0.070 tty:x:5:
#5 DONE 0.1s

#6 [web  3/11] RUN (groupadd --gid 20 "rfay" || groupadd "rfay" || true) && (useradd -G tty -l -m -s "/bin/bash" --gid "rfay" --comment '' --uid 501 "rfay" || useradd -G tty -l -m -s "/bin/bash" --gid "rfay" --comment '' "rfay" || useradd  -G tty -l -m -s "/bin/bash" --gid "20" --comment '' "rfay" || useradd -G tty -l -m -s "/bin/bash" --comment '' rfay )
#6 0.077 groupadd: GID '20' already exists
#6 0.092 useradd warning: rfay's uid 501 outside of the UID_MIN 1000 and UID_MAX 60000 range.
#6 DONE 0.1s

#7 [web  4/11] RUN mkdir -p /home/rfay && chown rfay /home/rfay && chmod 600 /home/rfay/.pgpass
#7 DONE 0.1s

#8 [web  5/11] RUN composer global require perftools/php-profiler --dev
#8 0.151 Changed current directory to /home/rfay/.composer
#8 0.554 ./composer.json has been created
#8 0.570 Running composer update perftools/php-profiler
#8 0.575 Loading composer repositories with package information
#8 1.044 Updating dependencies
#8 1.059 Lock file operations: 1 install, 0 updates, 0 removals
#8 1.059   - Locking perftools/php-profiler (1.2.0)
#8 1.060 Writing lock file
#8 1.060 Installing dependencies from lock file (including require-dev)
#8 1.061 Package operations: 1 install, 0 updates, 0 removals
#8 1.064   - Downloading perftools/php-profiler (1.2.0)
#8 1.799   - Installing perftools/php-profiler (1.2.0): Extracting archive
#8 2.268 7 package suggestions were added by new dependencies, use `composer suggest` to see details.
#8 2.268 Generating autoload files
#8 2.274 No security vulnerability advisories found.
#8 2.274 Using version ^1.2 for perftools/php-profiler
#8 DONE 2.3s

#9 [web  6/11] RUN START_SCRIPT_TIMEOUT=30 mariadb-client-install.sh || true
#9 0.095 This script is not intended to run with mariadb:10.11
#9 DONE 0.1s

#10 [web  7/11] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || log-stderr.sh composer self-update --2 || true
#10 0.147 Storing "stable" as default update channel for the next self-update run.
#10 0.436 You are already using the latest available Composer version 2.8.6 (stable channel).
#10 0.811 You are already using the latest available Composer version 2.8.6 (2.x channel).
#10 DONE 0.8s

#11 [web  8/11] RUN timeout 30 apt-get update || true
#11 0.273 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#11 0.344 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#11 0.370 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#11 0.394 Get:4 http://deb.debian.org/debian bookworm/main arm64 Packages [8692 kB]
#11 0.576 Get:5 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm InRelease [3675 B]
#11 0.739 Get:7 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm InRelease [3681 B]
#11 0.759 Get:8 http://nginx.org/packages/debian bookworm InRelease [2869 B]
#11 0.869 Get:9 https://packages.sury.org/php bookworm InRelease [7551 B]
#11 0.916 Get:10 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [4422 B]
#11 0.958 Get:11 http://nginx.org/packages/debian bookworm/nginx arm64 Packages [17.8 kB]
#11 1.096 Get:12 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm/main arm64 Packages [4355 B]
#11 1.150 Get:6 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease [4628 B]
#11 1.198 Get:13 http://packages.blackfire.io/debian any InRelease [29.2 kB]
#11 1.227 Get:14 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm/main arm64 Packages [3336 B]
#11 1.355 Get:15 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main arm64 Packages [8576 B]
#11 1.372 Get:16 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [129 kB]
#11 1.641 Get:17 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main arm64 Packages [35.2 kB]
#11 1.677 Get:18 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [512 B]
#11 1.677 Get:19 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [246 kB]
#11 1.814 Get:21 https://packages.sury.org/php bookworm/main arm64 Packages [252 kB]
#11 1.884 Get:22 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main arm64 Packages [345 kB]
#11 1.887 Get:20 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main amd64 Packages [42.1 kB]
#11 2.580 Get:23 http://packages.blackfire.io/debian any/main arm64 Packages [30.8 kB]
#11 2.605 Fetched 10.1 MB in 2s (4154 kB/s)
#11 2.605 Reading package lists...
#11 DONE 2.9s

#12 [web  9/11] RUN curl -I https://www.google.com
#12 0.114   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#12 0.114                                  Dload  Upload   Total   Spent    Left  Speed
#12 0.114 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#12 0.257 HTTP/2 200 
#12 0.257 content-type: text/html; charset=ISO-8859-1
#12 0.257 content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-myW1h8QtEdiGMv7FpUMhdw' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
#12 0.257 accept-ch: Sec-CH-Prefers-Color-Scheme
#12 0.257 p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
#12 0.257 date: Sun, 30 Mar 2025 15:15:28 GMT
#12 0.257 server: gws
#12 0.257 x-xss-protection: 0
#12 0.257 x-frame-options: SAMEORIGIN
#12 0.257 expires: Sun, 30 Mar 2025 15:15:28 GMT
#12 0.257 cache-control: private
#12 0.257 set-cookie: AEC=AVcja2cdw7ctNIEdZZk7qQCLEfzZyv7RwDlOugoZnxBnxvzbIyq_TCO7B5E; expires=Fri, 26-Sep-2025 15:15:28 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#12 0.257 set-cookie: NID=522=U7UYM5mZ_RRx8ikRjpWmFdvl_fk4ol1X-O67nm8gSqeJIN0ViI-6IQhaJD0JR4HaQg0fZxK3tgNB3z3s9GQZrTkpoREIXsNb9d836I1oYf7c6RKEsibQjF5232GTbwB5mHyMNiBLkklzaBg-iyQ7gK8J305vf5mO_ov1vOtrvE_OnIwE02Vd4X_ou89R9Rpkl1ZhZkrVqgGTBHkhVAAW; expires=Mon, 29-Sep-2025 15:15:28 GMT; path=/; domain=.google.com; HttpOnly
#12 0.257 alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
#12 0.257 
#12 DONE 0.3s

#13 [web 10/11] RUN chmod 777 /run/php /var/log
#13 DONE 0.1s

#14 [web 11/11] RUN mkdir -p /tmp/xhprof && chmod -R ugo+w /etc/php /var/lib/php /tmp/xhprof
#14 DONE 0.3s

#15 [web] exporting to image
#15 exporting layers
#15 exporting layers 0.2s done
#15 writing image sha256:c77b3274b1cc099e8d86ad80f8fa5d634866df4065c3ccb3ec3293f98c596d87 done
#15 naming to docker.io/ddev/ddev-webserver:20250307_rfay_xhgui-tryddevproject-9694-built done
#15 DONE 0.2s

#16 [web] resolving provenance for metadata file
#16 DONE 0.0s
 web  Built
Rebuilt Docker cache for project tryddevproject-9694 in 8s
Network ddev_default created
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Using custom web-build configuration: [
	/Users/rfay/workspace/tryddevproject-9694/.ddev/web-build/Dockerfile.test
]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
Building project images....
Project images built in 1s.
 Network ddev-tryddevproject-9694_default  Created
 Container ddev-tryddevproject-9694-web  Created
 Container ddev-tryddevproject-9694-db  Created
 Container ddev-tryddevproject-9694-web  Started
 Container ddev-tryddevproject-9694-db  Started
Starting Mutagen sync process...
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st tryddevproject-9694 -l'
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started

======== Project startup ========
Starting tryddevproject-9694...
2025-03-30T09:15:50.385 GetAvailableRouterPort(): Router is healthy and running
2025-03-30T09:15:50.387 GetAvailableRouterPort(): proposedPort 80 already bound on ddev-router, accepting it
2025-03-30T09:15:50.387 GetAvailableRouterPort(): Router is healthy and running
2025-03-30T09:15:50.388 GetAvailableRouterPort(): proposedPort 443 already bound on ddev-router, accepting it
2025-03-30T09:15:50.389 GetAvailableRouterPort(): Router is healthy and running
2025-03-30T09:15:50.39 GetAvailableRouterPort(): proposedPort 8025 already bound on ddev-router, accepting it
2025-03-30T09:15:50.391 GetAvailableRouterPort(): Router is healthy and running
2025-03-30T09:15:50.392 GetAvailableRouterPort(): proposedPort 8026 already bound on ddev-router, accepting it
2025-03-30T09:15:50.413 Pulled image for ddev/ddev-webserver:20250307_rfay_xhgui
2025-03-30T09:15:50.413 Pulled image for busybox:stable
2025-03-30T09:15:50.414 Pulled image for ddev/ddev-utilities
2025-03-30T09:15:50.414 Pulled image for ddev/ddev-ssh-agent:v1.24.3
2025-03-30T09:15:50.415 Pulled image for ddev/ddev-traefik-router:20250318_stasadev_proxy_load_balancer_alias
2025-03-30T09:15:50.69 GetDockerContext: contextInfo='default unix:///Users/rfay/.orbstack/run/docker.sock'
2025-03-30T09:15:50.69 Using Docker context default (unix:///Users/rfay/.orbstack/run/docker.sock)
2025-03-30T09:15:50.944 chowning /mnt/ddev-global-cache and /var/lib/mysql to 501
2025-03-30T09:15:51.148 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 501
Using custom web-build configuration: [
	/Users/rfay/workspace/tryddevproject-9694/.ddev/web-build/Dockerfile.test
]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
2025-03-30T09:15:51.152 host.docker.internal='' because no other case was discovered
2025-03-30T09:15:51.153 Using automatically detected timezone: TZ=America/Denver
2025-03-30T09:15:51.193 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.24.3
2025-03-30T09:15:51.194 Pulled image for ddev/ddev-webserver:20250307_rfay_xhgui
2025-03-30T09:15:51.194 Pulled image for ddev/ddev-ssh-agent:v1.24.3
2025-03-30T09:15:51.195 Pulled image for ddev/ddev-traefik-router:20250318_stasadev_proxy_load_balancer_alias
Building project images...
2025-03-30T09:15:51.196 Executing docker-compose -f /Users/rfay/workspace/tryddevproject-9694/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.
Project images built in 1s.
2025-03-30T09:15:52.501 Removing dangling images for the project ddev-tryddevproject-9694
2025-03-30T09:15:52.506 Executing docker-compose -f /Users/rfay/workspace/tryddevproject-9694/.ddev/.ddev-docker-compose-full.yaml up -d
 Container ddev-tryddevproject-9694-web  Recreate
 Container ddev-tryddevproject-9694-db  Recreate
 Container ddev-tryddevproject-9694-db  Recreated
 Container ddev-tryddevproject-9694-web  Recreated
 Container ddev-tryddevproject-9694-db  Started
 Container ddev-tryddevproject-9694-web  Started
2025-03-30T09:16:03.148 VIRTUAL_HOST=tryddevproject-9694.ddev.site for web
2025-03-30T09:16:03.148 HTTP_EXPOSE=80:80,8025:8025 for web
2025-03-30T09:16:03.148 HTTPS_EXPOSE=443:80,8026:8025 for web
2025-03-30T09:16:03.148 VIRTUAL_HOST=tryddevproject-9694.ddev.site for xhgui
2025-03-30T09:16:03.148 HTTP_EXPOSE=8143:80 for xhgui
2025-03-30T09:16:03.148 HTTPS_EXPOSE=8142:80 for xhgui
2025-03-30T09:16:03.395 Copied /Users/rfay/workspace/tryddevproject-9694/.ddev/traefik:CopyIntoVolume_msfgvoctmqvn into /mnt/v/traefik in 15.839458ms
2025-03-30T09:16:03.408 Exec chown -R 501 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-03-30T09:16:03.51 Copied Traefik certs in /Users/rfay/workspace/tryddevproject-9694/.ddev/traefik/certs to ddev-global-cache/traefik
Starting Mutagen sync process...
2025-03-30T09:16:03.561 Using Mutagen config file /Users/rfay/workspace/tryddevproject-9694/.ddev/mutagen/mutagen.yml

2025-03-30T09:16:04.182 Mutagen status after sync: ok
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st tryddevproject-9694 -l'
2025-03-30T09:16:04.183 Running /start.sh in ddev-webserver
Waiting for containers to become ready: [web db]
2025-03-30T09:16:06.579 Copied /Users/rfay/.ddev/commands:CopyIntoVolume_tltklikgijlx into /mnt/v/global-commands in 32.938333ms
2025-03-30T09:16:06.591 Exec chown -R 501 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2025-03-30T09:16:06.725 Testing to see if /mnt/ddev_config is properly mounted
2025-03-30T09:16:06.772 Getting stderr output from 'log-stderr.sh --show'
Starting ddev-router if necessary...
2025-03-30T09:16:07.117 Copied /Users/rfay/.ddev/traefik:CopyIntoVolume_afauubldxxan into /mnt/v/traefik in 18.233584ms
2025-03-30T09:16:07.129 Exec chown -R 501 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-03-30T09:16:07.209 Copied global Traefik config in /Users/rfay/.ddev/traefik/certs to ddev-global-cache/traefik
2025-03-30T09:16:07.246 Waiting for ddev-router to become ready, timeout=60
2025-03-30T09:16:07.752 ddev-router is ready
Successfully started tryddevproject-9694
Your project can be reached at https://tryddevproject-9694.ddev.site
See 'ddev describe' for alternate URLs.

======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0   HTTP/1.1 200 OK
Server: nginx
Date: Sun, 30 Mar 2025 15:16:09 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

  0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

======== curl -I of http://127.0.0.1:33254 (web container http docker bind port) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 30 Mar 2025 15:16:09 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-9694.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Sun, 30 Mar 2025 15:16:09 GMT
Server: nginx
Vary: Accept-Encoding

======== Full curl of http://tryddevproject-9694.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   286    0   286    0     0   109k      0 --:--:-- --:--:-- --:--:--  139k
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/var/folders/z5/lhpyjf2n7xj2djl0bw_7kb3m0000gn/T/ddev-debug-test.txt</b><br />
file:///var/folders/z5/lhpyjf2n7xj2djl0bw_7kb3m0000gn/T/ddev-debug-test.txt<br />

======== Full curl of https://tryddevproject-9694.ddev.site (router https URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   286    0   286    0     0  12623      0 --:--:-- --:--:-- --:--:-- 13000
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/var/folders/z5/lhpyjf2n7xj2djl0bw_7kb3m0000gn/T/ddev-debug-test.txt</b><br />
file:///var/folders/z5/lhpyjf2n7xj2djl0bw_7kb3m0000gn/T/ddev-debug-test.txt<br />

======== Curl google.com to check internet access and VPN ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-fRVDJYnn-iNk3Bq_w9pH1w' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Sun, 30 Mar 2025 15:16:09 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Sun, 30 Mar 2025 15:16:09 GMT
cache-control: private
set-cookie: AEC=AVcja2fObVFBzyYoUmyWmHYS8tXWp9FYYCKtpjMPd1PMB9f3ZMAudw8zuA; expires=Fri, 26-Sep-2025 15:16:09 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: NID=522=L3hcKX_PwmeFPz1Yc70cNJETemkFsOwWbepiCEc7Bclh36folGLbJR4zqD7Ol3xQIPqWyiTB8_k8-qw-hxdKdlSXep7rltdot8YU90-zqxHg4B0WAIZCvUQrXtxiU0lwfj1HNGcCleBBUm_jGJ_WeN5NkVPbbylTKH1JGDMw-R_iWkkWxTUb637HFPPteotZcPmDHpfTE5v5wNr6gYj8; expires=Mon, 29-Sep-2025 15:16:09 GMT; path=/; domain=.google.com; HttpOnly
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

======== host.docker.internal status ========
PING host.docker.internal (0.250.250.254) 56(84) bytes of data.
64 bytes from host.orb.internal (0.250.250.254): icmp_seq=1 ttl=62 time=0.113 ms

--- host.docker.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.113/0.113/0.113/0.000 ms

======== Project ownership on host ========
drwxr-xr-x@ 4 rfay  staff  128 Mar 30 09:15 ../tryddevproject-9694

======== Project ownership in container ========
drwxr-xr-x 1 rfay dialout 16 Mar 30 09:16 //var/www/html

======== In-container filesystem ========
Filesystem     Type   1K-blocks     Used  Available Use% Mounted on
/dev/vdb1      btrfs 1274955236 11703820 1263251416   1% /var/www

======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting for ddev launch to complete before deleting project

Cleanup: deleting test project tryddevproject-9694
 Container ddev-tryddevproject-9694-db  Stopped
 Container ddev-tryddevproject-9694-web  Stopped
 Container ddev-tryddevproject-9694-web  Stopped
 Container ddev-tryddevproject-9694-db  Stopped
 Container ddev-tryddevproject-9694-db  Removed
 Container ddev-tryddevproject-9694-web  Removed
 Network ddev-tryddevproject-9694_default  Removed
Volume tryddevproject-9694-mariadb for project tryddevproject-9694 was deleted
Volume tryddevproject-9694-postgres for project tryddevproject-9694 was deleted
Volume tryddevproject-9694_project_mutagen for project tryddevproject-9694 was deleted
Project tryddevproject-9694 was deleted. Your code and configuration are unchanged.

Please remove the files from this test with 'rm -r ../tryddevproject-9694'

</details>

### Expected Behavior

TYPO3 should work as always.

### Actual Behavior

After installing TYPO3 per the normal quickstart I get lots of fatal errors. 

### Steps To Reproduce

1. `ddev config global --xhprof-mode=xhgui`
2. Use the quickstart to create a TYPO3 project. Tell it to create a default page. 
3. Open the TYPO3 back-end (/typo3)
4. Edit the default page (you don't have to do anything). Click save. Everything works fine.
5. `ddev xhgui on`
6. Edit the default page and save. Now you get a huge stack trace as below. (Just a browser refresh gets the crash)
7. `ddev xhgui off`
8. Now you can edit and save again. (Just a browser refresh of the edit page is adequate)

The most suspicious thing to me is "The following paths were checked: /home/rfay/.composer/vendor/typo3/cms-backend/Resources/Private/Templates". I don't understand why it's using the default global composer path, which is not persistent anyway.

```
(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Default->Form/FilesControlContainer" in format ".html", but none of the paths contained the expected template file (Default/Form/FilesControlContainer.html). The following paths were checked: /home/rfay/.composer/vendor/typo3/cms-backend/Resources/Private/Templates

in /var/www/html/vendor/typo3fluid/fluid/src/View/TemplatePaths.php line 586
        }
        $templateReference = $this->resolveTemplateFileForControllerAndActionAndFormat($controller, $action);
        if (!file_exists((string)$templateReference) && $templateReference !== 'php://stdin') {
            $format = $this->getFormat();
            throw new InvalidTemplateResourceException(
                sprintf(
                    'Tried resolving a template file for controller action "%s->%s" in format ".%s", but none of the paths ' .
                    'contained the expected template file (%s). %s',
                    $controller,
at TYPO3Fluid\Fluid\View\TemplatePaths->getTemplateSource()
in /var/www/html/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php line 347
        $actionName = $renderingContext->getControllerAction();
        $parsedTemplate = $templateParser->getOrParseAndStoreTemplate(
            $templatePaths->getTemplateIdentifier($controllerName, $actionName),
            function ($parent, TemplatePaths $paths) use ($controllerName, $actionName) {
                return $paths->getTemplateSource($controllerName, $actionName);
            },
        );
        if ($parsedTemplate->isCompiled()) {
            $parsedTemplate->addCompiledNamespaces($this->baseRenderingContext);
at TYPO3Fluid\Fluid\View\AbstractTemplateView->TYPO3Fluid\Fluid\View\{closure}()
in /var/www/html/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php line 168

    protected function parseTemplateSource(string $templateIdentifier, \Closure $templateSourceClosure): ParsingState
    {
        $parsedTemplate = $this->parse(
            $templateSourceClosure($this, $this->renderingContext->getTemplatePaths()),
            $templateIdentifier,
        );
        $parsedTemplate->setIdentifier($templateIdentifier);
        $this->parsedTemplates[$templateIdentifier] = $parsedTemplate;
at TYPO3Fluid\Fluid\Core\Parser\TemplateParser->parseTemplateSource()
in /var/www/html/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php line 153
            if ($parsedTemplate instanceof UncompilableTemplateInterface) {
                $parsedTemplate = $this->parseTemplateSource($templateIdentifier, $templateSourceClosure);
            }
        } else {
            $parsedTemplate = $this->parseTemplateSource($templateIdentifier, $templateSourceClosure);
            try {
                $compiler->store($templateIdentifier, $parsedTemplate);
            } catch (StopCompilingException $stop) {
                $this->renderingContext->getErrorHandler()->handleCompilerError($stop);
at TYPO3Fluid\Fluid\Core\Parser\TemplateParser->getOrParseAndStoreTemplate()
in /var/www/html/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php line 344
        $templatePaths = $renderingContext->getTemplatePaths();
        $templateParser = $renderingContext->getTemplateParser();
        $controllerName = $renderingContext->getControllerName();
        $actionName = $renderingContext->getControllerAction();
        $parsedTemplate = $templateParser->getOrParseAndStoreTemplate(
            $templatePaths->getTemplateIdentifier($controllerName, $actionName),
            function ($parent, TemplatePaths $paths) use ($controllerName, $actionName) {
                return $paths->getTemplateSource($controllerName, $actionName);
            },
at TYPO3Fluid\Fluid\View\AbstractTemplateView->getCurrentParsedTemplate()
in /var/www/html/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php line 139
            $actionName = ucfirst($actionName);
            $renderingContext->setControllerAction($actionName);
        }
        try {
            $parsedTemplate = $this->getCurrentParsedTemplate();
        } catch (PassthroughSourceException $error) {
            return $error->getSource();
        }
```

Image

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #7170

The problem with TYPO3 can be solved by making only the following change:

```diff
-$globalAutoload = $homeDir . '/.composer/vendor/autoload.php';
+$globalAutoload = $homeDir . '/.composer/vendor/perftools/php-profiler/autoloader.php';
```

The above is recommended by the upstream https://github.com/perftools/php-profiler#autoloader

Global `~/.composer/vendor/autoload.php` affected TYPO3 files, which was wrong.

## How This PR Solves The Issue

- We don't care about PHP version, [perftools/php-profiler](https://packagist.org/packages/perftools/php-profiler) can be used with `php: ^5.3.0 || ^7.0 || ^8.0`
- Previous usage of `ddev composer global require` is tricky and can break Composer for our users. We don't need to have global `composer.json` and use its autoloader, I moved the php-profiler to `/usr/local/xhgui.collector/php-profiler`.
- Creates an actual test that fails on DDEV HEAD.
- Don't allow to run `ddev xhgui` with hardened images (because we don't install the required files there).

## Manual Testing Instructions

See the issue.

Follow https://ddev.readthedocs.io/en/stable/users/quickstart/#typo3

And run:

```
ddev xhgui
ddev launch
```

Don't see this:

image

### CODE REVIEW

File: pkg/ddevapp/config.go [hunk 1]
```diff
@@ -1113,15 +1113,6 @@ ENV N_PREFIX=/home/$username/.n
...
 	}
-	// TODO: I would rather put this in the ddev-webserver image but...
-	// - We don't know the username yet there, so would have to put in /usr/local/composer
-	// - /usr/local/composer would then have to be set as COMPOSER_HOME
-	// - We could set the permissions here so people could use it
-	// - BUT... we don't know the PHP version until runtime.
-	// - Oh, but we don't know the PHP version here yet because it's not runtime yet.
-	// - Maybe this can be done or checked by `ddev xhgui` ?
-	// Add php-profiler for xhgui
-	extraWebContent = extraWebContent + "\nUSER ${username}\nRUN composer global require perftools/php-profiler --dev\nUSER root\n"
```
Comment (rfay) [inline pkg/ddevapp/config.go:1124]: Do we need to chown/chmod the installed php-profiler stuff in start.sh now that it's installed at image build time?

**Review by rfay — APPROVED** [review]
This is correct and lovely and solves the problem, thank you!

File: pkg/ddevapp/config.go (hunk 1 above)
Comment (stasadev) [reply pkg/ddevapp/config.go:1124]: I pushed the image (without running tests):

```
docker pull ddev/ddev-webserver:20250331_stasadev_xhgui_php-profiler
docker run -it --rm ddev/ddev-webserver-prod:20250331_stasadev_xhgui_php-profiler ls -la /usr/local/xhgui.collector
```
