### PR TITLE
test: fix TestNetworkAliases, fixes #7657

### LINKED ISSUE #7657: TestNetworkAliases sometimes fails
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://docs.ddev.com/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://docs.ddev.com/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

It should work.

### Actual Behavior

Failures in tests with Mutagen enabled:

- tests (mutagen, true) https://github.com/ddev/ddev/actions/runs/17977559504/job/51147551469
- tests (no-bind-mounts, true) https://github.com/ddev/ddev/actions/runs/17977559504/job/51147551491
- tests (race-detection, true) https://github.com/ddev/ddev/actions/runs/17977559504/job/51147551481

The other day it failed in `ddev-windows-mutagen`.

The error is intermittent and `TestNetworkAliases` has multiple curl calls.

I see the same failures without Mutagen

### Steps To Reproduce

Try to reproduce locally by running `TestNetworkAliases`.

### Anything else?

Test was added in:

- #7642

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #7657

## How This PR Solves The Issue

- Uses require instead of assert for network tests
- Fixes assign for app1 and app2 - that's why tests failed sometimes
- Runs `TestNetworkAliases` everywhere, I don't think that we can get "connection reset by peer" inside containers.

### CODE REVIEW

**Comment by stasadev** [comment]
Looking at `TestInternalAndExternalAccessToURL`, I realized that we needed more waiting time after `ddev start` as in that test.

So this is most likely a problem with the test, and not with DDEV logic.

**Comment by rfay** [comment]
Normally `ddev start` finishes everything; mutagen sync is complete when app.Start() finishes.

File: pkg/dockerutil/networks_test.go [hunk 1]
```diff
@@ -213,23 +206,27 @@ func TestNetworkAliases(t *testing.T) {
...
+			require.NoError(t, err)
 
 			apps = append(apps, app)
 		}
 	})
 
 	// Get app references after setup
 	var app1, app2 *ddevapp.DdevApp
-	if len(apps) >= 2 {
-		app1, app2 = apps[0], apps[1]
```
Comment (stasadev) [inline pkg/dockerutil/networks_test.go:232]: I found out what was wrong: sometimes `app1` was actually `app2`, that's why Traefik failed with 404, because there was nothing running on that port.

Incorrect order = failed checks.

**Review by rfay — APPROVED** [review]
Thanks, congrats!
