### PR TITLE
fix: don't panic when running project in not allowed location, fixes #6925

### LINKED ISSUE #6925: "panic: runtime error: invalid memory address or nil pointer dereference" - ddev v1.24.2
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
admin1@erazer:/tmp$ ddev debug test
Please make sure you have already looked at troubleshooting guide: 
https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/ 
Simple things to check:
* Use latest stable DDEV version
* ddev poweroff
* Restart Docker Provider
* Reboot computer
* Temporarily disable VPN and firewall
* Remove customizations like 'docker-compose.*.yaml' and PHP/Apache/Nginx config while debugging. 
Resulting output will be written to:
/tmp/ddev-debug-test.txt
file:///tmp/ddev-debug-test.txt
Please provide the file for support in Discord or the issue queue. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa67cf8]

goroutine 1 [running]:
github.com/ddev/ddev/pkg/ddevapp.GetActiveProjects()
        /home/runner/work/ddev/ddev/pkg/ddevapp/utils.go:51 +0x238
github.com/ddev/ddev/cmd/ddev/cmd.init.func28(0x1338380?, {0x1367f20?, 0x0?, 0x0?})
        /home/runner/work/ddev/ddev/cmd/ddev/cmd/debug-test.go:51 +0x4b6
github.com/spf13/cobra.(*Command).execute(0x1338380, {0x1367f20, 0x0, 0x0})
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x133cb60)
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:1041
github.com/ddev/ddev/cmd/ddev/cmd.Execute()
        /home/runner/work/ddev/ddev/cmd/ddev/cmd/root.go:122 +0x1a
main.main()
        /home/runner/work/ddev/ddev/cmd/ddev/main.go:27 +0xd3

```
</details>

### Expected Behavior

the expected behaviour is that the ddev commands run as they did before on v1.24.1

### Actual Behavior

~~~
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa67cf8]
~~~

### Steps To Reproduce

any command like these (tested)

~~~
ddev poweroff 
ddev list
ddev start
ddev restart
ddev debug test
~~~

results in 

~~~
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa67cf8]
~~~

and this is since this ddev was updated from former `v1.24.1` => to =>  `v1.24.2` this morning on my kubuntu linux desktop 

---

_version_  
~~~
admin1@erazer:/tmp$ ddev version 
 ITEM             VALUE                                    
 DDEV version     v1.24.2                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.24.2 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.24.2              
 docker           26.1.3                                   
 docker-api       1.45                                     
 docker-compose   v2.32.4                                  
 docker-platform  linux-docker                             
 global-ddev-dir  /home/admin1/.ddev                       
 mutagen          0.18.0                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.24.2         
 web              ddev/ddev-webserver:v1.24.2
~~~

### Anything else?

(K)Ubuntu 24.04.1 LTS

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #6925

The problem is that when you upgrade from DDEV v1.24.1 to v1.24.2 and have a *running* project in a not allowed place, you will see panic:

```
$ ddev poweroff
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa67cf8]

goroutine 1 [running]:
github.com/ddev/ddev/pkg/ddevapp.GetActiveProjects()
        /home/runner/work/ddev/ddev/pkg/ddevapp/utils.go:51 +0x238
...
```

---

The change was made in:

- #6852

Previously, the code was:

https://github.com/ddev/ddev/blob/4936e6958fec52fff844df64f2650db6148348d3/pkg/ddevapp/config.go#L79C1-L81C3

```go
if appRoot == filepath.Dir(globalconfig.GetGlobalDdevDir()) || app.AppRoot == homeDir {
	return nil, fmt.Errorf("ddev config is not useful in your home directory (%s)", homeDir)
}
```

and now it is:

https://github.com/ddev/ddev/blob/8cded44666ff3dab8b2132feac34aa25795030af/pkg/ddevapp/config.go#L78-L80

As you can see, it used to return `nil`, so theoretically there was panic all this time, I just added a new condition that triggered it.

## How This PR Solves The Issue

Fixes panic by returning `app` instead of nothing.

## Manual Testing Instructions

To reproduce:

Using DDEV v1.24.1, create a project at not allowed location, and start it:

```
mkdir -p ~/workspace && cd ~/workspace
mkdir good && cd good && ddev config --auto
cd ~/workspace
ddev config --auto
ddev start
```

Upgrade DDEV to v1.24.2 and run `ddev list`, see panic.

Then run `ddev list` using this PR (without doing `ddev poweroff`) the forbidden project will show up in the list (without a warning, because the project is in the *running* state).

Run `ddev poweroff`, and see the warning in `ddev list`:

```
$ ddev list
Something went wrong with /home/stas/workspace: project is not allowed in /home/stas/workspace because another project exists in the subdirectory /home/stas/workspace/good
Unlist this project (if it exists) with 'cd "/home/stas/workspace" && ddev stop --unlist'
Or run 'ddev stop --unlist' for all projects in the subdirectories of this project directory
...
```

Run the recommended command:
```
Unlist this project (if it exists) with 'cd "/home/stas/workspace" && ddev stop --unlist'
```

`ddev list` should not show any warnings.

And `ddev start` won't be possible:
```
$ ddev start
Failed to start project(s): a project is not allowed in /home/stas/workspace because another project exists in the subdirectory /home/stas/workspace/good
Unlist this project (if it exists) with 'cd "/home/stas/workspace" && ddev stop --unlist'
Or run 'ddev stop --unlist' for all projects in the subdirectories of this project directory
```

### CODE REVIEW

File: pkg/ddevapp/config.go [hunk 1]
```diff
@@ -1385,28 +1387,37 @@ func WriteImageDockerfile(fullpath string, contents []byte) error {
...
+	projectMap := globalconfig.GetGlobalProjectList()
+	projectList := make([]*globalconfig.ProjectInfo, 0, len(projectMap))
+	for _, project := range projectMap {
+		projectList = append(projectList, project)
+	}
+	// Sort the projects by AppRoot in reverse alphabetical order,
+	// so deeper-level projects (longer paths) take precedence
+	sort.Slice(projectList, func(i, j int) bool {
+		return projectList[i].AppRoot > projectList[j].AppRoot
+	})
```
Comment (stasadev) [inline pkg/ddevapp/config.go:1412]: Sorting is needed because if a project in the parent directory is returned before another project in the subdirectory, it will not show any warning.

File: pkg/ddevapp/config.go [hunk 2]
```diff
@@ -1385,28 +1387,37 @@ func WriteImageDockerfile(fullpath string, contents []byte) error {
...
-	projectList := globalconfig.GetGlobalProjectList()
+		return fmt.Errorf("a project is not allowed in the directory used for DDEV development (%v)", app.AppRoot)
+	}
+	projectMap := globalconfig.GetGlobalProjectList()
+	projectList := make([]*globalconfig.ProjectInfo, 0, len(projectMap))
+	for _, project := range projectMap {
+		projectList = append(projectList, project)
+	}
+	// Sort the projects by AppRoot in reverse alphabetical order,
+	// so deeper-level projects (longer paths) take precedence
```
Comment (rfay) [inline pkg/ddevapp/config.go:1409]: The comment can probably be improved; it's not checking for longer paths but alpha, which happens to get longer paths. Maybe just change this line's comment to say why instead of focusing on "longer paths"

File: pkg/ddevapp/config.go [hunk 3]
```diff
@@ -1385,28 +1387,37 @@ func WriteImageDockerfile(fullpath string, contents []byte) error {
...
 	rel, err = filepath.Rel(globalconfig.GetGlobalDdevDir(), app.AppRoot)
 	if err == nil && !strings.HasPrefix(rel, "..") {
-		return fmt.Errorf("'ddev config' is not allowed in your global config directory (%v)", app.AppRoot)
+		return fmt.Errorf("a project is not allowed in your global config directory (%v)", app.AppRoot)
 	}
 	if fileutil.FileExists(filepath.Join(app.AppRoot, "cmd/ddev/main.go")) && fileutil.FileExists(filepath.Join(app.AppRoot, "cmd/ddev_gen_autocomplete/ddev_gen_autocomplete.go")) {
-		return fmt.Errorf("'ddev config' is not allowed in the directory used for DDEV development (%v)", app.AppRoot)
-	}
-	projectList := globalconfig.GetGlobalProjectList()
+		return fmt.Errorf("a project is not allowed in the directory used for DDEV development (%v)", app.AppRoot)
```
Comment (rfay) [inline pkg/ddevapp/config.go:1401]: Nit: I don't think this error message is obvious, but only we should be hitting it.

```suggestion
		return fmt.Errorf("a project cannot be created in the DDEV source code (%v)", app.AppRoot)
```

File: pkg/ddevapp/config.go (hunk 2 above)
Comment (rfay) [reply pkg/ddevapp/config.go:1409]: However, this could possibly be sorted by AppRoot length as well. I think the reverse alpha sort might be better.

**Review by rfay — APPROVED** [review]
Thanks for fixing this so fast and understanding it so fast. 

This approach works. It sure does seem like a lot of work and complexity, so I'm not terribly happy with the result. But I haven't thought of anything better at this point. It might be possible to combine the RunValidateConfig and HasAllowedLocation together, not sure. 

Options include sorting by path length instead of alpha, but I'm not sure how that helps. Also N^2 comparisons on an IsSubdirectory() function, which sounds ugly.

File: pkg/ddevapp/config_test.go [hunk 4]
```diff
@@ -87,26 +87,26 @@ func TestConfigHasAllowedLocation(t *testing.T) {
...
-	assert.Contains(err.Error(), "'ddev config' is not allowed in your global config directory")
+	assert.Contains(err.Error(), "is not allowed in your global config directory")
 
 	// Make sure we're not allowed to config in the root of ddev/ddev project itself.
 	// origDir is "pkg/ddevapp", we need to go two levels up.
 	tmpDir = filepath.Dir(filepath.Dir(origDir))
 	_, err = ddevapp.NewApp(tmpDir, false)
 	require.Error(t, err, "'ddev config' must not be allowed in %s", tmpDir)
-	assert.Contains(err.Error(), "'ddev config' is not allowed in the directory used for DDEV development")
+	assert.Contains(err.Error(), "is not allowed in the directory used for DDEV development")
```
[the remark this answers is not in the document]
Comment (stasadev) [reply pkg/ddevapp/config_test.go]: I changed it to `require`.

File: pkg/ddevapp/config.go (hunk 2 above)
Comment (stasadev) [reply pkg/ddevapp/config.go]: I hope I made it clear with more comments.

**Comment by stasadev** [comment]
Thank you for the review!

> It might be possible to combine the RunValidateConfig and HasAllowedLocation together, not sure.

The check for `RunValidateConfig` inside the function is much better, thanks!
