### PR TITLE
fix: check only for IPv4 in DNS lookup, fixes #6592

### LINKED ISSUE #6592: `ddev start` fails looking up AAAA record for *.ddev.site and then tries to add to hosts file
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```

======== Output file will be in /tmp/ddev-debug-test.txt ========


======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev
/bin/ddev

These config files were loaded for project typo3-v10: [/home/inf/PhpstormProjects/typo3-v10/.ddev/config.yaml]
name: typo3-v10
type: typo3
docroot: public
php_version: 7.2
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.23.4
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.11}
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 20
default_container_timeout: 120


======== existing project customizations ========
.ddev/db-build/Dockerfile.example
.ddev/web-build/Dockerfile.example


======== installed DDEV add-ons ========
No registered add-ons were found. Add-ons installed before DDEV v1.22.0 will not be listed.
Update them with `ddev get` so they'll be shown.


======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /home/inf/PhpstormProjects/typo3-v10
.ddev/mutagen/mutagen.yml not found


======== Creating dummy project named tryddevproject-6873 in ../tryddevproject-6873 ========
Creating a new DDEV project config in the current directory (/home/inf/PhpstormProjects/tryddevproject-6873)
Once completed, your configuration will be written to /home/inf/PhpstormProjects/tryddevproject-6873/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-6873' with docroot 'web' at '/home/inf/PhpstormProjects/tryddevproject-6873/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.


======== OS Information ========
Linux NOTEBOOK023 6.11.0-6-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Sep 25 11:41:23 UTC 2024 x86_64 GNU/Linux


======== User information ========
uid=1000(inf) gid=1000(inf) groups=1000(inf),90(network),96(scanner),98(power),108(vboxusers),971(docker),986(video),988(storage),990(optical),991(lp),994(disk),995(audio),998(wheel)


======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.23.4                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.4 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.4              
 docker           27.2.0                                   
 docker-api       1.47                                     
 docker-compose   v2.29.1                                  
 docker-platform  linux-docker                             
 global-ddev-dir  /home/inf/.ddev                          
 mutagen          0.17.2                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.23.4         
 web              ddev/ddev-webserver:v1.23.4              



======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 


======== DDEV global info ========
developer-mode=false
disable-http2=false
fail-on-hook-fail=false
instrumentation-opt-in=true
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.23.4
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/home/inf/.local/share/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=none
project-tld=ddev.site
required-docker-compose-version=v2.29.1
router=traefik
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=


======== DOCKER provider info ========
docker client location: -rwxr-xr-x 1 root root 27132440 29. Aug 18:44 /usr/bin/docker

docker client alternate locations:
/usr/bin/docker
/bin/docker

Docker provider: linux-docker
docker version: 
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.23.0
 Git commit:        3ab4256958
 Built:             Thu Aug 29 16:44:26 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.23.0
  Git commit:       3ab5c7d003
  Built:            Thu Aug 29 16:44:26 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c.m
 runc:
  Version:          1.1.14
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

DOCKER_DEFAULT_PLATFORM=notset
Docker platform: linux-docker
Using Docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.29.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 27.2.0
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:Filesystem                Size      Used Available Use% Mounted on
overlay                 451.4G    308.8G    119.6G  72% /


======== Existing docker containers ========
CONTAINER ID   IMAGE                               COMMAND     CREATED       STATUS    PORTS     NAMES
b3fb0dc77d32   phpstorm_helpers:PS-242.21829.154   "/bin/sh"   4 weeks ago   Created             phpstorm_helpers_PS-242.21829.154
474566b03e7d   phpstorm_helpers:PS-242.20224.427   "/bin/sh"   5 weeks ago   Created             phpstorm_helpers_PS-242.20224.427


======== mkcert information ========
/usr/bin/mkcert
/bin/mkcert
/home/inf/.local/share/mkcert
total 8
-r-------- 1 inf inf 2488 14. Mai 2019  rootCA-key.pem
-rw-r--r-- 1 inf inf 1631 14. Mai 2019  rootCA.pem


======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (::1) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.094 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.094/0.094/0.094/0.000 ms


======== ddev debug refresh ========
Rebuilding project images...
Rebuilding web image with `/home/inf/.ddev/bin/docker-compose -f /home/inf/PhpstormProjects/tryddevproject-6873/.ddev/.ddev-docker-compose-full.yaml build web --no-cache`
#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.34kB done
#1 WARN: InvalidDefaultArgInFrom: Default value for ARG $BASE_IMAGE results in empty or invalid base image name (line 6)
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/ddev/ddev-webserver:v1.23.4
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web 1/8] FROM docker.io/ddev/ddev-webserver:v1.23.4
#4 CACHED

#5 [web 2/8] RUN (groupadd --gid 1000 "inf" || groupadd "inf" || true) && (useradd  -l -m -s "/bin/bash" --gid "inf" --comment '' --uid 1000 "inf" || useradd  -l -m -s "/bin/bash" --gid "inf" --comment '' "inf" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "inf" || useradd -l -m -s "/bin/bash" --comment '' inf )
#5 DONE 0.4s

#6 [web 3/8] RUN mkdir -p /home/inf && chown inf /home/inf && chmod 600 /home/inf/.pgpass
#6 DONE 0.3s

#7 [web 4/8] RUN mariadb-client-install.sh || true
#7 0.216 This script is not intended to run with mariadb:10.11
#7 DONE 0.2s

#8 [web 5/8] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || composer self-update --2 || true
#8 0.415 Storing "stable" as default update channel for the next self-update run.
#8 0.599 Upgrading to version 2.8.1 (stable channel).
#8 0.651    
#8 1.377 Use composer self-update --rollback to return to version 2.7.7
#8 1.713 You are already using the latest available Composer version 2.8.1 (2.x channel).
#8 DONE 1.8s

#9 [web 6/8] RUN apt-get update
#9 0.382 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#9 0.400 Get:2 http://nginx.org/packages/debian bookworm InRelease [2869 B]
#9 0.480 Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#9 0.507 Get:4 http://nginx.org/packages/debian bookworm/nginx amd64 Packages [14.6 kB]
#9 0.519 Get:5 https://packages.sury.org/php bookworm InRelease [7551 B]
#9 0.531 Get:6 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#9 0.581 Get:7 http://deb.debian.org/debian bookworm/main amd64 Packages [8787 kB]
#9 0.593 Get:8 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm InRelease [3675 B]
#9 0.709 Get:9 https://packages.sury.org/php bookworm/main amd64 Packages [243 kB]
#9 0.775 Get:10 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm InRelease [3681 B]
#9 0.992 Get:12 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [4422 B]
#9 1.124 Get:13 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm/main amd64 Packages [4384 B]
#9 1.171 Get:14 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [129 kB]
#9 1.229 Get:15 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm/main amd64 Packages [3235 B]
#9 1.378 Get:16 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main amd64 Packages [7535 B]
#9 1.394 Get:11 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease [4625 B]
#9 1.479 Get:17 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 Packages [357 kB]
#9 2.213 Get:18 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main arm64 Packages [34.4 kB]
#9 2.835 Get:20 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [2468 B]
#9 2.835 Get:21 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB]
#9 3.042 Get:19 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main amd64 Packages [40.9 kB]
#9 3.776 Fetched 10.1 MB in 3s (2899 kB/s)
#9 3.776 Reading package lists...
#9 DONE 4.4s

#10 [web 7/8] RUN curl -I https://www.google.com
#10 0.289   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#10 0.289                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#10 0.624 HTTP/2 200 
#10 0.624 content-type: text/html; charset=ISO-8859-1
#10 0.624 content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-s5v0mLVFPx73HZpoW2AwcQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
#10 0.624 accept-ch: Sec-CH-Prefers-Color-Scheme
#10 0.624 p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
#10 0.624 date: Mon, 07 Oct 2024 12:41:13 GMT
#10 0.624 server: gws
#10 0.624 x-xss-protection: 0
#10 0.624 x-frame-options: SAMEORIGIN
#10 0.624 expires: Mon, 07 Oct 2024 12:41:13 GMT
#10 0.624 cache-control: private
#10 0.624 set-cookie: AEC=AVYB7cpUcg8e3R9SY8tRg8-sQ2-OkSsUpussM4NjoYR1d7abmXvQRIpJWA; expires=Sat, 05-Apr-2025 12:41:13 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#10 0.624 set-cookie: __Secure-ENID=22.SE=O3frAmfrP0puWNUVB9Z3_VEJOQ2JxWdJ4owqlov0HuG2v5LLc6YRCWoGbfbvgNJJXwGS7bjCEbsrthrqJnUcgkyiiU10pcCChhE7oqec63FzW1CImFKA1TPLN71KRWo9UBX-lNjpnus7BQlm7HMfTDmZN-5O_FA9pos98Z_sHoqQrdW4NzHEHu6fNJQa6__EMajY6Y_N3fEidHetL17lBVTHH7l5Q6CpU4EIB2s; expires=Fri, 07-Nov-2025 04:59:31 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#10 0.624 alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
#10 0.624 
#10 DONE 0.7s

#11 [web 8/8] RUN chmod 777 /run/php /var/log
#11 DONE 0.3s

#12 [web] exporting to image
#12 exporting layers
#12 exporting layers 2.3s done
#12 writing image sha256:fbff0ae962466016f741552faefa88a7177433787ec5d249404fda8878d5c818 done
#12 naming to docker.io/ddev/ddev-webserver:v1.23.4-tryddevproject-6873-built done
#12 DONE 2.3s

#13 [web] resolving provenance for metadata file
#13 DONE 0.0s
Refreshed Docker cache for project tryddevproject-6873 in 11s
Network ddev_default created
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
The hostname tryddevproject-6873.ddev.site is not currently resolvable, trying to add it to the hosts file
DDEV needs to run with administrative privileges.
This is normally to add unresolvable hostnames to the hosts file.
You may be required to enter your password for sudo or allow escalation.
DDEV is about to issue the command:
  sudo --preserve-env=HOME /usr/bin/ddev hostname tryddevproject-6873.ddev.site 127.0.0.1


Building project images...
.Project images built in 1s.
 Network ddev-tryddevproject-6873_default  Created
 Container ddev-tryddevproject-6873-web  Created
 Container ddev-tryddevproject-6873-db  Created
 Container ddev-tryddevproject-6873-db  Started
 Container ddev-tryddevproject-6873-web  Started
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started
Waiting for additional project containers to become ready...
Waiting 120s for additional project containers [ddev-tryddevproject-6873-db ddev-tryddevproject-6873-web] to become ready...
All project containers are now ready.


======== Project startup ========
Starting tryddevproject-6873...
2024-10-07T14:41:58.694 Pulled image for ddev/ddev-webserver:v1.23.4
2024-10-07T14:41:58.695 Pulled image for busybox:stable
2024-10-07T14:41:58.695 Pulled image for ddev/ddev-utilities
2024-10-07T14:41:58.696 Pulled image for ddev/ddev-ssh-agent:v1.23.4
2024-10-07T14:41:58.696 Pulled image for ddev/ddev-traefik-router:v1.23.4
2024-10-07T14:41:59.805 chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
2024-10-07T14:42:01.312 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
2024-10-07T14:42:01.335 host.docker.internal='' runtime.GOOS==linux and docker 20.10+
2024-10-07T14:42:01.428 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.23.4
2024-10-07T14:42:01.429 Pulled image for ddev/ddev-webserver:v1.23.4
2024-10-07T14:42:01.429 Pulled image for ddev/ddev-ssh-agent:v1.23.4
2024-10-07T14:42:01.43 Pulled image for ddev/ddev-traefik-router:v1.23.4
Building project images...
2024-10-07T14:42:01.43 Executing docker-compose -f /home/inf/PhpstormProjects/tryddevproject-6873/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.Project images built in 1s.
2024-10-07T14:42:02.431 Executing docker-compose -f /home/inf/PhpstormProjects/tryddevproject-6873/.ddev/.ddev-docker-compose-full.yaml up -d
 Container ddev-tryddevproject-6873-db  Recreate
 Container ddev-tryddevproject-6873-web  Recreate
 Container ddev-tryddevproject-6873-db  Recreated
 Container ddev-tryddevproject-6873-web  Recreated
 Container ddev-tryddevproject-6873-web  Started
 Container ddev-tryddevproject-6873-db  Started
2024-10-07T14:42:13.763 VIRTUAL_HOST=tryddevproject-6873.ddev.site for web
2024-10-07T14:42:13.763 HTTP_EXPOSE=80:80,8025:8025 for web
2024-10-07T14:42:13.763 HTTPS_EXPOSE=443:80,8026:8025 for web
2024-10-07T14:42:14.517 Copied /home/inf/PhpstormProjects/tryddevproject-6873/.ddev/traefik:CopyIntoVolume_apscwxiobpsz into /mnt/v/traefik in 82.595834ms
2024-10-07T14:42:14.613 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-10-07T14:42:14.796 Copied Traefik certs in /home/inf/PhpstormProjects/tryddevproject-6873/.ddev/traefik/certs to ddev-global-cache/traefik
2024-10-07T14:42:14.796 Running /start.sh in ddev-webserver
Waiting for containers to become ready: [web db]
2024-10-07T14:42:20.152 Copied /home/inf/.ddev/commands:CopyIntoVolume_crpccbuyzodx into /mnt/v/global-commands in 112.599965ms
2024-10-07T14:42:20.237 Exec chown -R 1000 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2024-10-07T14:42:20.563 Testing to see if /mnt/ddev_config is properly mounted
2024-10-07T14:42:20.765 Getting stderr output from 'log-stderr.sh --show'
Starting ddev-router if necessary...
2024-10-07T14:42:21.766 Copied /home/inf/.ddev/traefik:CopyIntoVolume_bskpzmysfaba into /mnt/v/traefik in 109.730655ms
2024-10-07T14:42:21.838 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-10-07T14:42:22.042 Copied global Traefik config in /home/inf/.ddev/traefik/certs to ddev-global-cache/traefik
 Container ddev-router  Running
2024-10-07T14:42:22.129 Waiting for ddev-router to become ready. docker inspect --format "{{json .State.Health }}" ddev-router
2024-10-07T14:42:22.635 ddev-router is ready
Waiting for additional project containers to become ready...
Waiting 120s for additional project containers [ddev-tryddevproject-6873-web ddev-tryddevproject-6873-db] to become ready...
All project containers are now ready.
Successfully started tryddevproject-6873
Project can be reached at https://tryddevproject-6873.ddev.site https://127.0.0.1:32821


======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 07 Oct 2024 12:42:24 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://127.0.0.1:32820 (web container http docker bind port) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 07 Oct 2024 12:42:24 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://tryddevproject-6873.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Mon, 07 Oct 2024 12:42:24 GMT
Server: nginx
Vary: Accept-Encoding



======== Full curl of http://tryddevproject-6873.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   198    0   198    0     0  48624      0 --:--:-- --:--:-- --:--:-- 66000
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Full curl of https://tryddevproject-6873.ddev.site (router https URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   198    0   198    0     0   8208      0 --:--:-- --:--:-- --:--:--  8250
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Curl google.com to check internet access and VPN ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-N7Ug6sTyiLgAMcK4iSG2FA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Mon, 07 Oct 2024 12:42:25 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Mon, 07 Oct 2024 12:42:25 GMT
cache-control: private
set-cookie: AEC=AVYB7cp1ApmDuXwCB57cz3W0KaV87B4mexkxXGNrZNxHms6v6LG-HD5yDg; expires=Sat, 05-Apr-2025 12:42:25 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: __Secure-ENID=22.SE=eatDo3DWtZLGtg7NIQxpeIiYzc1J3wAquEzzmfm4A_UNcCHhUjSY0Whzi-l01J9PLOUtm7dvC9GdX1L4AK3KBGVRIUsBePl1BDNB_tA_YKVUi8iv6EBdIms3bJ1cRB8NnDxt2aHJQX_ClZ6lZzxB7ppf7R_bWsHB3zHAsa5G3R4-K4XAk4g_InBRhcpvgfXDYdzCKmKQgOp0rmSV9BVMWzeY0xUTLJc0dqixwRHd; expires=Fri, 07-Nov-2025 05:00:43 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000



======== host.docker.internal status ========
PING host.docker.internal (172.17.0.1) 56(84) bytes of data.
64 bytes from host.docker.internal (172.17.0.1): icmp_seq=1 ttl=64 time=0.046 ms

--- host.docker.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.046/0.046/0.046/0.000 ms


======== Project ownership on host ========
drwxr-xr-x 4 inf inf 4096  7. Okt 14:41 ../tryddevproject-6873


======== Project ownership in container ========
drwxr-xr-x 4 inf inf 4096 Oct  7 12:41 //var/www/html


======== In-container filesystem ========
Filesystem     Type 1K-blocks      Used Available Use% Mounted on
/dev/nvme0n1p2 ext4 473344956 323948880 125278020  73% /var/www/html


======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
[325612, Main Thread] WARNING: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not(): 'glib warning', file /usr/src/debug/firefox/firefox-131.0/toolkit/xre/nsSigHandlers.cpp:187

(firefox:325612): Gtk-WARNING **: 14:42:29.603: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
Waiting for ddev launch to complete before deleting project


Cleanup: deleting test project tryddevproject-6873
 Container ddev-tryddevproject-6873-db  Stopped
 Container ddev-tryddevproject-6873-web  Stopped
 Container ddev-tryddevproject-6873-web  Stopped
 Container ddev-tryddevproject-6873-db  Stopped
 Container ddev-tryddevproject-6873-db  Removed
 Container ddev-tryddevproject-6873-web  Removed
 Network ddev-tryddevproject-6873_default  Removed
DDEV needs to run with administrative privileges.
This is normally to add unresolvable hostnames to the hosts file.
You may be required to enter your password for sudo or allow escalation.
DDEV is about to issue the command:
  sudo --preserve-env=HOME /usr/bin/ddev hostname --remove tryddevproject-6873.ddev.site 127.0.0.1

Volume tryddevproject-6873-mariadb for project tryddevproject-6873 was deleted
Volume tryddevproject-6873-postgres for project tryddevproject-6873 was deleted
Volume tryddevproject-6873_project_mutagen for project tryddevproject-6873 was deleted
Project tryddevproject-6873 was deleted. Your code and configuration are unchanged.

Please remove the files from this test with 'rm -r ../tryddevproject-6873'
```
</details>

### Expected Behavior

DDEV project starting without promoting for sudo access to /etc/hosts

### Actual Behavior

```
DDEV needs to run with administrative privileges.
This is normally to add unresolvable hostnames to the hosts file.
You may be required to enter your password for sudo or allow escalation.
DDEV is about to issue the command:
  sudo --preserve-env=HOME /usr/bin/ddev hostname --remove tryddevproject-6873.ddev.site 127.0.0.1
```

### Steps To Reproduce

Add a `AAAA` record for `<projectname>.ddev.site` pointing to `::1`

### Anything else?

To avoid unnecessary leaking and excessive upstream DNS lookups (because *.ddev.site has a TTL of 5m) I registered a wildcard for *.ddev.site in my local DNS resolver.

`127.0.0.1 A *.ddev.site`

This reduced the amount of ipv4 DNS resolution calls (eliminated all `A` record lookups).

But I still experienced `AAAA` lookup queries sent to upstream DNS server.

So I added that as well locally:

`::1 AAAA *.ddev.site`

Once there is a `AAAA` record in place, DDEV is unable to resolve the project's ddev hostname anymore:

Thus resulting in:

```
DDEV needs to run with administrative privileges.
This is normally to add unresolvable hostnames to the hosts file.
You may be required to enter your password for sudo or allow escalation.
DDEV is about to issue the command:
  sudo --preserve-env=HOME /usr/bin/ddev hostname --remove tryddevproject-6873.ddev.site 127.0.0.1
```

Which is clearly a false positive. It is apparently not capable to receive a `A` and a `AAAA` result as well.

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #6592

## How This PR Solves The Issue

Checks only for IPv4 in DNS lookup.

## Manual Testing Instructions

It should work when local DNS is configured to resolve IPv4 and IPv6 for the same host at the same time.

I tested it with custom TLD `*.test` (to be sure it doesn't collide with online `*.ddev.site`) and `dnsmasq`:

dnsmasq config:
for IPv4:
```
address=/*.test/127.0.0.1
```
for IPv6:
```
address=/*.test/::1
```

DDEV config:
```
ddev config --project-tld test
```

Cases:
1. Resolve IPv4 `*.test` added, resolve IPv6 `*.test` added - `ddev start` works
2. Resolve IPv4 `*.test` added, resolve IPv6 `*.test` not added - `ddev start` works
3. Resolve IPv4 `*.test` not added, resolve IPv6 `*.test` added - `ddev start` asks for sudo as expected
4. Resolve IPv4 `*.test` not added, resolve IPv6 `*.test` not added - `ddev start` asks for sudo as expected

### CODE REVIEW

**Comment by infabo** [comment]
I'll give it a try.

**Review by rfay — APPROVED** [review]
This seems like a reasonable change, although it would do some strange things if a variety of ipv4 addresses were returned. 

The logic could also have been added to GetLocalIPs() I think, or to IsLocalIP() perhaps, making it handle a slice instead of single. 

if @infabo finds it solves the problem, it should be OK.

File: pkg/ddevapp/hostname_mgt.go [hunk 1]
```diff
@@ -98,11 +98,19 @@ func (app *DdevApp) AddHostsEntriesIfNeeded() error {
 
 			// If we had successful lookup and the IP address looked up is local
 			// then we don't have to add it to the /etc/hosts.
-			if err == nil && len(hostIPs) > 0 && netutil.IsLocalIP(hostIPs[0]) {
```
Comment (infabo) [inline pkg/ddevapp/hostname_mgt.go:101]: why does the original code not already cover it? It looks like `hostIPs` is already an array and even when ipv6 adds another array item: at `hostIPs[0]` can only be a 50/50 chance: either it is `127.0.0.1` or it is `::1`. Is netutil.IsLocalIP not capable of recognizing `::1` as local IP?

**Comment by infabo** [comment]
Just downloaded this PRs ddev binary and for me it works. But I left a comment on the commit. I am wondering why it is even necessary to loop over the hostIPs. I dont know how to debug myself, have not set-up the ddev buildchain, I am interested in a dump of the `hostIPs` variable in case of ipv4/ipv6 DNS records are in place.

File: pkg/ddevapp/hostname_mgt.go (hunk 1 above)
Comment (stasadev) [reply pkg/ddevapp/hostname_mgt.go:101]: `netutil.IsLocalIP()` compares the IP with `dockerutil.GetDockerIP()`, which is `127.0.0.1` in this case, and if it's not equal, it compares it with `netutil.GetLocalIPs()` which gets local IPs, but excludes loopback addresses such as `127.0.0.1` and `::1`:

https://github.com/ddev/ddev/blob/cef6f2f7820283abf39e51c8475c2d51b9a33559/pkg/netutil/netutil.go#L47-L96

Theoretically it should work when the IP is resolvable either with IPv4 or IPv6.

I tried to remove this check for loopback `if v.IP.IsLoopback() {`, and tested it with a domain that can only be resolved with IPv6 (with `dnsmasq` help), `ddev start` didn't ask for sudo, but the site didn't open in the browser. I believe that it does not work for us.

**Comment by stasadev** [comment]
> The logic could also have been added to GetLocalIPs() I think, or to IsLocalIP() perhaps, making it handle a slice instead of single.

@rfay, this is done, and `GetLocalIPs()` returns only IPv4 addresses now.

And I applied this suggestion:

> I see this, https://stackoverflow.com/a/64950701/215713 - it implies that if we switch to net.LookupIP() we could force ipv4 lookup.

---

I use OpenSnitch to check my traffic, and with DDEV v1.23.4 it makes two lookups (but it doesn't say if it's IPv4 or IPv6, so that's why I didn't fully understood what was really going on here).

And with this PR, DDEV makes only one lookup for IPv4.

**Comment by infabo** [comment]
> And with this PR, DDEV makes only one lookup for IPv4.

I can confirm that. I can see no IPv6 (AAAA) queries anymore. There were a ton of `test.ddev.site`  AAAA-queries on 1.23.4. I see about 60k queries for test.ddev.site in a month. That's a huge number. These wont leave my network anymore now.

**Review by infabo — APPROVED** [review]

**Review by rfay — APPROVED** [review]
Impressive! Niche area, but great to have improvement here.
