### PR TITLE
fix: disable `.env` parsing for `docker-compose pull`, fixes #7671

### LINKED ISSUE #7671: ddev throws warnings because of dollar signs in my `.env` file
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://docs.ddev.com/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://docs.ddev.com/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

[ddev-debug-test.txt](https://github.com/user-attachments/files/22598001/ddev-debug-test.txt)****

### Expected Behavior

Having a multi-line environment variable that includes dollar signs enclosed in double quotes in my `.env` file should not throw any warnings.

### Actual Behavior

After updating from 1.24.7 to 1.24.8, I'm seeing an issue where ddev is throwing a bunch of warnings every time I start a project:

```
WARN[0000] The "S49DM" variable is not set. Defaulting to a blank string. 
WARN[0000] The "V56" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "XAQ" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QY7H" variable is not set. Defaulting to a blank string. 
… many more lines
```

All the mentioned variables are strings that appear in my `.env` file (in the project root, not inside `.ddev`) in a particular variable.

I use an environment variable for the license key for my Craft CMS projects. License keys are output as a multi-line string by default, so they look something like this in my `.env`:

```dotenv
CRAFT_LICENSE_KEY="KX9MQ8TD7$#R25YBL$N84FH//OPVXR^W#BBX%/QF^8M/Z+4K
9K4!NB4/S%O2WEYRXB$/XVYRPODDLE$*/Q$8M9ESN$7+YM$O29
7$KH=O!&+7N&*RFGQ%2B7Q28BPQRMSZXNZ$YPT^NRY5FK=$82B
Q8Z5$TY2H+R8PZV8%2&2#F^8TV9!2RRA8ZYZ24B*X*XS5PNB5B
Y*QFY72$K27ZBP=7RS$!BRY//TO&84SNX&!9QRM^8P8NXR2%X&"
```

Please note this is a randomly generated example and not a real license key for obvious reasons. The real license key includes all the alphanumeric strings displayed in the warnings above. All the warnings occur after a dollar sign (`$`) in the environment variable, and are terminated with any punctuation (non-alphanumeric character). Looks like it's trying to do variable expansion on my `.env` file?

Not sure why ddev is trying to do variable expansion on my `.env` file, but this only started happening in 1.24.8, so it must be related to a change since 1.24.7.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #7671

## How This PR Solves The Issue

- Adds `Env` to `dockerutils.ComposeCmdOpts`
- Adds `COMPOSE_DISABLE_ENV_FILE=1` for `docker-compose pull`, see https://github.com/compose-spec/compose-go/pull/510
- Skips `docker-compose pull` when there is nothing to pull (previously it ran every time)
- Removes unused `getInjectedEnv`
- Appends to `Env` instead of full overriding in different places.

## Manual Testing Instructions

```
echo "FOO=\$BAR" > .env
docker rmi ddev/ddev-utilities
ddev start
```

v1.24.8:
```
$ ddev start
Starting project... 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
[+] Pulling 3/3
 ✔ ddev-ddev-utilities-latest Pulled                                       4.1s 
   ✔ 43c4264eed91 Pull complete                                            1.5s 
   ✔ 134d3819e0e6 Pull complete                                            2.4s 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
Building project images....
Project images built in 2s.
...
```

This PR:

```
$ ddev start
Starting project... 
[+] Pulling 3/3
 ✔ ddev-ddev-utilities-latest Pulled                                       3.8s 
   ✔ 43c4264eed91 Pull complete                                            1.0s 
   ✔ 134d3819e0e6 Pull complete                                            2.1s 
Building project images....
```

### CODE REVIEW

**Comment by rfay** [comment]
Docs on COMPOSE_DISABLE_ENV_FILE: https://docs.docker.com/compose/how-tos/environment-variables/envvars/#compose_disable_env_file

File: cmd/ddev/cmd/addon-get.go [hunk 1]
```diff
@@ -310,31 +310,6 @@ func createManifestFile(app *ddevapp.DdevApp, addonName string, repository strin
 	return manifest, nil
 }
 
-// getInjectedEnv returns bash export string for env variables
-// that will be used in PreInstallActions and PostInstallActions
-func getInjectedEnv(envFile string, verbose bool) string {
```
Comment (rfay) [inline cmd/ddev/cmd/addon-get.go:315]: Thanks for removing stuff we aren't using.

I see getInjectedEnvForBash() still exists.

File: cmd/ddev/cmd/exec.go [hunk 2]
```diff
@@ -66,7 +66,7 @@ ddev exec --raw -- ls -lR`,
 			}
 			// opts.RawCmd is used instead of opts.Cmd
 			opts.RawCmd = args
-			opts.Env = env
+			opts.Env = append(os.Environ(), env...)
```
Comment (rfay) [inline cmd/ddev/cmd/exec.go]: Maybe I'm misunderstanding, but it looks to me like we're giving the host environment to a command being executed in the container, which could be problematic.

File: pkg/dockerutil/docker_compose.go [hunk 3]
```diff
@@ -78,6 +79,7 @@ func ComposeWithStreams(cmd *ComposeCmdOpts, stdin io.Reader, stdout io.Writer,
 	} else {
 		proc.Stdin = stdin
 	}
+	proc.Env = append(os.Environ(), cmd.Env...)
```
Comment (rfay) [inline pkg/dockerutil/docker_compose.go:82]: Same thing here, it looks like we're giving the host environment to the container, which probably isn't what we want?

File: pkg/dockerutil/docker_compose.go [hunk 4]
```diff
@@ -381,15 +384,22 @@ func PullImages(images []string, pullAlways bool) error {
 		util.Debug(`Pulling image for %s ("%s" service)`, image, service)
 	}
 
+	if len(composeYamlPull.Services) == 0 {
```
Comment (rfay) [inline pkg/dockerutil/docker_compose.go:387]: I like this improvement.

File: cmd/ddev/cmd/exec.go (hunk 2 above)
Comment (stasadev) [reply cmd/ddev/cmd/exec.go]: You're right, we don't want to change it here.

File: pkg/dockerutil/docker_compose.go (hunk 3 above)
Comment (stasadev) [reply pkg/dockerutil/docker_compose.go:82]: No, it's not inside the container.

If I replace it with:

```go
if cmd.Env != nil {
	proc.Env = cmd.Env
}
```

then `docker-compose pull` command is broken:

```
$ ddev debug download-images
Downloading images for php-2023 
[+] Pulling 0/6
 ⠋ ddev-ddev-dbserver-mysql-8.0-20250824_akibaat_buildx_arm_builder Pulling          0.0s 
 ⠋ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder Pulling                   0.0s 
 ⠋ ddev-ddev-traefik-router-20250824_akibaat_buildx_arm_builder Pulling              0.0s 
 ⠋ ddev-ddev-utilities-latest Pulling                                                0.0s 
 ⠋ ddev-ddev-xhgui-20250824_akibaat_buildx_arm_builder Pulling                       0.0s 
 ⠋ ddev-ddev-webserver-20250824_akibaat_buildx_arm_builder Pulling                   0.0s 
error getting credentials - err: exec: "docker-credential-secretservice": executable file not found in $PATH, out: ``
Failed to pull DDEV images: exit status 1 
```

**Review by rfay — APPROVED** [review]
Thanks!
