### PR TITLE
fix: use real path to global config location, fixes #6328

### LINKED ISSUE #6328: `ddev list` should show correct location of router configuration
### Expected Behavior

`ddev list` shows the router configuration location. It's not correct if XDG_CONFIG_HOME is set to something different, etc.

image

All we really need to do here is show the real directory.

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #6328

## How This PR Solves The Issue

Introduces a new function to replace `$HOME` with `~`.
Fixes the output.

## Manual Testing Instructions

```
export XDG_CONFIG_HOME=~/test
ddev list
cp ~/.ddev/project_list.yaml $XDG_CONFIG_HOME/ddev/project_list.yaml
ddev list # look at the router
ddev help config global | grep "~/test"
```

### CODE REVIEW

File: cmd/ddev/cmd/config-global.go [hunk 1]
```diff
@@ -297,21 +298,21 @@ func init() {
 	configGlobalCommand.Flags().BoolVarP(&instrumentationOptIn, "instrumentation-opt-in", "", false, "instrumentation-opt-in=true")
 	configGlobalCommand.Flags().Bool("router-bind-all-interfaces", false, "router-bind-all-interfaces=true")
 	configGlobalCommand.Flags().Int("internet-detection-timeout-ms", 3000, "Increase timeout when checking internet timeout, in milliseconds")
-	configGlobalCommand.Flags().Bool("disable-http2", false, "Optionally disable http2 in deprecated nginx-proxy ddev-router, 'ddev global --disable-http2' or `ddev global --disable-http2=false'")
-	configGlobalCommand.Flags().Bool("use-letsencrypt", false, "Enables experimental Let's Encrypt integration, 'ddev global --use-letsencrypt' or `ddev global --use-letsencrypt=false'")
-	configGlobalCommand.Flags().String("letsencrypt-email", "", "Email associated with Let's Encrypt, `ddev global --letsencrypt-email=me@example.com'")
+	configGlobalCommand.Flags().Bool("disable-http2", false, "Optionally disable http2 in deprecated nginx-proxy ddev-router, 'ddev config global --disable-http2' or `ddev config global --disable-http2=false'")
```
Comment (rfay) [inline cmd/ddev/cmd/config-global.go:301]: Oh nice catch(es)!

File: cmd/ddev/cmd/config-global.go [hunk 2]
```diff
@@ -297,21 +298,21 @@ func init() {
...
 	configGlobalCommand.Flags().Bool("fail-on-hook-fail", false, "If true, 'ddev start' will fail when a hook fails.")
 	configGlobalCommand.Flags().Bool("mutagen-enabled", false, "If true, web container will use Mutagen caching/asynchronous updates.")
 	_ = configGlobalCommand.Flags().MarkDeprecated("mutagen-enabled", fmt.Sprintf("please use --%s instead", configTypes.FlagPerformanceModeName))
 	configGlobalCommand.Flags().String(configTypes.FlagPerformanceModeName, configTypes.FlagPerformanceModeDefault, configTypes.FlagPerformanceModeDescription(configTypes.ConfigTypeGlobal))
 	configGlobalCommand.Flags().Bool(configTypes.FlagPerformanceModeResetName, true, configTypes.FlagPerformanceModeResetDescription(configTypes.ConfigTypeGlobal))
-	configGlobalCommand.Flags().String("table-style", "", "Table style for list and describe, see ~/.ddev/global_config.yaml for values")
+	configGlobalCommand.Flags().String("table-style", "", fmt.Sprintf("Table style for list and describe, see %s for values", fileutil.ShortHomeJoin(globalconfig.GetGlobalConfigPath())))
```
Comment (rfay) [inline cmd/ddev/cmd/config-global.go:311]: Excellent.

**Review by rfay — COMMENTED** [review]
Looks fantastic, thanks. Thanks for catching the other related things. I haven't manually tested yet.

File: cmd/ddev/cmd/config-global.go [hunk 3]
```diff
@@ -297,21 +298,21 @@ func init() {
...
 	configGlobalCommand.Flags().String("required-docker-compose-version", "", "Override default docker-compose version (used only in development testing)")
 	_ = configGlobalCommand.Flags().MarkHidden("required-docker-compose-version")
 	configGlobalCommand.Flags().String("project-tld", "", "Override default project tld")
-	configGlobalCommand.Flags().Bool("use-docker-compose-from-path", true, "If true, use docker-compose from path instead of private ~/.ddev/bin/docker-compose (used only in development testing)")
+	configGlobalCommand.Flags().Bool("use-docker-compose-from-path", true, fmt.Sprintf("If true, use docker-compose from path instead of private %s (used only in development testing)", fileutil.ShortHomeJoin(globalconfig.GetDDEVBinDir(), "docker-compose")))
```
Comment (rfay) [inline cmd/ddev/cmd/config-global.go:315]: This is fine and glad you caught it. But it's probably time for us to remove or hide this option. Pretty sure it's obsolete.

**Review by rfay — APPROVED** [review]
Manually tested, looks great. Thanks for fixing the broken missing `config global` stuff.

File: cmd/ddev/cmd/config-global.go (hunk 3 above)
Comment (stasadev) [reply cmd/ddev/cmd/config-global.go:315]: I remember there was a discussion about what to do with it, and it was hidden as a result.

I decided to update the description to be consistent even if users don't see it.
