### PR TITLE
fix: make project network external, fixes #5193

### LINKED ISSUE #5193: Multiple ambiguous docker networks created
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Running bash [-c /var/folders/1m/cv08gd016zs66h2p26szn0840000gn/T/test_ddev.sh]
======= Existing project config =========
These config files were loaded for project npg: [/Users/peter/projects/npg/npg_web/.ddev/config.yaml]
name: npg
type: php
docroot: htdocs
php_version: 8.1
webserver_type: apache-fpm
webimage: drud/ddev-webserver:v1.21.5
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
mariadb_version: 10.5
database: {mariadb 10.5}
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: ddev.site
use_dns_when_possible: true
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-9274 in ../tryddevproject-9274 =========
OS Information: Darwin MBP2021.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82
User information: uid=501(peter) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE
 DDEV version     v1.21.6
 architecture     arm64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.5
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.5
 docker           24.0.4
 docker-compose   v2.15.1
 docker-platform  docker
 mutagen          0.16.0
 os               darwin
 router           drud/ddev-router:v1.21.5
 web              drud/ddev-webserver:v1.21.5
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false
wsl2-no-windows-hosts-mgt=false

======= DOCKER info =========
docker location: lrwxr-xr-x  1 root  wheel  53 24 Jul 15:42 /usr/local/bin/docker -> /Applications/OrbStack.app/Contents/MacOS/xbin/docker
Docker Desktop Version: Docker Desktop for Mac 4.21.1 build 114176
docker version:
Client:
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:47:27 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server:
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       4ffc61430bbe6d3d405bdf357b766bf303ff3cc5
  Built:            Fri Jul 14 13:18:38 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:          1.1.8
  GitCommit:        82f18fe0e44a59034f3e1f45e475fa5636e539aa
 docker-init:
  Version:          0.19.0
  GitCommit:
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: docker
Using docker context: default (unix:///Users/peter/.orbstack/run/docker.sock)
docker-compose: v2.15.1
Using DOCKER_HOST=unix:///Users/peter/.orbstack/run/docker.sock
Docker version: 24.0.4
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 264.2G      5.5G    258.8G   2% /

Container ddev-npg-elasticsearch  Removed
Container ddev-npg-db  Removed
Container ddev-npg-web  Removed
Container ddev-npg-dba  Removed
Network ddev-npg_default  Error
failed to remove network ddev-npg_default: Error response from daemon: error while removing network: network ddev-npg_default id 03c36ecc4635f7146f09cb9181b3c8db1f98b3c0583e1039aed6e3df3fdc9649 has active endpoints
Failed to docker-compose down: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-npg docker-compose -f /Users/peter/projects/npg/npg_web/.ddev/.ddev-docker-compose-full.yaml down', action='[down]', err='exit status 1', stdout='', stderr='Container ddev-npg-web  Stopping
Container ddev-npg-web  Stopping
Container ddev-npg-dba  Stopping
Container ddev-npg-dba  Stopping
Container ddev-npg-db  Stopping
Container ddev-npg-db  Stopping
Container ddev-npg-elasticsearch  Stopping
Container ddev-npg-elasticsearch  Stopping
Container ddev-npg-elasticsearch  Stopped
Container ddev-npg-elasticsearch  Removing
Container ddev-npg-elasticsearch  Removed
Container ddev-npg-db  Stopped
Container ddev-npg-db  Removing
Container ddev-npg-db  Removed
Container ddev-npg-web  Stopped
Container ddev-npg-web  Removing
Container ddev-npg-web  Removed
Container ddev-npg-dba  Stopped
Container ddev-npg-dba  Removing
Container ddev-npg-dba  Removed
Network ddev-npg_default  Removing
Network ddev-npg_default  Error
failed to remove network ddev-npg_default: Error response from daemon: error while removing network: network ddev-npg_default id 03c36ecc4635f7146f09cb9181b3c8db1f98b3c0583e1039aed6e3df3fdc9649 has active endpoints'
Removing container: ddev-npg-web-run-db17b45e5f8c
Removing container: ddev-npg-web-run-501f02f3f63d
Project npg has been stopped.
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers:
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Creating a new ddev project config in the current directory (/Users/peter/projects/npg/tryddevproject-9274)
Once completed, your configuration will be written to /Users/peter/projects/npg/tryddevproject-9274/.ddev/config.yaml

Configuring unrecognized codebase as project type 'php' at /Users/peter/projects/npg/tryddevproject-9274/web
Configuration complete. You may now run 'ddev start'.
Network ddev_default created
Starting tryddevproject-9274...
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
v1.21.5: Pulling from drud/ddev-dbserver-mariadb-10.4
970e18d4d6e7: Already exists
8e1696491692: Already exists
fdaddccffd64: Already exists
3916deba3048: Already exists
1cd2db5c00a0: Pull complete
763136347ea3: Pull complete
9fbbbbe6aadb: Pull complete
3d5e4be2696f: Pull complete
e4554e9c224b: Pull complete
4f4fb700ef54: Pull complete
1dc40240383f: Pull complete
e874df046cc2: Pull complete
86140e227aaa: Pull complete
22ff3eb0b980: Pull complete
9e61d5ae7fe0: Pull complete
a3c19fbcb613: Pull complete
3c5741040871: Pull complete
1ffc539f9ccb: Pull complete
ca0cb63dbcb0: Pull complete
eada3ebe2860: Pull complete
149b49488bc6: Pull complete
8d2045d8a17d: Pull complete
c891587387a1: Pull complete
0be54c4d4ee7: Pull complete
Digest: sha256:5c09a3302f5d77780e7cf2987762aefe2c0e0bcb603cb9624d1cc8624a9c6f30
Status: Downloaded newer image for drud/ddev-dbserver-mariadb-10.4:v1.21.5
docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.5
Network ddev-tryddevproject-9274_default  Created
Container ddev-tryddevproject-9274-web  Started
Container ddev-tryddevproject-9274-db  Started
Container ddev-tryddevproject-9274-dba  Started
Container ddev-router  Started
Successfully started tryddevproject-9274
Project can be reached at https://tryddevproject-9274.ddev.site https://127.0.0.1:32783
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 25 Jul 2023 08:33:01 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-9274.ddev.site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Tue, 25 Jul 2023 08:33:01 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-9274.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-9274'
======== Project ownership on host:
drwxr-xr-x  4 peter  staff  128 25 Jul 09:32 ../tryddevproject-9274
======== Project ownership in container:
drwxr-xr-x 4 peter dialout 128 Jul 25 08:32 /var/www/html
======== In-container filesystem:
Filesystem     Type     1K-blocks      Used Available Use% Mounted on
mac            virtiofs 971350180 688718612 282631568  71% /var/www/html
======== curl again of tryddevproject-9274 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-9274'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-9274'
```
</details>         

### Expected Behavior

I have a PHP site running within ddev, and on my host machine I run vite with a default configuration (so bound to localhost:5173).

I'd expect them to run alongside each other, but running Vite's dev server with HMR seems to kill DDEV.

### Actual Behavior

502: Unresponsive/broken ddev back-end site.
This is the ddev-router container: The back-end webserver at the URL you specified is not responding. You may want to use "ddev restart" to restart the site.

The network hangs around and if I do a `ddev stop` 

### Steps To Reproduce

So, this doesn't reproduce 100% of the time but over the last couple of days this is the closest I can get to a reproducer.

When the HTTP 502 happens I try the following:

```
> ddev stop
Container ddev-npg-db  Removed
Container ddev-npg-elasticsearch  Removed
Container ddev-npg-web  Removed
Container ddev-npg-dba  Removed
Network ddev-npg_default  Error
failed to remove network ddev-npg_default: Error response from daemon: error while removing network: network ddev-npg_default id 03c36ecc4635f7146f09cb9181b3c8db1f98b3c0583e1039aed6e3df3fdc9649 has active endpoints
Failed to docker-compose down: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-npg docker-compose -f /Users/peter/projects/npg/npg_web/.ddev/.ddev-docker-compose-full.yaml down', action='[down]', err='exit status 1', stdout='', stderr='Container ddev-npg-web  Stopping
Container ddev-npg-web  Stopping
Container ddev-npg-db  Stopping
Container ddev-npg-db  Stopping
Container ddev-npg-elasticsearch  Stopping
Container ddev-npg-elasticsearch  Stopping
Container ddev-npg-dba  Stopping
Container ddev-npg-dba  Stopping
Container ddev-npg-db  Stopped
Container ddev-npg-db  Removing
Container ddev-npg-db  Removed
Container ddev-npg-elasticsearch  Stopped
Container ddev-npg-elasticsearch  Removing
Container ddev-npg-elasticsearch  Removed
Container ddev-npg-web  Stopped
Container ddev-npg-web  Removing
Container ddev-npg-web  Removed
Container ddev-npg-dba  Stopped
Container ddev-npg-dba  Removing
Container ddev-npg-dba  Removed
Network ddev-npg_default  Removing
Network ddev-npg_default  Error
failed to remove network ddev-npg_default: Error response from daemon: error while removing network: network ddev-npg_default id 03c36ecc4635f7146f09cb9181b3c8db1f98b3c0583e1039aed6e3df3fdc9649 has active endpoints'
Removing container: ddev-npg-web-run-cead698ab009
Project npg has been stopped.
```

Trying to restart leads to:
```
> ddev start
Starting npg...
Using custom mysql configuration: [/Users/peter/projects/npg/npg_web/.ddev/mysql/my-npg.cnf]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
Container ddev-npg-dba  Started
Container ddev-npg-web  Started
Container ddev-npg-db  Started
Container ddev-npg-elasticsearch  Started
Container ddev-router  Started
Failed to start npg: container(s) failed to become healthy before their configured timeout or in 120 seconds. This may be just a problem with the healthcheck and not a functional problem. (health check timed out: labels map[com.ddev.site-name:npg] timed out without becoming healthy, status=, detail= ddev-npg-web-run-bd3dd0de6a9a:starting - more info with `docker inspect --format "{{json .State.Health }}" ddev-npg-web-run-bd3dd0de6a9a` )
```

```
> docker network ls
NETWORK ID     NAME               DRIVER    SCOPE
de785f219008   bridge             bridge    local
03c36ecc4635   ddev-npg_default   bridge    local
0c8e9b9f2705   ddev_default       bridge    local
d97be534fb66   host               host      local
b159031a67f9   none               null      local

> docker network rm ddev-npg_default
Error response from daemon: error while removing network: network ddev-npg_default id 03c36ecc4635f7146f09cb9181b3c8db1f98b3c0583e1039aed6e3df3fdc9649 has active endpoints

> ddev poweroff
Container ddev-npg-dba  Removed
Container ddev-npg-db  Removed
Container ddev-npg-elasticsearch  Removed
Container ddev-npg-web  Removed
Network ddev-npg_default  Error
failed to remove network ddev-npg_default: Error response from daemon: error while removing network: network ddev-npg_default id 03c36ecc4635f7146f09cb9181b3c8db1f98b3c0583e1039aed6e3df3fdc9649 has active endpoints
Failed to docker-compose down: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-npg docker-compose -f /Users/peter/projects/npg/npg_web/.ddev/.ddev-docker-compose-full.yaml down', action='[down]', err='exit status 1', stdout='', stderr='Container ddev-npg-web  Stopping
Container ddev-npg-elasticsearch  Stopping
Container ddev-npg-web  Stopping
Container ddev-npg-elasticsearch  Stopping
Container ddev-npg-db  Stopping
Container ddev-npg-db  Stopping
Container ddev-npg-dba  Stopping
Container ddev-npg-dba  Stopping
Container ddev-npg-web  Stopped
Container ddev-npg-web  Removing
Container ddev-npg-dba  Stopped
Container ddev-npg-dba  Removing
Container ddev-npg-elasticsearch  Stopped
Container ddev-npg-elasticsearch  Removing
Container ddev-npg-db  Stopped
Container ddev-npg-db  Removing
Container ddev-npg-dba  Removed
Container ddev-npg-db  Removed
Container ddev-npg-elasticsearch  Removed
Container ddev-npg-web  Removed
Network ddev-npg_default  Removing
Network ddev-npg_default  Error
failed to remove network ddev-npg_default: Error response from daemon: error while removing network: network ddev-npg_default id 03c36ecc4635f7146f09cb9181b3c8db1f98b3c0583e1039aed6e3df3fdc9649 has active endpoints'
Removing container: ddev-npg-web-run-bd3dd0de6a9a
Project npg has been stopped.
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.

> docker network ls
NETWORK ID     NAME               DRIVER    SCOPE
de785f219008   bridge             bridge    local
03c36ecc4635   ddev-npg_default   bridge    local
d97be534fb66   host               host      local
b159031a67f9   none               null      local

> docker network rm ddev-npg_default
ddev-npg_default
```

Once I run that I can now run `ddev start` and it works.

Now I run `npm run dev` again in my subfolder:
```
  VITE v4.4.7  ready in 149 ms

  ➜  Local:   https://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

Reload my PHP page a couple of times, and ddev goes back to returning the HTTP 502.

### Anything else?

I thought it might be a bug in Docker, so I installed OrbStack with this DDEV setup the only set of containers/networks in it. The problem happens just the same, which is why I'm posting here as it could be to do with DDEV instead.

vite.config.ts:
```
import { defineConfig } from 'vite'
// @ts-ignore
import fs from 'fs'
// @ts-ignore
import path from 'path'

export default defineConfig({
    server: {
        https: {
            key: fs.readFileSync(path.resolve(__dirname, 'localhost-key.pem')),
            cert: fs.readFileSync(path.resolve(__dirname, 'localhost.pem'))
        }
    },
    plugins: [
    ],
    css: {
        devSourcemap: true
    },
    build: {
        manifest: true,
        rollupOptions: {
            input: {
                main: './main.js',
            }
        },
        outDir: '../htdocs/assets/dist'
    }
})
```

And the minimal parts of my package.json:
```
{
  "dependencies": {
  },
  "scripts": {
    "dev": "rm -rf dist/* && vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^4.4.7"
  }
}
```

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

* #5193 

Sometimes when you start a project, multiple project networks are created (e.g. `ddev-npg_default`) which prevents the project from starting.

```
Error response from daemon: network ddev-npg_default is ambiguous (16 matches found on name)
```

It doesn't happen all the time, but it's really annoying.

## How This PR Solves The Issue

The idea is that if the project's docker network is created before doing the usual stuff, it can prevent the problem from occurring.

Let's make the project's docker network external (just like the `ddev_default` global network).

## Manual Testing Instructions

This PR must *not* break existing features to be considered something valuable to merge.

There is no reliable way to test this, because the issue is related to `docker-compose` (not DDEV itself), and it occurs randomly.

## Related Issue Link(s)

- https://github.com/ddev/ddev/issues/5193

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5305"></a>

### CODE REVIEW

File: pkg/dockerutil/dockerutils.go [hunk 1]
```diff
@@ -550,7 +560,7 @@ func ComposeCmd(composeFiles []string, action ...string) (string, string, error)
 	// Container (or Volume) ... Creating or Created or Stopping or Starting or Removing
 	// Container Stopped or Created
 	// No resource found to remove (when doing a stop and no project exists)
-	ignoreRegex := "(^ *(Network|Container|Volume) .* (Creat|Start|Stopp|Remov)ing$|^Container .*(Stopp|Creat)(ed|ing)$|Warning: No resource found to remove$|Pulling fs layer|Waiting|Downloading|Extracting|Verifying Checksum|Download complete|Pull complete)"
+	ignoreRegex := "(^ *(Network|Container|Volume) .* (Creat|Start|Stopp|Remov)ing$|^Container .*(Stopp|Creat)(ed|ing)$|Warning: No resource found to remove|Pulling fs layer|Waiting|Downloading|Extracting|Verifying Checksum|Download complete|Pull complete)"
```
Comment (stasadev) [inline pkg/dockerutil/dockerutils.go:563]: I removed `$` from `Warning: No resource found to remove$` because there was extra output from `docker-compose` with this command:

```
$ project=test-5305 && mkdir $project && cd $project && ddev config --auto --omit-containers=db && ddev start && ddev stop && ddev restart && ddev delete --omit-snapshot --yes && cd .. && rm -rf $project
...
Starting test-5305...
...
Project test-5305 has been stopped. 
Restarting project test-5305... 
Warning: No resource found to remove for project "ddev-test-5305".
...
```

**Comment by rfay** [comment]
Rebased to hopefully fix colima problems.

**Comment by rfay** [comment]
Rebased again hoping for colima success.

**Comment by jonaseberle** [comment]
It seems we are working around a docker bug here if the implicit project networks get duplicated with the same name (which should not be possible!).

I haven't found regressions so far.

But maybe help me understand: Where do we create that external project network now that we are not letting docker-compose doing that? It must be in our code but I have not found it.

**Comment by rfay** [comment]
I haven't looked closely at this, but another way to handle this, instead of using external network, is to just remove any dangling network before running docker-compose up. That would leave the network responsibility in the docker-compose yaml and be less intrusive.

**Comment by stasadev** [comment]
>Where do we create that external project network now that we are not letting docker-compose doing that?

I put the creation of the project's network inside `EnsureDdevNetwork()` - where ddev_default is created.

>another way to handle this, instead of using external network, is to just remove any dangling network before running docker-compose up

The problem is that there is no dangling network, the duplicate is created when `docker-compose up` is executed.

**Comment by stasadev** [comment]
I have been using this PR for a week and have not noticed any problems.

During this time, I did not see duplicate networks.

Again, this is a workaround, but it would be nice to have it here.

**Review by rfay — APPROVED** [review]
I manually tested this and looked at networks before and after and it seemed right to me. 

I added just a single commit to add links to the PRs and issues so this won't be incomprehensible in the future when somebody stumbles across it in the code.

@stasadev would you mind testing this version for another week, as it now has an updated docker-compose in it?

**Comment by stasadev** [comment]
Sure, I will use for another week.

Meanwhile, yesterday I went to the stable v1.22.1 to confirm that I have this problem with networks - yes, I still see duplicate networks.

**Comment by rfay** [comment]
I sure wish we understood why this can happen to you so often, but is not often-reported.

**Comment by rfay** [comment]
I'm sure you're already doing this, but when testing make sure to use the "native" bundled version of docker-compose.

**Comment by stasadev** [comment]
>I sure wish we understood why this can happen to you so often, but is not often-reported.

Added a new comment [here](https://github.com/ddev/ddev/issues/5193#issuecomment-1709537042), hard to tell, but the problem may come from the Docker Engine.

>I'm sure you're already doing this, but when testing make sure to use the "native" bundled version of docker-compose.

Yes, I use the bundled version.

**Comment by rfay** [comment]
We'll do a point release this week, so if you think this is going to be OK we'll pull when you're ready again. Or we can wait for the next point release. 

We could also wait for https://github.com/moby/moby/pull/46251 but that one won't roll out to all environments for quite some time, even though it will show up sooner on Linux and Docker Desktop.

**Comment by stasadev** [comment]
I've been testing it for a few days and haven't noticed any issues with docker-compose v2.21.0.

But let's postpone this PR for another point release.

I see activity in moby/moby#46251 and want to check it out, hopefully it will be merged soon (I'll build Docker from master).

**Comment by rfay** [comment]
Thanks! I'm going to move this back to draft then, and we'll rebase as time goes on.

**Comment by rfay** [comment]
I did find one minor piece of fallout with this, but it has to do with going back to regular version after testing this one:

`failed to start d10: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-d10 docker-compose -f /Users/rfay/workspace/d10/.ddev/.ddev-docker-compose-full.yaml up -d', action='[up -d]', err='exit status 1', stdout='', stderr='time="2023-09-11T11:25:04-06:00" level=warning msg="a network with name ddev-d10_default exists but was not created by compose.\nSet `external: true` to use an existing network"
network ddev-d10_default was found but has incorrect label com.docker.compose.network set to ""'`

People who understand what's going on know to delete the network, but it would be baffling for others. Not sure if or what we could do or if we should do anything.

**Comment by stasadev** [comment]
Ah yes, that could be a problem. DDEV offers to do `ddev poweroff` only after the upgrade.

But I can't guarantee that project will be stopped *before* switching the version.

This requires adding extra code to check and remove the external network at `ddev start`.

But again, that won't prevent this error from occurring if someone decides to downgrade.

**Comment by rfay** [comment]
Yeah, let's just think about it. One thing we could do now is
* Always tag networks like we already do on containers and should start doing on images
* `ddev poweroff` can delete all tagged networks.

**Comment by stasadev** [comment]
Yes, looks like part of a larger task with Docker resources management.
So many things to control, but it would definitely improve the user experience.

**Comment by stasadev** [comment]
>I see activity in moby/moby#46251 and want to check it out, hopefully it will be merged soon (I'll build Docker from master).

My update here:

I'm not testing anything here yet, despite it being merged into master.

The PR has not yet been merged into the https://github.com/moby/moby/commits/24.0 branch.

I tried a build from master, but `ddev start` is very slow for me there. I believe the Arch Linux build is not optimized for it (the master branch is something like what we'll see in Docker 25).

**Comment by rfay** [comment]
Rebased.

**Comment by rfay** [comment]
Rebased

**Comment by stasadev** [comment]
Testing PR artifact.

P.S. Oops, I clicked Update branch, and it made merge instead of rebase, I will remember to choose a correct option here:
img

**Comment by rfay** [comment]
Thanks, it doesn't usually matter because we squash in the end, but my preference is always rebase because of the good git history.

**Comment by rfay** [comment]
Rebased

**Comment by stasadev** [comment]
I have manually updated the artifact links to the latest ones.

Tested it again.

This PR is ready for review.

**Review by rfay — APPROVED** [review]
I looked it through and took it for a manual spin again, watching the network creation. The only problem I had, as you had predicted, was returning to an earlier version, where I got

`time="2023-10-10T19:01:03+02:00" level=warning msg="a network with name ddev-junk_default exists but was not created by compose.\nSet `external: true` to use an existing network"
network ddev-junk_default was found but has incorrect label com.docker.compose.network set to ""
Failed to restart junk: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-junk docker-compose -f /Users/rfay/workspace/junk/.ddev/.ddev-docker-compose-full.yaml up -d', action='[]', err='exit status 1', stdout='', stderr='time="2023-10-10T19:01:03+02:00" level=warning msg="a network with name ddev-junk_default exists but was not created by compose.\nSet `external: true` to use an existing network"`

I don't think there's a way to solve that. But I'll bet we get issues about it.

**Comment by jonaseberle** [comment]
I'll make this PR my daily driver for a while.

**Comment by jonaseberle** [comment]
For what it's worth https://github.com/jonaseberle/ddev/commit/ccda749034196cabb28664b19f4a6d3e0d3fe305 would label the DDEV networks. Maybe that gets us further?

**Comment by rfay** [comment]
That labeling here would allow us to give people a one-liner `docker network delete` command if they do happen to go backward.

**Comment by rfay** [comment]
We may want to take this in two steps. In the next point release add a little code that removes all networks by label, using @jonaseberle 's technique, in addition to removing all networks it knows about. So that would go into v1.22.4. Then in v1.22.5 we could add the external networks, and people could at least go back down to v1.22.4 without trouble.

**Comment by stasadev** [comment]
I was going to do the [same](https://github.com/ddev/ddev/pull/5305#issuecomment-1755916733) thing with labels, and on a larger scale (with images and other docker entities).

But I haven't had time to do it yet. @jonaseberle we think alike here :smile:

**Review by rfay — CHANGES_REQUESTED** [review]
So sad to say this after as long as you've been working on this, but it will introduce a situation where if we have any kind of problem with the release it's introduced in, we won't easily be able to tell people "just go back to previous" without quite a bit of pain. 

So let's introduce a simple all-network cleanup before we introduce this, and clean up all known networks and all "ddev" tagged networks. So with that little item added in the upcoming release, we can be confident that we can offer people backward compatibility. Then we can get this into the next one.

This also gives @jonaseberle, a total expert on networks, time to use these artifacts, which is also a win.

**Comment by rfay** [comment]
Put this one back to draft mode again, just do I don't get confused along the way :)

**Comment by stasadev** [comment]
I will rebase and resolve conflicts here later

- https://github.com/ddev/ddev/pull/5436

**Comment by stasadev** [comment]
Another rebase after v1.22.4 release.

I am going to test it after tests and I believe we can finally merge it.

Thanks to @rfay for the careful planning and @jonaseberle for the testing and ideas on how to make it better.

**Review by rfay — APPROVED** [review]
Given the amount of effort on this one and good checking I think it should be good to go now, can be pulled when you think it's good.

**Comment by rfay** [comment]
I also did a prerelease that can be used for testing this, https://github.com/ddev/ddev/releases/tag/v1.22.5-alpha1
