### PR TITLE
fix: replace broken http and https port lookup, fixes #7246

### LINKED ISSUE #7246: ddev share uses web_extra_exposed_ports instead of main http port
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```


======== Output file will be in /tmp/ddev-debug-test.txt ========


======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev
/bin/ddev

These config files were loaded for project fvn-li: [/home/akiba/Projects/fvn.li/.ddev/config.yaml /home/akiba/Projects/fvn.li/.ddev/config.laravel-workers.yaml]
name: fvn-li
type: laravel
docroot: public
php_version: 8.4
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.24.4
xdebug_enabled: true
database: {postgres 17}
webimage_extra_packages: [ffmpeg libgl1]
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 22
default_container_timeout: 120
web_extra_exposed_ports: [{vite 5173 5172 5173}]
web_extra_daemons: [{queue-1 while true; do /usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3 --queue=default,android; sleep 1; done /var/www/html}]
ddev_version_constraint: >=v1.23.0


======== existing project customizations ========
.ddev/docker-compose.renpy-sdk.yaml
.ddev/php/xdebug_trigger.ini
.ddev/nginx/redirect.conf
.ddev/web-build/Dockerfile
.ddev/.env
.ddev/.env.redis
Customizations in .ddev/nginx:
total 4
-rw-r--r-- 1 akiba akiba 84 Apr 28 18:30 redirect.conf


======== installed DDEV add-ons ========
┌────────────────────┬─────────┬────────────────────────────┬───────────────────────────┐
│ ADD-ON             │ VERSION │ REPOSITORY                 │ DATE INSTALLED            │
├────────────────────┼─────────┼────────────────────────────┼───────────────────────────┤
│ ddev-laravel-queue │ 1.0.0   │ tyler36/ddev-laravel-queue │ 2025-04-28T01:25:39+02:00 │
├────────────────────┼─────────┼────────────────────────────┼───────────────────────────┤
│ redis              │ v1.2.3  │ ddev/ddev-redis            │ 2025-02-17T00:01:57+01:00 │
└────────────────────┴─────────┴────────────────────────────┴───────────────────────────┘



======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /home/akiba/Projects/fvn.li

.ddev/mutagen/mutagen.yml not found


======== Creating dummy project named tryddevproject-29210 in ../tryddevproject-29210 ========
Creating a new DDEV project config in the current directory (/home/akiba/Projects/tryddevproject-29210)
Once completed, your configuration will be written to /home/akiba/Projects/tryddevproject-29210/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-29210' with docroot 'web' at '/home/akiba/Projects/tryddevproject-29210/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.


======== OS Information ========
Linux Mainframe 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


======== User information ========
uid=1000(akiba) gid=1000(akiba) groups=1000(akiba),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),100(users),107(netdev),1001(docker)


======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.24.4                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.24.4 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.24.4              
 docker           28.1.1                                   
 docker-api       1.49                                     
 docker-compose   v2.34.0                                  
 docker-platform  docker-desktop                           
 global-ddev-dir  /home/akiba/.ddev                        
 go-version       go1.23.7                                 
 mutagen          0.18.1                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.24.4         
 web              ddev/ddev-webserver:v1.24.4              
 xhgui-image      ddev/ddev-xhgui:v1.24.4                  



======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''



======== DDEV global info ========
developer-mode=false
fail-on-hook-fail=false
instrumentation-opt-in=false
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.24.4
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/mnt/c/Users/Akiba/AppData/Local/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=none
project-tld=ddev.site
required-docker-compose-version=v2.34.0
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=
xhgui-http-port=
xhgui-https-port=
xhprof-mode=


======== DOCKER provider info ========
docker client location: lrwxrwxrwx 1 root root 48 May  1 11:12 /usr/bin/docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker

docker client alternate locations:
/usr/bin/docker
/bin/docker
/Docker/host/bin/docker

Docker provider: docker-desktop


======== docker version ========
Client:
 Version:           28.1.1
 API version:       1.49
 Go version:        go1.23.8
 Git commit:        4eba377
 Built:             Fri Apr 18 09:51:06 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop 4.0.0 ()
 Engine:
  Version:          28.1.1
  API version:      1.49 (minimum version 1.24)
  Go version:       go1.23.8
  Git commit:       01f442b
  Built:            Fri Apr 18 09:52:57 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


======== docker context ls ========
NAME            DESCRIPTION                               DOCKER ENDPOINT                             ERROR
default *       Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                 
desktop-linux   Docker Desktop                            npipe:////./pipe/dockerDesktopLinuxEngine   

DOCKER_HOST=unix:///var/run/docker.sock
DOCKER_DEFAULT_PLATFORM=notset


======== ddev debug dockercheck ========
Docker platform: docker-desktop
Using Docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.34.0
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 28.1.1
Docker API version: 1.49
Able to run simple container that mounts a volume.
Able to use internet inside container.

Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                1006.9G      7.0G    948.6G   1% /


======== Existing docker containers ========
CONTAINER ID   IMAGE                               COMMAND     CREATED        STATUS    PORTS     NAMES
d2792d9ac024   phpstorm_helpers:PS-251.23774.436   "/bin/sh"   15 hours ago   Created             phpstorm_helpers_PS-251.23774.436


======== docker system df ========
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          12        1         3.878GB   3.875GB (99%)
Containers      1         0         4.096kB   4.096kB (100%)
Local Volumes   9         1         67.8MB    67.64MB (99%)
Build Cache     52        0         57.34kB   57.34kB

  Tips:
  1. Periodically check your Docker filesystem usage with 'docker system df'
  2. Use 'docker builder prune' to remove unused Docker build cache (it doesn't remove your data)
  3. To remove all containers and images (it doesn't remove your data):
    ```
    ddev poweroff
    docker rm -f $(docker ps -aq) || true
    docker rmi -f $(docker images -q)
    ```
    (DDEV images will be downloaded again on 'ddev start')


======== mkcert information ========
/usr/bin/mkcert
/bin/mkcert
CAROOT=/mnt/c/Users/Akiba/AppData/Local/mkcert WSLENV=CAROOT/up: JAVA_HOME=
/mnt/c/Users/Akiba/AppData/Local/mkcert
total 8
-r-xr-xr-x 1 akiba akiba 2484 Feb  6  2024 rootCA-key.pem
-rwxrwxrwx 1 akiba akiba 1789 Feb  6  2024 rootCA.pem


======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.012 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.012/0.012/0.012/0.000 ms


======== curl information ========
/home/akiba/anaconda3/bin/curl
/usr/bin/curl
/bin/curl


======== ddev debug rebuild ========
Rebuilding project images...
Rebuilding project tryddevproject-29210 with `/home/akiba/.ddev/bin/docker-compose -f /home/akiba/Projects/tryddevproject-29210/.ddev/.ddev-docker-compose-full.yaml --progress plain build web --no-cache`
#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.54kB done
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/ddev/ddev-webserver:v1.24.4
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web  1/10] FROM docker.io/ddev/ddev-webserver:v1.24.4@sha256:6f23918a2b5d42370e99e0b90812302572953636b2e0134e4347c1113b5cd9e2
#4 resolve docker.io/ddev/ddev-webserver:v1.24.4@sha256:6f23918a2b5d42370e99e0b90812302572953636b2e0134e4347c1113b5cd9e2
#4 ...

#5 [web auth] ddev/ddev-webserver:pull token for registry-1.docker.io
#5 DONE 0.0s

#4 [web  1/10] FROM docker.io/ddev/ddev-webserver:v1.24.4@sha256:6f23918a2b5d42370e99e0b90812302572953636b2e0134e4347c1113b5cd9e2
#4 resolve docker.io/ddev/ddev-webserver:v1.24.4@sha256:6f23918a2b5d42370e99e0b90812302572953636b2e0134e4347c1113b5cd9e2 1.1s done
#4 DONE 1.1s

#4 [web  1/10] FROM docker.io/ddev/ddev-webserver:v1.24.4@sha256:6f23918a2b5d42370e99e0b90812302572953636b2e0134e4347c1113b5cd9e2
#4 CACHED

#6 [web  2/10] RUN getent group tty || groupadd tty
#6 0.283 tty:x:5:
#6 DONE 0.3s

#7 [web  3/10] RUN (groupadd --gid 1000 "akiba" || groupadd "akiba" || true) && (useradd -G tty -l -m -s "/bin/bash" --gid "akiba" --comment '' --uid 1000 "akiba" || useradd -G tty -l -m -s "/bin/bash" --gid "akiba" --comment '' "akiba" || useradd  -G tty -l -m -s "/bin/bash" --gid "1000" --comment '' "akiba" || useradd -G tty -l -m -s "/bin/bash" --comment '' akiba )
#7 DONE 0.6s

#8 [web  4/10] RUN mkdir -p /home/akiba && chown akiba /home/akiba && chmod 600 /home/akiba/.pgpass
#8 DONE 0.5s

#9 [web  5/10] RUN START_SCRIPT_TIMEOUT=30 mariadb-client-install.sh || true
#9 0.462 This script is not intended to run with mariadb:10.11
#9 DONE 0.5s

#10 [web  6/10] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || log-stderr.sh composer self-update --2 || true
#10 0.593 Storing "stable" as default update channel for the next self-update run.
#10 0.698 Upgrading to version 2.8.8 (stable channel).
#10 0.726    
#10 0.925 Use composer self-update --rollback to return to version 2.8.6
#10 1.121 You are already using the latest available Composer version 2.8.8 (2.x channel).
#10 DONE 1.2s

#11 [web  7/10] RUN timeout 30 apt-get update || true
#11 0.612 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#11 0.631 Get:2 https://packages.sury.org/php bookworm InRelease [7551 B]
#11 0.632 Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#11 0.636 Get:4 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [129 kB]
#11 0.647 Get:5 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#11 0.653 Get:7 http://nginx.org/packages/debian bookworm InRelease [2857 B]
#11 0.694 Get:8 http://deb.debian.org/debian bookworm/main amd64 Packages [8792 kB]
#11 0.738 Get:9 https://packages.sury.org/php bookworm/main amd64 Packages [257 kB]
#11 0.875 Get:10 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm InRelease [3675 B]
#11 0.878 Get:11 http://nginx.org/packages/debian bookworm/nginx amd64 Packages [20.7 kB]
#11 0.920 Get:12 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 Packages [360 kB]
#11 1.013 Get:6 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease [4628 B]
#11 1.036 Get:13 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm InRelease [3681 B]
#11 1.205 Get:14 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [4422 B]
#11 1.220 Get:15 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [512 B]
#11 1.221 Get:16 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [257 kB]
#11 1.381 Get:17 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm/main amd64 Packages [4540 B]
#11 1.495 Get:18 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm/main amd64 Packages [3389 B]
#11 1.641 Get:20 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main amd64 Packages [8556 B]
#11 1.750 Get:21 http://packages.blackfire.io/debian any InRelease [29.2 kB]
#11 1.825 Get:19 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main arm64 Packages [35.2 kB]
#11 2.276 Get:22 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main amd64 Packages [42.1 kB]
#11 2.942 Get:23 http://packages.blackfire.io/debian any/main amd64 Packages [31.8 kB]
#11 2.961 Fetched 10.3 MB in 2s (4262 kB/s)
#11 2.961 Reading package lists...
#11 DONE 3.4s

#12 [web  8/10] RUN curl -I https://www.google.com
#12 0.400   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#12 0.400                                  Dload  Upload   Total   Spent    Left  Speed
#12 0.400 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#12 0.496 HTTP/2 200 
#12 0.496 content-type: text/html; charset=ISO-8859-1
#12 0.496 content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-aS689hnAOygIcYladDn3vA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
#12 0.496 accept-ch: Sec-CH-Prefers-Color-Scheme
#12 0.496 p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
#12 0.496 date: Thu, 01 May 2025 11:37:34 GMT
#12 0.496 server: gws
#12 0.496 x-xss-protection: 0
#12 0.496 x-frame-options: SAMEORIGIN
#12 0.496 expires: Thu, 01 May 2025 11:37:34 GMT
#12 0.496 cache-control: private
#12 0.496 set-cookie: AEC=AVcja2c7SD6-bm6wEKAiTN1CzhtYUc60ovEUXWehV_cU9eB6sYxeL2cQxQ; expires=Tue, 28-Oct-2025 11:37:34 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#12 0.496 set-cookie: __Secure-ENID=27.SE=R7fT0x7mP7GbuZD9fJhrLQUIrI8akjjBeOlsWxnOHRX1Eo3amQYYFQ56t6mxhB_Y5A-GRXqQp665TEjnyo6TOxlwjSLZuaqO-r1HBmuSCV6LIcfSDFl9ITm2ze3QcGTNzCcbUqb7l8QA8Qm43FKNVhpdDpw-MMhFz2sXJKKzYlFYJfWnLWr8iurpXCVQM6h-nChGn4t-B9edOUDFvSjACvc5tHFuz5xpgBII4-ndZoOAOW23S6aaZEmyvdJJ; expires=Mon, 01-Jun-2026 03:55:52 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#12 0.496 alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
#12 0.496 
#12 DONE 0.5s

#13 [web  9/10] RUN chmod 777 /run/php /var/log
#13 DONE 0.5s

#14 [web 10/10] RUN mkdir -p /tmp/xhprof && chmod -R ugo+w /etc/php /var/lib/php /tmp/xhprof
#14 DONE 1.6s

#15 [web] exporting to image
#15 exporting layers
#15 exporting layers 1.0s done
#15 exporting manifest sha256:b0c0bc1227dc8d84f06865beedf6077c6ddfd1d4d16dc275d400a2b16219e5df 0.0s done
#15 exporting config sha256:725213ffabe62926134038b4f5d463027bb57c2b99d9a08dc44c9dd7e419566e 0.0s done
#15 exporting attestation manifest sha256:d641091e1bb07cbba3efa9f263aeb9d43145eb2d17be126bf0c4b575e67195c4 0.0s done
#15 exporting manifest list sha256:60db13badc415a3efb1fcc22bdaf1362ef0f958044022b378e125889a76c2796
#15 exporting manifest list sha256:60db13badc415a3efb1fcc22bdaf1362ef0f958044022b378e125889a76c2796 0.0s done
#15 naming to docker.io/ddev/ddev-webserver:v1.24.4-tryddevproject-29210-built done
#15 unpacking to docker.io/ddev/ddev-webserver:v1.24.4-tryddevproject-29210-built
#15 unpacking to docker.io/ddev/ddev-webserver:v1.24.4-tryddevproject-29210-built 0.3s done
#15 DONE 1.5s

#16 [web] resolving provenance for metadata file
#16 DONE 0.0s
 web  Built
Rebuilt Docker cache for project tryddevproject-29210 in 12s
Network ddev_default created
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Using custom web-build configuration: [
	/home/akiba/Projects/tryddevproject-29210/.ddev/web-build/Dockerfile.test
]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
v1.24.4: Pulling from ddev/ddev-dbserver-mariadb-10.11
1ebbf5e8fdb9: Pulling fs layer
7e9e7bda14da: Pulling fs layer
cbabeda24ec6: Pulling fs layer
cdb0276abf64: Pulling fs layer
e54392e56360: Pulling fs layer
bfd6adc85b5f: Pulling fs layer
7c24292b64e2: Pulling fs layer
4f4fb700ef54: Pulling fs layer
16cde4e0c5f9: Pulling fs layer
c1f62eab2318: Pulling fs layer
84fcff9187a6: Pulling fs layer
4f4fb700ef54: Pulling fs layer
e00be9f0138b: Pulling fs layer
83e8d3443b5f: Pulling fs layer
d01b2c099ea1: Pulling fs layer
80bdcc6e5c0e: Pulling fs layer
4e0d8410ccaa: Pulling fs layer
4f4fb700ef54: Pulling fs layer
57c19184f838: Pulling fs layer
1db5af178e2c: Pulling fs layer
4f4fb700ef54: Pulling fs layer
b515be6a51b7: Pulling fs layer
b2ff9d74e625: Pulling fs layer
b5d0c07e1b39: Pulling fs layer
4f4fb700ef54: Pulling fs layer
4f4fb700ef54: Pulling fs layer
05b596fc5153: Pulling fs layer
146766f55375: Pulling fs layer
4f4fb700ef54: Pulling fs layer
edb9e2f7fe14: Pulling fs layer
9cb31e2e37ea: Pulling fs layer
d645c8b36c27: Pulling fs layer
5d78e461641c: Pulling fs layer
4f4fb700ef54: Already exists
cbabeda24ec6: Download complete
1ebbf5e8fdb9: Download complete
84fcff9187a6: Download complete
e00be9f0138b: Download complete
c1f62eab2318: Download complete
bfd6adc85b5f: Download complete
d01b2c099ea1: Download complete
b515be6a51b7: Download complete
80bdcc6e5c0e: Download complete
1db5af178e2c: Download complete
83e8d3443b5f: Download complete
b2ff9d74e625: Download complete
7e9e7bda14da: Download complete
16cde4e0c5f9: Download complete
5d78e461641c: Download complete
cdb0276abf64: Download complete
4e0d8410ccaa: Download complete
d645c8b36c27: Download complete
edb9e2f7fe14: Download complete
b5d0c07e1b39: Download complete
05b596fc5153: Download complete
146766f55375: Download complete
7c24292b64e2: Download complete
9cb31e2e37ea: Download complete
9cb31e2e37ea: Pull complete
b5d0c07e1b39: Pull complete
7e9e7bda14da: Pull complete
146766f55375: Pull complete
57c19184f838: Download complete
4e0d8410ccaa: Pull complete
e54392e56360: Download complete
c1f62eab2318: Pull complete
d645c8b36c27: Pull complete
e54392e56360: Pull complete
4f4fb700ef54: Pull complete
d01b2c099ea1: Pull complete
80bdcc6e5c0e: Pull complete
b515be6a51b7: Pull complete
57c19184f838: Pull complete
5d78e461641c: Pull complete
cbabeda24ec6: Pull complete
b2ff9d74e625: Pull complete
e00be9f0138b: Pull complete
16cde4e0c5f9: Pull complete
cdb0276abf64: Pull complete
05b596fc5153: Pull complete
83e8d3443b5f: Pull complete
edb9e2f7fe14: Pull complete
7c24292b64e2: Pull complete
1ebbf5e8fdb9: Pull complete
84fcff9187a6: Pull complete
bfd6adc85b5f: Pull complete
1db5af178e2c: Pull complete
Digest: sha256:98174978ec8e67982c6c22eb4bb1daf8637f3d9b108af3ef89492b5dca29e602
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.11:v1.24.4
docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.24.4
Building project images........
Project images built in 6s.
 Network ddev-tryddevproject-29210_default  Created
 Container ddev-tryddevproject-29210-web  Created
 Container ddev-tryddevproject-29210-db  Created
 Container ddev-tryddevproject-29210-db  Started
 Container ddev-tryddevproject-29210-web  Started
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started


======== Project startup ========
Starting tryddevproject-29210...
2025-05-01T13:38:23.344 GetAvailableRouterPort(): Router is healthy and running
2025-05-01T13:38:23.361 GetAvailableRouterPort(): proposedPort 80 already bound on ddev-router, accepting it
2025-05-01T13:38:23.378 GetAvailableRouterPort(): Router is healthy and running
2025-05-01T13:38:23.394 GetAvailableRouterPort(): proposedPort 443 already bound on ddev-router, accepting it
2025-05-01T13:38:23.413 GetAvailableRouterPort(): Router is healthy and running
2025-05-01T13:38:23.43 GetAvailableRouterPort(): proposedPort 8025 already bound on ddev-router, accepting it
2025-05-01T13:38:23.447 GetAvailableRouterPort(): Router is healthy and running
2025-05-01T13:38:23.465 GetAvailableRouterPort(): proposedPort 8026 already bound on ddev-router, accepting it
2025-05-01T13:38:23.592 Pulled image for ddev/ddev-webserver:v1.24.4
2025-05-01T13:38:23.62 Pulled image for busybox:stable
2025-05-01T13:38:23.639 Pulled image for ddev/ddev-utilities
2025-05-01T13:38:23.662 Pulled image for ddev/ddev-ssh-agent:v1.24.4
2025-05-01T13:38:23.691 Pulled image for ddev/ddev-traefik-router:v1.24.4
2025-05-01T13:38:25.105 chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
2025-05-01T13:38:25.813 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
Using custom web-build configuration: [
	/home/akiba/Projects/tryddevproject-29210/.ddev/web-build/Dockerfile.test
]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
2025-05-01T13:38:25.849 host.docker.internal='' because IsWSL2 and IsDockerDesktop
2025-05-01T13:38:25.866 Using automatically detected timezone: TZ=Europe/Vienna
2025-05-01T13:38:25.959 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.24.4
2025-05-01T13:38:25.975 Pulled image for ddev/ddev-webserver:v1.24.4
2025-05-01T13:38:25.996 Pulled image for ddev/ddev-ssh-agent:v1.24.4
2025-05-01T13:38:26.022 Pulled image for ddev/ddev-traefik-router:v1.24.4
Building project images...
2025-05-01T13:38:26.027 Executing docker-compose -f /home/akiba/Projects/tryddevproject-29210/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.
Project images built in 2s.
2025-05-01T13:38:27.62 Removing dangling images for the project ddev-tryddevproject-29210
2025-05-01T13:38:27.685 Executing docker-compose -f /home/akiba/Projects/tryddevproject-29210/.ddev/.ddev-docker-compose-full.yaml up -d
 Container ddev-tryddevproject-29210-web  Recreate
 Container ddev-tryddevproject-29210-db  Recreate
 Container ddev-tryddevproject-29210-db  Recreated
 Container ddev-tryddevproject-29210-web  Recreated
 Container ddev-tryddevproject-29210-db  Started
 Container ddev-tryddevproject-29210-web  Started
2025-05-01T13:38:40.36 VIRTUAL_HOST=tryddevproject-29210.ddev.site for web
2025-05-01T13:38:40.36 HTTP_EXPOSE=80:80,8025:8025 for web
2025-05-01T13:38:40.36 HTTPS_EXPOSE=443:80,8026:8025 for web
2025-05-01T13:38:40.36 VIRTUAL_HOST=tryddevproject-29210.ddev.site for xhgui
2025-05-01T13:38:40.36 HTTP_EXPOSE=8143:80 for xhgui
2025-05-01T13:38:40.36 HTTPS_EXPOSE=8142:80 for xhgui
2025-05-01T13:38:40.854 Copied /home/akiba/Projects/tryddevproject-29210/.ddev/traefik:CopyIntoVolume_ghmsmxxhofvg into /mnt/v/traefik in 54.318726ms
2025-05-01T13:38:40.888 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-05-01T13:38:41.212 Copied Traefik certs in /home/akiba/Projects/tryddevproject-29210/.ddev/traefik/certs to ddev-global-cache/traefik
2025-05-01T13:38:41.212 Running /start.sh in ddev-webserver
Waiting for containers to become ready: [web db]
2025-05-01T13:38:44.713 Copied /home/akiba/.ddev/commands:CopyIntoVolume_uckyihtijkxz into /mnt/v/global-commands in 50.424513ms
2025-05-01T13:38:44.746 Exec chown -R 1000 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2025-05-01T13:38:45.346 Testing to see if /mnt/ddev_config is properly mounted
2025-05-01T13:38:45.544 Getting stderr output from 'log-stderr.sh --show'
Starting ddev-router if necessary...
2025-05-01T13:38:46.409 Copied /home/akiba/.ddev/traefik:CopyIntoVolume_oncquaigtjth into /mnt/v/traefik in 57.628335ms
2025-05-01T13:38:46.448 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-05-01T13:38:46.822 Copied global Traefik config in /home/akiba/.ddev/traefik/certs to ddev-global-cache/traefik
2025-05-01T13:38:46.979 Waiting for ddev-router to become ready, timeout=60
2025-05-01T13:38:47.498 ddev-router is ready
Successfully started tryddevproject-29210
Your project can be reached at https://tryddevproject-29210.ddev.site
See 'ddev describe' for alternate URLs.


======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 01 May 2025 11:38:50 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://127.0.0.1:19028 (web container http docker bind port) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 01 May 2025 11:38:50 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://tryddevproject-29210.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Thu, 01 May 2025 11:38:50 GMT
Server: nginx
Vary: Accept-Encoding



======== Full curl of http://tryddevproject-29210.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   198    0   198    0     0  58684      0 --:--:-- --:--:-- --:--:-- 66000
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Full curl of https://tryddevproject-29210.ddev.site (router https URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the webpage mentioned above.


======== Curl google.com to check internet access and VPN ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-vZEmaMYISKgJkfC5HIoSig' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Thu, 01 May 2025 11:38:50 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Thu, 01 May 2025 11:38:50 GMT
cache-control: private
set-cookie: AEC=AVcja2fyXR_uJ8vBMGdLgTFklFElu5NHEmKAsY-IyQbhAoWunvY9ncNpSA; expires=Tue, 28-Oct-2025 11:38:50 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: __Secure-ENID=27.SE=DIPywBqBjHGs1p2uB2HOCBnrXyQ4Z4DMPTZttNuVvEBA86qkXfw8G7fro6in66F43TzUpGYw8Di_LB9PBJcUmG3PUWC2kMyeK7q3uUcvoATOczYUxJE3z0QPX6lQo94NLgNbpPo6z01DhEtY2wvUfXo8lF64h8uKXeW3oC1-LrVQkDs1NWQ7N8Igv-vO39rMo_-wXiOPn323-6NsnAi7fXhgIxIRU-t9zc3ayfUiDpqKLdPhwnTL8MEPDrQ4YQ; expires=Mon, 01-Jun-2026 03:57:08 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000



======== host.docker.internal status ========
PING host.docker.internal (192.168.65.254) 56(84) bytes of data.
64 bytes from 192.168.65.254 (192.168.65.254): icmp_seq=1 ttl=63 time=0.701 ms

--- host.docker.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.701/0.701/0.701/0.000 ms


======== Project ownership on host ========
drwxr-xr-x 4 akiba akiba 4096 May  1 13:37 ../tryddevproject-29210


======== Project ownership in container ========
drwxr-xr-x 4 akiba akiba 4096 May  1 13:37 //var/www/html


======== In-container filesystem ========
Filesystem     Type  1K-blocks      Used Available Use% Mounted on
/dev/sde       ext4 1055762868 154192184 847867212  16% /var/www/html


======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting for ddev launch to complete before deleting project


Cleanup: deleting test project tryddevproject-29210
 Container ddev-tryddevproject-29210-db  Stopped
 Container ddev-tryddevproject-29210-web  Stopped
 Container ddev-tryddevproject-29210-web  Stopped
 Container ddev-tryddevproject-29210-db  Stopped
 Container ddev-tryddevproject-29210-web  Removed
 Container ddev-tryddevproject-29210-db  Removed
 Network ddev-tryddevproject-29210_default  Removed
Volume tryddevproject-29210-mariadb for project tryddevproject-29210 was deleted
Volume tryddevproject-29210-postgres for project tryddevproject-29210 was deleted
Image ddev/ddev-dbserver-mariadb-10.11:v1.24.4-tryddevproject-29210-built for project tryddevproject-29210 was deleted
Image ddev/ddev-webserver:v1.24.4-tryddevproject-29210-built for project tryddevproject-29210 was deleted
Project tryddevproject-29210 was deleted. Your code and configuration are unchanged.

Please remove the files from this test with 'rm -r ../tryddevproject-29210'
```
</details>

### Expected Behavior

When using `ddev share`, I expect ngrok to be routed to the primary container http port.

### Actual Behavior

Instead, traffic is being routed to a http_port added via web_extra_exposed_ports:

```
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5172
    https_port: 5173
```

```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Project: fvn-li ~/Projects/fvn.li https://fvn-li.ddev.site                                               │
│ Docker platform: docker-desktop                                                                          │
│ Router: traefik                                                                                          │
├──────────────┬──────┬───────────────────────────────────────────────────────────────┬────────────────────┤
│ SERVICE      │ STAT │ URL/PORT                                                      │ INFO               │
├──────────────┼──────┼───────────────────────────────────────────────────────────────┼────────────────────┤
│ web          │ OK   │ https://fvn-li.ddev.site                                      │ laravel PHP 8.4    │
│              │      │ InDocker -> Host:                                             │ Server: nginx-fpm  │
│              │      │  - web:80 -> 127.0.0.1:19126                                  │ Docroot: 'public'  │
│              │      │  - web:443 -> 127.0.0.1:19124                                 │ Perf mode: none    │
│              │      │  - web:5173 -> 127.0.0.1:19568                                │ Node.js: 22        │
│              │      │  - web:8025 -> 127.0.0.1:19569                                │                    │
├──────────────┼──────┼───────────────────────────────────────────────────────────────┼────────────────────┤
│ db           │ OK   │ InDocker -> Host:                                             │ postgres:17        │
│              │      │  - db:5432 -> 127.0.0.1:19127                                 │ User/Pass: 'db/db' │
│              │      │                                                               │ or 'root/root'     │
├──────────────┼──────┼───────────────────────────────────────────────────────────────┼────────────────────┤
│ redis        │ OK   │ InDocker:                                                     │                    │
│              │      │  - redis:6379                                                 │                    │
├──────────────┼──────┼───────────────────────────────────────────────────────────────┼────────────────────┤
│ Mailpit      │      │ Mailpit: https://fvn-li.ddev.site:8026                        │                    │
│              │      │ Launch: ddev mailpit                                          │                    │
├──────────────┼──────┼───────────────────────────────────────────────────────────────┼────────────────────┤
│ vite         │      │ https://fvn-li.ddev.site:5173                                 │                    │
│              │      │ InDocker: web:5173                                            │                    │
├──────────────┼──────┼───────────────────────────────────────────────────────────────┼────────────────────┤
│ Project URLs │      │ https://fvn-li.ddev.site, https://127.0.0.1:19124,            │                    │
│              │      │ http://fvn-li.ddev.site, http://127.0.0.1:19568               │                    │
└──────────────┴──────┴───────────────────────────────────────────────────────────────┴────────────────────┘
```

`ddev share`

```
Forwarding                    https://x.ngrok-free.app -> http://127.0.0.1:19568     
```

19568 maps to 5173, which is the container port of my vite config.

### Steps To Reproduce

Have ngrok set up and authenticated as per https://ngrok.com/docs/getting-started/
```
mkdir share_test
cd share_test
ddev config --project-type=php --omit-containers=db
```

Add `web_extra_exposed_ports` to `.ddev/config.yaml`:
```
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5172
    https_port: 5173
```

```
ddev start
ddev share
```

Verify that ngrok is pointing to the container_port of the vite web_extra_exposed_ports config.

### Anything else?

Looking at GetWebContainerDirectHTTPPort, the default mailpit port (8025) is being excluded from consideration, but this ignores the fact that it can be changed to a different port via `config.yaml`.

### PR DESCRIPTION
**Pull request by AkibaAT**
## The Issue

- #7246 

## How This PR Solves The Issue

Fix up `GetWebContainerDirectHTTPPort` and `GetWebContainerHTTPSPublicPort` to preferably use `app.GetPublishedPortForPrivatePort("web", 80)` and `app.GetPublishedPortForPrivatePort("web", 443)`, and fall back only for generic type projects.

## Manual Testing Instructions

Have ngrok set up and authenticated as per https://ngrok.com/docs/getting-started/
```
mkdir share_test
cd share_test
ddev config --project-type=php --omit-containers=db
```

Add `web_extra_exposed_ports` to `.ddev/config.yaml`:
```
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5172
    https_port: 5173
```

```
ddev start
ddev share
```

Verify that `ddev share` maps to the expected port, instead of the web_extra_exposed_ports it did before.

Additionally, test the same with https://ddev.readthedocs.io/en/stable/users/quickstart/#generic-frankenphp to verify that generic projects also behave correctly.

## Automated Testing Overview

Added new tests:
- TestGetWebContainerDirectURLs tests the GetWebContainerDirectHTTPURL and GetWebContainerDirectHTTPSURL functions
- TestGetWebContainerDirectURLsErrorHandling tests error handling in GetWebContainerDirectHTTPURL and GetWebContainerDirectHTTPSURL
- TestGetWebContainerDirectURLsWithDockerIPError tests behavior when GetDockerIP returns an error

## Release/Deployment Notes

n/a

### CODE REVIEW

**Comment by AkibaAT** [comment]
TestDdevFullSiteSetup for site TestPkgSveltekit is failing.

Project setup:
```
webserver_type: generic
web_extra_exposed_ports:
    - name: svelte
      container_port: 3000
      http_port: 80
      https_port: 443
```

Ports at time of check:
image

**Comment by AkibaAT** [comment]
So `app.GetPublishedPortForPrivatePort("web", 80)` is too simple after all, because for generic project type, the private port doesn't have to be 80. But the intended public port is 80, and same for 443.

**Comment by rfay** [comment]
Thanks for studying it so carefully!

**Comment by AkibaAT** [comment]
> Thanks for studying it so carefully!

Before I clean up and declare this ready for review, there's one remaining question about the priority and fallback logic, and if it's sufficient this way:

- Prefer `app.GetPublishedPortForPrivatePort("web", 80)`
- If generic type, look for a `web_extra_exposed_ports` with `http_port: 80`
- Throw error

Should it fall back further and return the first http port like the current code does?
Is there a different mapping way we have to take into account here? (e.g. docker compose config)

**Comment by rfay** [comment]
This looks like a great strategy to me, and wow, thanks for the tests too!

Could you rework the manual testing instructions (or add to) using `ddev describe` instead of or in addition to the less direct `ddev share` technique? `ddev describe` should show the detected port clearly I hope.

**Comment by rfay** [comment]
This should be on a good path, thanks for undertaking it. Move to "ready for review" when you're satisfied.

File: pkg/ddevapp/ddevapp.go [hunk 1]
```diff
@@ -3140,49 +3143,73 @@ func (app *DdevApp) GetWebContainerDirectHTTPSURL() string {
...
+	if app.WebserverType == nodeps.WebserverGeneric && len(app.WebExtraExposedPorts) > 0 {
+		for _, extraPort := range app.WebExtraExposedPorts {
+			// Check only ports mapped to HTTP (port 80)
+			if extraPort.HTTPPort == 80 {
+				containerPort := uint16(extraPort.WebContainerPort)
+				publishedPort, err := app.GetPublishedPortForPrivatePort("web", containerPort)
+				if err == nil && publishedPort != 0 {
+					return publishedPort, nil
+				}
+			}
```
Comment (stasadev) [inline pkg/ddevapp/ddevapp.go:3179]: I'm handling a similar case in this PR:

- https://github.com/ddev/ddev/pull/7171/files#diff-b91d6b70cb12af7da31b8f31100e04f6cb12aa023a5cde9cc03e11521b2bac9fR536-R541

Currently, I select the first port pair without checking the port numbers.

Your approach (preferring ports 80/443) makes sense. However, we can't assume those ports will appear in the same pair. Consider the following (stupid, but possible) config:

```yaml
web_extra_exposed_ports:
  - name: test
    container_port: 80
    http_port: 80
    https_port: 12345
  - name: test2
    container_port: 81
    http_port: 11111
    https_port: 443
```

In this example, `http_port: 80` and `https_port: 443` are in different entries.

So I suggest we:

1. Prefer a port pair where `http_port: 80`.
2. If none exists, fall back to the first available pair.

I'll update my PR accordingly to implement this preference logic.

**Review by stasadev — COMMENTED** [review]
Nice work on this issue (how did I never catch it in the wild? 🙂)

File: pkg/ddevapp/ddevapp.go (hunk 1 above)
Comment (AkibaAT) [reply pkg/ddevapp/ddevapp.go:3179]: Hmmm, is that expectable behaviour? I personally wouldn't expect, if, for whatever reason, I set 443 is on a different mapping pair, for that to be ignored, and for GetWebContainerHTTPSPublicPort to still return the one from the 80 pair. Like, I'd have clearly set it that way with some sort of intention in the described hypothetical scenario.

Comment (stasadev) [reply pkg/ddevapp/ddevapp.go:3179]: I will experiment with this more.

Comment (rfay) [reply pkg/ddevapp/ddevapp.go:3179]: Just for clarity, the internal https port is never really intended to be used, and it shouldn't be used with the traefik router, only http protocol should ever be used by the router.  The direct web container https port is just there for people who have no other options, it's not even used on gitpod or codespaces.

**Review by rfay — APPROVED** [review]
Thanks for the great manual testing instructions and the new tests!

The code looks good to me, and I don't think it involves any risks. 

Manual testing works out fine with both scenarios, thanks!

**Comment by rfay** [comment]
If you like this now @AkibaAT please move to ready for review

File: pkg/ddevapp/ddevapp.go (hunk 1 above)
Comment (stasadev) [reply pkg/ddevapp/ddevapp.go:3179]: I'm definitely overthinking it. The provided code handles the default scenario, which should be enough.

**Review by stasadev — APPROVED** [review]
Thank you! Looks good to me.

**Comment by rfay** [comment]
Thanks so much for the careful and thoughtful work on this @AkibaAT !
