### PR TITLE
fix: use `charset=utf8mb4` in DATABASE_URL for Symfony environment variables, fixes #7068

### LINKED ISSUE #7068: MySQL Charset Issue with Symfony Integration
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
======== Output file will be in /tmp/ddev-debug-test.txt ========


======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev
/bin/ddev

These config files were loaded for project rnd-shortuuid: [/home/ruben_colpaert/projects/rnd-shortuuid/.ddev/config.yaml]
name: rnd-shortuuid
type: symfony
docroot: public
php_version: 8.4
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.24.3
additional_hostnames: []
additional_fqdns: []
database: {mysql 8.4}
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 22
default_container_timeout: 120


======== existing project customizations ========


======== installed DDEV add-ons ========
No registered add-ons were found.


======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /home/ruben_colpaert/projects/rnd-shortuuid
.ddev/mutagen/mutagen.yml not found


======== Creating dummy project named tryddevproject-620 in ../tryddevproject-620 ========
Creating a new DDEV project config in the current directory (/home/ruben_colpaert/projects/tryddevproject-620)
Once completed, your configuration will be written to /home/ruben_colpaert/projects/tryddevproject-620/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-620' with docroot 'web' at '/home/ruben_colpaert/projects/tryddevproject-620/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.


======== OS Information ========
Linux DJRK3T3 6.8.0-52-generic #53~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 15 19:18:46 UTC 2 x86_64 x86_64 x86_64 GNU/Linux


======== User information ========
uid=1001(ruben_colpaert) gid=1001(ruben_colpaert) groups=1001(ruben_colpaert),27(sudo),998(docker)


======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.24.3                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.24.3 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.24.3              
 docker           28.0.1                                   
 docker-api       1.48                                     
 docker-compose   v2.33.1                                  
 docker-platform  linux-docker                             
 global-ddev-dir  /home/ruben_colpaert/.ddev               
 mutagen          0.18.1                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.24.3         
 web              ddev/ddev-webserver:v1.24.3              



======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 


======== DDEV global info ========
developer-mode=false
fail-on-hook-fail=false
instrumentation-opt-in=true
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.24.3
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/home/ruben_colpaert/.local/share/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=none
project-tld=ddev.site
required-docker-compose-version=v2.33.1
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=


======== DOCKER provider info ========
docker client location: -rwxr-xr-x 1 root root 43049064 Feb 26 11:41 /usr/bin/docker

docker client alternate locations:
/usr/bin/docker
/bin/docker

Docker provider: linux-docker
docker version: 
Client: Docker Engine - Community
 Version:           28.0.1
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        068a01e
 Built:             Wed Feb 26 10:41:08 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.1
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       bbd0a17
  Built:            Wed Feb 26 10:41:08 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker context: 
NAME            DESCRIPTION                               DOCKER ENDPOINT                                           ERROR
default *       Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                               
desktop-linux                                             unix:///home/ruben_colpaert/.docker/desktop/docker.sock   
Warning: DOCKER_HOST environment variable overrides the active context. To use a context, either set the global --context flag, or unset DOCKER_HOST environment variable.


DOCKER_DEFAULT_PLATFORM=notset
Docker platform: linux-docker
Using Docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.33.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 28.0.1
Docker API version: 1.48
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:Filesystem                Size      Used Available Use% Mounted on
overlay                 146.6G    124.6G     14.5G  90% /


======== Existing docker containers ========
CONTAINER ID   IMAGE                               COMMAND     CREATED       STATUS    PORTS     NAMES
8c91e2b9db74   phpstorm_helpers:PS-243.25659.45    "/bin/sh"   2 days ago    Created             phpstorm_helpers_PS-243.25659.45
3d0420b38ede   phpstorm_helpers:PS-243.23654.168   "/bin/sh"   4 weeks ago   Created             phpstorm_helpers_PS-243.23654.168


======== mkcert information ========
/usr/bin/mkcert
/bin/mkcert
CAROOT= WSLENV= JAVA_HOME=
/home/ruben_colpaert/.local/share/mkcert
total 8
-r-------- 1 ruben_colpaert ruben_colpaert 2484 Apr  6  2023 rootCA-key.pem
-rw-r--r-- 1 ruben_colpaert ruben_colpaert 1761 Apr  6  2023 rootCA.pem


======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.062 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.062/0.062/0.062/0.000 ms


======== curl information ========
/usr/bin/curl
/bin/curl


======== ddev debug rebuild ========
Rebuilding project images...
Rebuilding project tryddevproject-620 with `/home/ruben_colpaert/.ddev/bin/docker-compose -f /home/ruben_colpaert/projects/tryddevproject-620/.ddev/.ddev-docker-compose-full.yaml --progress plain build web --no-cache`
#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.55kB done
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/ddev/ddev-webserver:v1.24.3
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web  1/10] FROM docker.io/ddev/ddev-webserver:v1.24.3
#4 CACHED

#5 [web  2/10] RUN getent group tty || groupadd tty
#5 0.105 tty:x:5:
#5 DONE 0.1s

#6 [web  3/10] RUN (groupadd --gid 1001 "ruben_colpaert" || groupadd "ruben_colpaert" || true) && (useradd -G tty -l -m -s "/bin/bash" --gid "ruben_colpaert" --comment '' --uid 1001 "ruben_colpaert" || useradd -G tty -l -m -s "/bin/bash" --gid "ruben_colpaert" --comment '' "ruben_colpaert" || useradd  -G tty -l -m -s "/bin/bash" --gid "1001" --comment '' "ruben_colpaert" || useradd -G tty -l -m -s "/bin/bash" --comment '' ruben_colpaert )
#6 DONE 0.1s

#7 [web  4/10] RUN mkdir -p /home/ruben_colpaert && chown ruben_colpaert /home/ruben_colpaert && chmod 600 /home/ruben_colpaert/.pgpass
#7 DONE 0.2s

#8 [web  5/10] RUN START_SCRIPT_TIMEOUT=30 mariadb-client-install.sh || true
#8 0.119 This script is not intended to run with mariadb:10.11
#8 DONE 0.1s

#9 [web  6/10] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || log-stderr.sh composer self-update --2 || true
#9 0.208 Storing "stable" as default update channel for the next self-update run.
#9 0.320 You are already using the latest available Composer version 2.8.6 (stable channel).
#9 0.537 You are already using the latest available Composer version 2.8.6 (2.x channel).
#9 DONE 0.6s

#10 [web  7/10] RUN timeout 30 apt-get update || true
#10 0.289 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#10 0.303 Get:2 http://nginx.org/packages/debian bookworm InRelease [2869 B]
#10 0.337 Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#10 0.356 Get:4 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#10 0.384 Get:5 http://nginx.org/packages/debian bookworm/nginx amd64 Packages [17.8 kB]
#10 0.387 Get:6 https://packages.sury.org/php bookworm InRelease [7551 B]
#10 0.435 Get:8 http://deb.debian.org/debian bookworm/main amd64 Packages [8792 kB]
#10 0.589 Get:9 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm InRelease [3675 B]
#10 0.598 Get:10 https://packages.sury.org/php bookworm/main amd64 Packages [255 kB]
#10 0.695 Get:11 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [129 kB]
#10 0.741 Get:12 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.5 kB]
#10 0.742 Get:13 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [246 kB]
#10 0.755 Get:14 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm InRelease [3681 B]
#10 0.873 Get:15 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 Packages [361 kB]
#10 0.889 Get:16 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [4422 B]
#10 1.022 Get:17 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm/main amd64 Packages [4504 B]
#10 1.100 Get:18 http://packages.blackfire.io/debian any InRelease [29.2 kB]
#10 1.149 Get:19 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm/main amd64 Packages [3347 B]
#10 1.506 Get:7 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease [4628 B]
#10 1.570 Get:20 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main amd64 Packages [8556 B]
#10 2.160 Get:21 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main arm64 Packages [35.2 kB]
#10 2.217 Get:22 http://packages.blackfire.io/debian any/main amd64 Packages [31.8 kB]
#10 2.609 Get:23 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main amd64 Packages [42.1 kB]
#10 2.647 Fetched 10.3 MB in 2s (4182 kB/s)
#10 2.647 Reading package lists...
#10 DONE 3.0s

#11 [web  8/10] RUN curl -I https://www.google.com
#11 0.157   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#11 0.157                                  Dload  Upload   Total   Spent    Left  Speed
#11 0.157 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#11 0.238 HTTP/2 200 
#11 0.238 content-type: text/html; charset=ISO-8859-1
#11 0.238 content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-W5ejkRKM3OY6tNhLrAK4qQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
#11 0.238 accept-ch: Sec-CH-Prefers-Color-Scheme
#11 0.238 p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
#11 0.238 date: Wed, 12 Mar 2025 13:24:41 GMT
#11 0.238 server: gws
#11 0.238 x-xss-protection: 0
#11 0.238 x-frame-options: SAMEORIGIN
#11 0.238 expires: Wed, 12 Mar 2025 13:24:41 GMT
#11 0.238 cache-control: private
#11 0.238 set-cookie: AEC=AVcja2eapj8D6WPCYrreRrPAnv6Kie5Pv9oLjPFCQ31V7n0xAaGNoHKJ7A; expires=Mon, 08-Sep-2025 13:24:41 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#11 0.238 set-cookie: __Secure-ENID=26.SE=PdeEymKZCK0f25tJ9VJsqZt2FdlI_4KChq_FHs3BYfdwosOGFhSheuy59lcqk42a4JuGcfCLVyEzftIXl55FwesT7pRlA3RnYdP9DImjyNdg6g3MG2zeG6VJfmPRxkYkmbSLdZemJbBwTpo8NsFolHdqKDSNotu-5bxh999ZpzjH3_Fx-dEPH4jhXoi9KpUvUKcxAtYU5eVTzVDxMFKLZ6M7Xy_HXvVHoepc-9wmqt_HCCzZF4cpjC3l; expires=Sun, 12-Apr-2026 05:42:59 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#11 0.238 alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
#11 0.238 
#11 DONE 0.2s

#12 [web  9/10] RUN chmod 777 /run/php /var/log
#12 DONE 0.1s

#13 [web 10/10] RUN mkdir -p /tmp/xhprof && chmod -R ugo+w /etc/php /var/lib/php /tmp/xhprof
#13 DONE 0.2s

#14 [web] exporting to image
#14 exporting layers 0.0s done
#14 writing image sha256:997a014c4fd1d72b6a0636cdf4634437051a978a8f5ec6aa57b3e81b2f92c375 done
#14 naming to docker.io/ddev/ddev-webserver:v1.24.3-tryddevproject-620-built done
#14 DONE 0.0s

#15 [web] resolving provenance for metadata file
#15 DONE 0.0s
 web  Built
Rebuilt Docker cache for project tryddevproject-620 in 5s
Network ddev_default created
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Using custom web-build configuration: [
	/home/ruben_colpaert/projects/tryddevproject-620/.ddev/web-build/Dockerfile.test
]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
v1.24.3: Pulling from ddev/ddev-dbserver-mariadb-10.11
9cb31e2e37ea: Already exists
b5d0c07e1b39: Pulling fs layer
146766f55375: Pulling fs layer
7e9e7bda14da: Pulling fs layer
4e0d8410ccaa: Pulling fs layer
e54392e56360: Pulling fs layer
c1f62eab2318: Pulling fs layer
d645c8b36c27: Pulling fs layer
4f4fb700ef54: Pulling fs layer
e54392e56360: Waiting
0d0506066f94: Pulling fs layer
c1f62eab2318: Waiting
cabb0df5366e: Pulling fs layer
4e0d8410ccaa: Waiting
0de630bea834: Pulling fs layer
6983a363f308: Pulling fs layer
4f4fb700ef54: Waiting
d645c8b36c27: Waiting
45703da1b505: Pulling fs layer
0d0506066f94: Waiting
f135cc67e118: Pulling fs layer
cabb0df5366e: Waiting
0de630bea834: Waiting
35d41eaf9359: Pulling fs layer
6983a363f308: Waiting
67db047c3421: Pulling fs layer
45703da1b505: Waiting
f135cc67e118: Waiting
35d41eaf9359: Waiting
d94963e1d855: Pulling fs layer
67db047c3421: Waiting
449645ada642: Pulling fs layer
609e326bc20a: Pulling fs layer
c624665b4d51: Pulling fs layer
a587269fc15e: Pulling fs layer
609e326bc20a: Waiting
8c3c7766f4c7: Pulling fs layer
449645ada642: Waiting
a587269fc15e: Waiting
e5303f7dcc49: Pulling fs layer
84fcff9187a6: Pulling fs layer
c624665b4d51: Waiting
5986183768bb: Pulling fs layer
8b35c8cf300b: Pulling fs layer
e5303f7dcc49: Waiting
5986183768bb: Waiting
8b35c8cf300b: Waiting
7e9e7bda14da: Verifying Checksum
7e9e7bda14da: Download complete
b5d0c07e1b39: Download complete
b5d0c07e1b39: Pull complete
146766f55375: Verifying Checksum
146766f55375: Download complete
146766f55375: Pull complete
7e9e7bda14da: Pull complete
4e0d8410ccaa: Download complete
4e0d8410ccaa: Pull complete
c1f62eab2318: Download complete
d645c8b36c27: Download complete
4f4fb700ef54: Download complete
0d0506066f94: Verifying Checksum
0d0506066f94: Download complete
cabb0df5366e: Verifying Checksum
cabb0df5366e: Download complete
6983a363f308: Download complete
45703da1b505: Verifying Checksum
45703da1b505: Download complete
e54392e56360: Verifying Checksum
e54392e56360: Download complete
f135cc67e118: Verifying Checksum
f135cc67e118: Download complete
35d41eaf9359: Verifying Checksum
35d41eaf9359: Download complete
e54392e56360: Pull complete
c1f62eab2318: Pull complete
d645c8b36c27: Pull complete
4f4fb700ef54: Pull complete
67db047c3421: Verifying Checksum
67db047c3421: Download complete
0d0506066f94: Pull complete
cabb0df5366e: Pull complete
d94963e1d855: Verifying Checksum
d94963e1d855: Download complete
0de630bea834: Download complete
609e326bc20a: Verifying Checksum
609e326bc20a: Download complete
449645ada642: Verifying Checksum
449645ada642: Download complete
c624665b4d51: Verifying Checksum
c624665b4d51: Download complete
a587269fc15e: Download complete
0de630bea834: Pull complete
6983a363f308: Pull complete
45703da1b505: Pull complete
f135cc67e118: Pull complete
35d41eaf9359: Pull complete
67db047c3421: Pull complete
d94963e1d855: Pull complete
449645ada642: Pull complete
609e326bc20a: Pull complete
c624665b4d51: Pull complete
a587269fc15e: Pull complete
8c3c7766f4c7: Download complete
8c3c7766f4c7: Pull complete
e5303f7dcc49: Verifying Checksum
e5303f7dcc49: Download complete
e5303f7dcc49: Pull complete
84fcff9187a6: Verifying Checksum
84fcff9187a6: Download complete
84fcff9187a6: Pull complete
5986183768bb: Verifying Checksum
5986183768bb: Download complete
5986183768bb: Pull complete
8b35c8cf300b: Verifying Checksum
8b35c8cf300b: Download complete
8b35c8cf300b: Pull complete
Digest: sha256:2b9911669de0f220fef105b426e3ffff418c8072fe7822fdd9ab2d33b703b168
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.11:v1.24.3
docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.24.3
Building project images....
Project images built in 1s.
 Network ddev-tryddevproject-620_default  Created
 Container ddev-tryddevproject-620-web  Created
 Container ddev-tryddevproject-620-db  Created
 Container ddev-tryddevproject-620-db  Started
 Container ddev-tryddevproject-620-web  Started
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started


======== Project startup ========
Starting tryddevproject-620...
2025-03-12T14:25:13.959 GetAvailableRouterPort(): Router is healthy and running
2025-03-12T14:25:13.96 GetAvailableRouterPort(): proposedPort 80 already bound on ddev-router, accepting it
2025-03-12T14:25:13.961 GetAvailableRouterPort(): Router is healthy and running
2025-03-12T14:25:13.962 GetAvailableRouterPort(): proposedPort 443 already bound on ddev-router, accepting it
2025-03-12T14:25:13.963 GetAvailableRouterPort(): Router is healthy and running
2025-03-12T14:25:13.964 GetAvailableRouterPort(): proposedPort 8025 already bound on ddev-router, accepting it
2025-03-12T14:25:13.965 GetAvailableRouterPort(): Router is healthy and running
2025-03-12T14:25:13.966 GetAvailableRouterPort(): proposedPort 8026 already bound on ddev-router, accepting it
2025-03-12T14:25:13.982 Pulled image for ddev/ddev-webserver:v1.24.3
2025-03-12T14:25:13.983 Pulled image for busybox:stable
2025-03-12T14:25:13.983 Pulled image for ddev/ddev-utilities
2025-03-12T14:25:13.983 Pulled image for ddev/ddev-ssh-agent:v1.24.3
2025-03-12T14:25:13.984 Pulled image for ddev/ddev-traefik-router:v1.24.3
2025-03-12T14:25:14.39 chowning /mnt/ddev-global-cache and /var/lib/mysql to 1001
2025-03-12T14:25:15.103 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 1001
Using custom web-build configuration: [
	/home/ruben_colpaert/projects/tryddevproject-620/.ddev/web-build/Dockerfile.test
]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
2025-03-12T14:25:15.108 host.docker.internal='' runtime.GOOS==linux and docker 20.10+
2025-03-12T14:25:15.112 Using automatically detected timezone: TZ=Europe/Brussels
2025-03-12T14:25:15.157 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.24.3
2025-03-12T14:25:15.157 Pulled image for ddev/ddev-webserver:v1.24.3
2025-03-12T14:25:15.157 Pulled image for ddev/ddev-ssh-agent:v1.24.3
2025-03-12T14:25:15.158 Pulled image for ddev/ddev-traefik-router:v1.24.3
Building project images...
2025-03-12T14:25:15.158 Executing docker-compose -f /home/ruben_colpaert/projects/tryddevproject-620/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.
Project images built in 1s.
2025-03-12T14:25:16.379 Removing dangling images for the project ddev-tryddevproject-620
2025-03-12T14:25:16.395 Executing docker-compose -f /home/ruben_colpaert/projects/tryddevproject-620/.ddev/.ddev-docker-compose-full.yaml up -d
 Container ddev-tryddevproject-620-web  Recreate
 Container ddev-tryddevproject-620-db  Recreate
 Container ddev-tryddevproject-620-db  Recreated
 Container ddev-tryddevproject-620-web  Recreated
 Container ddev-tryddevproject-620-db  Started
 Container ddev-tryddevproject-620-web  Started
2025-03-12T14:25:27.455 VIRTUAL_HOST=tryddevproject-620.ddev.site for web
2025-03-12T14:25:27.455 HTTP_EXPOSE=80:80,8025:8025 for web
2025-03-12T14:25:27.455 HTTPS_EXPOSE=443:80,8026:8025 for web
2025-03-12T14:25:27.715 Copied /home/ruben_colpaert/projects/tryddevproject-620/.ddev/traefik:CopyIntoVolume_sztefawwjhej into /mnt/v/traefik in 39.111385ms
2025-03-12T14:25:27.759 Exec chown -R 1001 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-03-12T14:25:27.865 Copied Traefik certs in /home/ruben_colpaert/projects/tryddevproject-620/.ddev/traefik/certs to ddev-global-cache/traefik
2025-03-12T14:25:27.865 Running /start.sh in ddev-webserver
Waiting for containers to become ready: [web db]
2025-03-12T14:25:32.736 Copied /home/ruben_colpaert/.ddev/commands:CopyIntoVolume_rkcvjylddknm into /mnt/v/global-commands in 44.35897ms
2025-03-12T14:25:32.771 Exec chown -R 1001 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2025-03-12T14:25:32.935 Testing to see if /mnt/ddev_config is properly mounted
2025-03-12T14:25:33.047 Getting stderr output from 'log-stderr.sh --show'
Starting ddev-router if necessary...
2025-03-12T14:25:33.537 Copied /home/ruben_colpaert/.ddev/traefik:CopyIntoVolume_bkmrhwlrpsmq into /mnt/v/traefik in 43.736228ms
2025-03-12T14:25:33.582 Exec chown -R 1001 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-03-12T14:25:33.677 Copied global Traefik config in /home/ruben_colpaert/.ddev/traefik/certs to ddev-global-cache/traefik
 Container ddev-router  Running
2025-03-12T14:25:33.711 Waiting for ddev-router to become ready, timeout=60
2025-03-12T14:25:34.214 ddev-router is ready
Successfully started tryddevproject-620
Your project can be reached at https://tryddevproject-620.ddev.site
See 'ddev describe' for alternate URLs.


======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 12 Mar 2025 13:25:35 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://127.0.0.1:32818 (web container http docker bind port) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 12 Mar 2025 13:25:35 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://tryddevproject-620.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Wed, 12 Mar 2025 13:25:35 GMT
Server: nginx
Vary: Accept-Encoding



======== Full curl of http://tryddevproject-620.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   198    0   198    0     0   5758      0 --:--:-- --:--:-- --:--:--  5823
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Full curl of https://tryddevproject-620.ddev.site (router https URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   198    0   198    0     0   3277      0 --:--:-- --:--:-- --:--:--  3300
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Curl google.com to check internet access and VPN ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-JEL3OTo6l8ZfdvqhfFIW1g' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Wed, 12 Mar 2025 13:25:35 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Wed, 12 Mar 2025 13:25:35 GMT
cache-control: private
set-cookie: AEC=AVcja2depAoq7MFbywAGeSITKkq5gW4z4SqK-_MXiUknGFCiOG0h45J3qQ; expires=Mon, 08-Sep-2025 13:25:35 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: __Secure-ENID=26.SE=tcMoaPIyE6n_CLVLoysp1lWrC2ZYPnSviEW_Nz3YXxBDcXw52txuwAZYuvnBLsycMve-3_yohDPnvL8Jjc_qCnatXllzamhr0ryCUv_Z7Jlp7b8-hhs33P00x32HmsfJ85UBJ8BMKPfeAVyKgoC53exjAOylzXxfBXnVqDXBs0izaFIZlcAzzEdJ7uTKoGxQY6iyR4NMUMSGpP6TNU3aVArka3JmRJxLM3aJKsLQwe_a373gOcJGcmM_; expires=Sun, 12-Apr-2026 05:43:53 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000



======== host.docker.internal status ========
PING host.docker.internal (172.17.0.1) 56(84) bytes of data.
64 bytes from host.docker.internal (172.17.0.1): icmp_seq=1 ttl=64 time=0.052 ms

--- host.docker.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.052/0.052/0.052/0.000 ms


======== Project ownership on host ========
drwxrwxr-x 4 ruben_colpaert ruben_colpaert 4096 Mar 12 14:24 ../tryddevproject-620


======== Project ownership in container ========
drwxrwxr-x 4 ruben_colpaert ruben_colpaert 4096 Mar 12 14:24 //var/www/html


======== In-container filesystem ========
Filesystem                Type 1K-blocks      Used Available Use% Mounted on
/dev/mapper/vgubuntu-root ext4 803324232 271150208 491293896  36% /var/www/html


======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting for ddev launch to complete before deleting project
Opening in existing browser session.


Cleanup: deleting test project tryddevproject-620
 Container ddev-tryddevproject-620-db  Stopped
 Container ddev-tryddevproject-620-web  Stopped
 Container ddev-tryddevproject-620-db  Stopped
 Container ddev-tryddevproject-620-web  Stopped
 Container ddev-tryddevproject-620-db  Removed
 Container ddev-tryddevproject-620-web  Removed
 Network ddev-tryddevproject-620_default  Removed
Volume tryddevproject-620-mariadb for project tryddevproject-620 was deleted
Volume tryddevproject-620-postgres for project tryddevproject-620 was deleted
Volume tryddevproject-620_project_mutagen for project tryddevproject-620 was deleted
Project tryddevproject-620 was deleted. Your code and configuration are unchanged.

Please remove the files from this test with 'rm -r ../tryddevproject-620'

```
</details>

### Expected Behavior

When using DDEV with the Symfony quickstart, the auto-generated .env.local file includes a DATABASE_URL with charset=utf8, which is an alias for utf8mb3. This charset is insufficient for modern applications as it doesn't support the full Unicode character set, including emojis and certain special characters.

The current implementation in DDEV hardcodes charset=utf8 in the connection string (https://github.com/ddev/ddev/blob/main/pkg/ddevapp/symfony.go#L75), and this value gets overwritten during DDEV restarts, making it impossible for developers to persistently change to utf8mb4.

This creates compatibility issues with Symfony/Doctrine, which expects utf8mb4 support for proper functionality, as documented in a related Symfony bug report: https://github.com/symfony/symfony/issues/59937

The DATABASE_URL should use utf8mb4 charset by default, which is the modern standard for MySQL/MariaDB and properly supports the full range of Unicode characters.

If a user modifies the charset in the DATABASE_URL, their changes should persist across DDEV restarts.

1. **Change the default charset**: Update the hardcoded value in the Symfony integration from charset=utf8 to charset=utf8mb4.
2. **Respect configuration from MySQL settings**: Derive the charset from the .ddev/mysql/*.cnf files to ensure consistency between the actual MySQL configuration and the connection string.
3. **Preserve user modifications**: Implement a mechanism to detect and preserve user modifications to the DATABASE_URL when rewriting the .env.local file.

### Actual Behavior

1. The charset for the DATABASE_URL parameter in the .env.local file is hard coded. 
2. Mysql configuration is not taken into account
3. Changes to the .env.local file are being overwritten

### Steps To Reproduce

1. Create a new project folder: `mkdir my-symfony-site && cd my-symfony-site`
2. Initialize a new DDEV project with Symfony quickstart: `ddev config --project-type=symfony --docroot=public`
3. Update database config settings in `.ddev/config.yaml` to

```
database:
    type: mysql
    version: "8.4"
```
 
4. Add a file `.ddev/mysql/character-set.cnf` with the content (probably not required, since this the default maybe?)

```
[mysqld]
collation-server = utf8mb4_unicode_ci
character-set-server = utf8mb4
```

5. Run `ddev start`
6. Observe the generated `.env.local file` contains: `DATABASE_URL="mysql://db:db@db:3306/db?sslmode=disable&charset=utf8&serverVersion=8.4"`
7. Manually change `charset=utf8` to `charset=utf8mb4` in the `.env.local` file
8. Run `ddev restart`7. Check `.env.local` again - the charset has reverted to utf8

### Anything else?

This issue affects all Symfony developers using DDEV who need to store full Unicode data, including emojis, certain special characters, and multilingual content. It creates a mismatch between what Symfony/Doctrine expects and what DDEV provides by default.

Thank you for considering these improvements to enhance the developer experience for Symfony users with DDEV.

### PR DESCRIPTION
**Pull request by RubenColpaert**
This PR uses `charset=utf8mb4` in the DATABASE_URL environment variable for Symfony projects.

## The Issue

- #7068

The DATABASE_URL should use utf8mb4 charset by default, which is the modern standard for MySQL/MariaDB and properly supports the full range of Unicode characters.

## How This PR Solves The Issue

The `.env.local` file generated by DDEV will now use the charset utf8mb4. This is in line with what Symfony/Doctrine expects.

## Manual Testing Instructions

1. Initialize a new DDEV project with Symfony quickstart: ddev config --project-type=symfony --docroot=public
2. Update database config settings in `.ddev/config.yaml` to

```
database:
    type: mysql
    version: "8.4"
```

3. Run `ddev start`
4. Observe the generated .env.local file contains: `DATABASE_URL="mysql://db:db@db:3306/db?sslmode=disable&charset=utf8mb4&serverVersion=8.4"`

## Automated Testing Overview

No tests required, since no tests existed.

## Release/Deployment Notes

No further ramifications.

### CODE REVIEW

**Comment by MatTheCat** [comment]
Do other RDBMS  support `utf8mb4` as charset?

Also `sslmode` is specific to PostgreSQL; parameters probably should be defined according to the chosen RDBMS.

**Comment by RubenColpaert** [comment]
@MatTheCat, you are probably correct. I am no expert, but the default URL for PostgreSQL [provided by Symfony](https://github.com/symfony/recipes/blob/main/doctrine/doctrine-bundle/2.9/manifest.json#L16) is indeed charset `utf8`. 

I updated the code to reflect this.

**Review by stasadev — COMMENTED** [review]
@IndraGunawan, could you please take a look?

This change looks good to me, but I didn't test the actual db connection from Symfony app.

**Comment by IndraGunawan** [comment]
I did quick check to doctrine-bundle, since v2.5.0 the bundle automatically add the ‘charset’ config based on the platform https://github.com/doctrine/DoctrineBundle/blob/2.13.x/src/ConnectionFactory.php#L130-L150

Do you want to try to remove the charset from DATABASE_URL completely to test if it solve your issue?

**Comment by RubenColpaert** [comment]
> Do you want to give it a try to remove the charset from DATABASE_URL completely to test if it solve your issue?

This seems to work perfectly. I could make a new commit to make sure the charset is not part of the DATABASE_URL variable anymore. However, I am personally not a fan of this, because it contradicts with the default settings proposed by Symfony. Especially for newer developers this might be confusing.

In any case, let me know what you prefer. If you want the charset to be removed I will create the commit.

**Comment by IndraGunawan** [comment]
I'm fine with either of those options

File: pkg/ddevapp/symfony.go [hunk 1]
```diff
@@ -46,22 +46,27 @@ func symfonyEnvDatabase(app *DdevApp, envMap map[string]string) {
 	dbPort := ""
 	dbDriver := ""
 	dbVersion := ""
+	// todo: idealy the charset takes the mysql config into account
```
Comment (IndraGunawan) [inline pkg/ddevapp/symfony.go:49]:
```suggestion
```

**Comment by rfay** [comment]
I would prefer we use what the upstream recommends.

**Review by stasadev — APPROVED** [review]
Looks good to me, thank you!

**Review by stasadev — COMMENTED** [review]
I looked at the source code again:

https://github.com/doctrine/DoctrineBundle/blob/2.13.x/src/ConnectionFactory.php#L130-L150

If we set `charset` explicitly, this part of code won't be executed:

```php
if (! isset($params['defaultTableOptions']['collation'])) {
    $params['defaultTableOptions']['collation'] = 'utf8mb4_unicode_ci';
}
```

Maybe auto-selection for `charset` in this case is more preferable?

**Comment by stasadev** [comment]
I can't find any info about collation in `DATABASE_URL` variable. (Ignore my previous comment.)

The docs have `charset` only for PostgreSQL (but not for MySQL or MariaDB) here:

https://symfony.com/doc/current/doctrine.html#configuring-the-database

And I see `charset` for all databases here:

https://symfony.com/doc/6.4/the-fast-track/en/8-doctrine.html#changing-the-default-database-url-value-in-env

---

In the end, let's get this change merged. Better say that we use `utf8mb4` or `utf8` instead of saying nothing.

**Review by rfay — COMMENTED** [review]
OK with me, thanks!
