### PR TITLE
fix: prevent various Mutagen conflicts between daemons when changing versions or global directory, fixes #6234

### LINKED ISSUE #6234: Critical global configuration misbehavior: Accidental switching between ~/.ddev and ~/.config/ddev
### Expected Behavior

The default directory should be ~/.ddev in the absence of XDG_CONFIG_HOME

On WSL2/Linux:

With mutagen enabled in the project, 

If I remove all config, `rm -r ~/.ddev ~/.config/ddev` and then `ddev start`

* Global config is created in ~/.ddev
* However, an empty ~/.config/ddev is also created

If I then `ddev stop`

* The various things in ~/.config/ddev are populated
* ~/.config/ddev becomes the global config dir

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #6234 

With our new ability to change the global configuration directory from `~/.ddev` to other places come new risks for mutagen. 

(Removed): Mutagen now keeps its directory in `<globaldir>/.mdd` instead of `<home>/.ddev_mutagen_data_directory`. 

There's a risk in changing that mutagen could continue using an obsolete mutagen session or accidentally use a docker volume that did not match.

## How This PR Solves The Issue

* When computing the mutagen hash for uniqueness, include not only the `mutagen.yml` contents but also the location of the `mutagen.yml` and the global configuration location.
* Revert to using ~/.ddev_mutagen_data_directory to resolve risks of upgrades and environment variable changes (XDG_CONFIG_HOME)

## Manual Testing Instructions

Still working on explicit instructions that can demonstrate the underlying problem.

## Automated Testing Overview

I think the existing tests probably already do enough.

### CODE REVIEW

File: pkg/globalconfig/global_config.go [hunk 1]
```diff
@@ -597,15 +597,23 @@ func GetGlobalDdevDir() string {
...
 	if xdgConfigHomeDir != "" {
 		return filepath.Join(xdgConfigHomeDir, "ddev")
 	}
-	// If Linux and ~/.config/ddev exists, use it,
+	// If Linux and ~/.ddev doesn't exist and
+	// ~/.config/ddev exists, use it,
 	// we don't create this directory.
-	if runtime.GOOS == "linux" {
+	_, userHomeDotDdevErr := os.Stat(userHomeDotDdev)
+	if runtime.GOOS == "linux" && userHomeDotDdevErr != nil {
```
Comment (stasadev) [inline pkg/globalconfig/global_config.go:616]:
```suggestion
	if runtime.GOOS == "linux" && os.IsNotExist(userHomeDotDdevErr) {
```

File: pkg/globalconfig/global_config.go [hunk 2]
```diff
@@ -616,10 +624,7 @@ func GetGlobalDdevDirLocation() string {
 	}
 	// Otherwise, use ~/.ddev
 	// It will be created if it doesn't exist.
-	userHome, err := os.UserHomeDir()
-	if err != nil {
-		logrus.Fatal("Could not get home directory for current user. Is it set?")
-	}
+
 	return filepath.Join(userHome, ".ddev")
```
Comment (stasadev) [inline pkg/globalconfig/global_config.go:628]:
```suggestion
	return userHomeDotDdev
```

**Review by stasadev — CHANGES_REQUESTED** [review]

**Review by stasadev — CHANGES_REQUESTED** [review]
I can't make a suggestion for this line, but we can check for directory with:

```diff
-if _, err := os.Stat(linuxDir); err == nil {
+if stat, err := os.Stat(linuxDir); err == nil && stat.IsDir() {
```

**Comment by rfay** [comment]
@stasadev please take a very skeptical look at this. It over-does a couple of things, and it probably actually changes your intent for default global config location on Linux. Now it does XDG_CONFIG_HOME if set, then ~/.ddev if exists, then ~/.config/ddev if exists, and that should be the same on all platforms. AFAICT the test failures are upstream ones at this point, I'm still working on those, but I think this can go in when you and I have looked at it again.

**Review by stasadev — APPROVED** [review]
I checked for active Mutagen processes and confirmed that they stop after running the new version of DDEV.

There is also an edge case where people decide to use `XDG_CONFIG_HOME`, run `ddev start`, and then set it to a different location or unset it, and leave the old Mutagen running.
But I don't think there is anything we can do about that (since we have no way of knowing the old value for `XDG_CONFIG_HOME`).

Thank you, I think this PR will smooth things over for the Mutagen.

**Comment by rfay** [comment]
This one was intended to go in before the other ones and somehow I lost track of it while working on those :)

**Comment by rfay** [comment]
I refactored this AGAIN to detect when the MUTAGEN_DATA_DIRECTORY has changed and to use `mutagen daemon stop` per @xenoscopic's suggestion in https://github.com/ddev/ddev/issues/6234#issuecomment-2135929437 - instead of pausing sessions when it has. Added global config for last_mutagen_data_directory.

File: pkg/ddevapp/mutagen.go [hunk 3]
```diff
@@ -94,6 +94,27 @@ func PauseMutagenSync(app *DdevApp) error {
...
+func StopOldMutagenDaemons() {
+	ourMutagenDataDirectory := globalconfig.GetMutagenDataDirectory()
+	util.Debug("Attempting to terminate any mutagen daemons from other versions of DDEV. Current MUTAGEN_DATA_DIRECTORY=%s", ourMutagenDataDirectory)
+
+	userHome, _ := os.UserHomeDir()
+	allKnownMutagenDataDirectories := []string{
+		filepath.Join(userHome, ".ddev_mutagen_data_directory"), // through v1.23.1
+		filepath.Join(userHome, ".ddev", ".mdd"),                // default current
+		filepath.Join(userHome, ".config", "ddev", ".mdd"),
+	}
```
Comment (stasadev) [inline pkg/ddevapp/mutagen.go:109]: If we allow `MUTAGEN_DATA_DIRECTORY` to be changed from the env variable, and that value is saved in the DDEV global configuration, perhaps we should add it to this list:

```go
if globalconfig.DdevGlobalConfig.LastMutagenDataDirectory != "" && !slices.Contains(allKnownMutagenDataDirectories, globalconfig.DdevGlobalConfig.LastMutagenDataDirectory) {
	allKnownMutagenDataDirectories = append(allKnownMutagenDataDirectories, globalconfig.DdevGlobalConfig.LastMutagenDataDirectory)
}
```

This will cover the case when someone adds a custom `MUTAGEN_DATA_DIRECTORY`, but then changes it, or unsets it:
```
export DDEV_DEBUG=true
export MUTAGEN_DATA_DIRECTORY=~/.ddev_mutagen2
ddev start
# if we don't check for LastMutagenDataDirectory, mutagen daemon in ~/.ddev_mutagen2 won't be stopped
unset MUTAGEN_DATA_DIRECTORY
ddev start
```

File: pkg/testcommon/testcommon.go [hunk 4]
```diff
@@ -260,12 +260,14 @@ func CopyGlobalDdevDir(t *testing.T) string {
 		require.NoError(t, err)
 	}
 	// Reset $MUTAGEN_DATA_DIRECTORY
-	err = os.Unsetenv("MUTAGEN_DATA_DIRECTORY")
-	require.NoError(t, err)
+	_ = os.Unsetenv("MUTAGEN_DATA_DIRECTORY")
+	// globalconfig.GetMutagenDataDirectory gets new version of MUTAGEH_DATA_DIRECTORY
```
Comment (stasadev) [inline pkg/testcommon/testcommon.go:264]:
```suggestion
	// globalconfig.GetMutagenDataDirectory gets new version of MUTAGEN_DATA_DIRECTORY
```

**Review by stasadev — CHANGES_REQUESTED** [review]

File: pkg/ddevapp/mutagen.go (hunk 3 above)
Comment (rfay) [reply pkg/ddevapp/mutagen.go:109]: I don't think we ever allow MUTAGEN_DATA_DIRECTORY to be set in the user's environment do we? We force it to the configuration determined by the code.

Comment (stasadev) [reply pkg/ddevapp/mutagen.go:109]: I think this was an unintentional change from me in #5813, but `GetMutagenDataDirectory()` now reads `MUTAGEN_DATA_DIRECTORY` env before setting the directory.

Comment (rfay) [reply pkg/ddevapp/mutagen.go:109]: But we *set* MUTAGEN_DATA_DIRECTORY in the init() in a.go.
https://github.com/ddev/ddev/blob/b3f7cf6df550f6b6d2cedaca9d64c98521ec2fcd/cmd/ddev/cmd/a.go#L17

Comment (rfay) [reply pkg/ddevapp/mutagen.go:109]: I see. I'm going to have to take another look at that. Thanks for pointing that out.

Comment (stasadev) [reply pkg/ddevapp/mutagen.go:109]: Oh, this was added from the start:

- #4109

https://github.com/ddev/ddev/blob/b3f7cf6df550f6b6d2cedaca9d64c98521ec2fcd/pkg/globalconfig/global_config.go#L143-L151

Some may rely on using a custom `MUTAGEN_DATA_DIRECTORY` even if this is not documented in our docs.

Comment (rfay) [reply pkg/ddevapp/mutagen.go:109]: I don't think it's likely that people are setting this, but I sure appreciate you pointing this out. 

It's quite awkward for mutagen not to have a command-line arg instead of env var. I'll open an issue about that.

Comment (rfay) [reply pkg/ddevapp/mutagen.go:109]: * https://github.com/mutagen-io/mutagen/issues/499

**Comment by rfay** [comment]
I have tested this:
* macOS with mutagen
* Gitpod without mutagen
* Ubuntu without mutagen

I'll still try to test Ubuntu with mutagen.

@stasadev please make sure I didn't break the docs. At one point I did. It's complicated how it works slightly differently on Linux.

**Review by stasadev — COMMENTED** [review]
I see that we cannot prevent all edge cases with Mutagen. No matter how hard we try, there is a way to break it.

Of course, there is a chance that you might break your project files while playing around with it. I don't mind if you decide to use `~/.ddev_mutagen_data_directory` again if this change might be too disruptive.

**Comment by rfay** [comment]
The worst-case scenario is caused by the fact that we delete/empty the docker volume when we don't have a matching mutagen sync. It's always possible that that has been a bad idea.  It sure has worked well to this point.

**Comment by stasadev** [comment]
> The worst-case scenario is caused by the fact that we delete/empty the docker volume when we don't have a matching mutagen sync.

What if we name the volume based on the `MUTAGEN_DATA_DIRECTORY`?

https://github.com/ddev/ddev/blob/e0b5fb9d3cbf69709d9494c395ad4c25e82c7bc8/pkg/ddevapp/mutagen.go#L614-L617

We can calculate `sha1` of the `MUTAGEN_DATA_DIRECTORY` path, get first 5 symbols, add it to the volume name. In this case we will have different volumes.

**Comment by rfay** [comment]
I like the idea. It abandons an old docker volume, but that's OK.

**Comment by rfay** [comment]
It was such a good idea! But my brain was off-kilter. The mutagen daemon sync session syncs between filesystem on the host and the *container*'s /var/www/html. So the more of these we have going, the more trouble we have. 

Here's the situation on my computer right now:

<details><summary>MUTAGEN_DATA_DIRECTORY=/Users/rfay/tmp/dd1/ddev/.mdd</summary>
```
$ export MUTAGEN_DATA_DIRECTORY=/Users/rfay/tmp/dd1/ddev/.mdd; ~/.ddev/bin/mutagen sync list
--------------------------------------------------------------------------------
Name: d10
Identifier: sync_X4NOdoqOMTlIgEMo6lpDn9TK06jtsRBMBPhgqxRCRtW
Alpha:
	URL: /Users/rfay/workspace/d10
	Connected: Yes
	Synchronizable contents:
		7040 directories
		27066 files (136 MB)
		4 symbolic links
Beta:
	URL: docker://ddev-d10-web/var/www/html
		DOCKER_HOST=unix:///Users/rfay/.orbstack/run/docker.sock
	Connected: Yes
	Synchronizable contents:
		7040 directories
		27066 files (136 MB)
		4 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
```
</details>

<details><summary>export MUTAGEN_DATA_DIRECTORY=/Users/rfay/.ddev/.mdd; ~/.ddev/bin/mutagen sync list</summary>
```
$ export MUTAGEN_DATA_DIRECTORY=/Users/rfay/.ddev/.mdd; ~/.ddev/bin/mutagen sync list
--------------------------------------------------------------------------------
Name: d10
Identifier: sync_xT9dQybWgGvLks1FxjkrXtUhyQDyaK1AlgW6mJyQ4Bf
Alpha:
	URL: /Users/rfay/workspace/d10
	Connected: Yes
	Synchronizable contents:
		7040 directories
		27066 files (136 MB)
		4 symbolic links
Beta:
	URL: docker://ddev-d10-web/var/www/html
		DOCKER_HOST=unix:///Users/rfay/.orbstack/run/docker.sock
	Connected: Yes
	Synchronizable contents:
		7040 directories
		27066 files (136 MB)
		4 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
```
</details>

Now both of these are synchonizing from the same alpha (host) to the same beta (here the docker container) at docker://ddev-d10-web/var/www/html - both fighting away!

With this situation I was able to get the host-side code deleted nearly every time :) I happened to have GoLand set up with a debug config that had XDG_CONFIG_HOME=~/tmp/dd1 and an iterm terminal that had XDG_CONFIG_HOME unset (so using ~/.ddev)

Every time (almost?) I do the start in the debugger it deletes everything. And if I kill the debug session... it leaves yet another mutagen session running, synchronizing to the same place. I had 8 of them :)

**Comment by rfay** [comment]
Oh so sad. Latest commits 
* Revert (previously unpushed) GetMutagenVolumeName() "improvements", which were pretty fancy but offered no value in the end. And they caused a lot of calls to `docker context`
* Revert use of MUTAGEN_DATA_DIRECTORY being in the global ddev dir + .mdd. It seemed impossible to sort out the risks with this.

**Comment by stasadev** [comment]
I prepared a revert patch for the docs:

```
curl https://github.com/ddev/ddev/commit/d3b8ee8ca59875ac13102337b261e1f4d4b13079.patch -o mutagen.patch
git apply mutagen.patch
```

**Comment by rfay** [comment]
Thanks so much for that. I'll apply that after we see how the tests do.

(It would probably have been easier and easier to review to do a PR against this PR)

**Comment by rfay** [comment]
I think this is ready to go. Or I'll die. I'm pretty sure that we've removed most of the risk by going back to the traditional MUTAGEN_DATA_DIRECTORY.

Anyway, it's important to get it in and get experience with it. I think it will do fine.
