### PR TITLE
fix: mount OpenSSH certificate for `auth ssh`, fixes #6832

### LINKED ISSUE #6832: auth ssh regression when using certificates with keys (v1.24.0-v1.24.1)
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```


======== Output file will be in /var/folders/0_/q7f3rmwd39377gqlr6_2c8bw1_wxrg/T/ddev-debug-test.txt ========


======== Existing project config ========
ddev installation alternate locations:
/usr/local/bin/ddev

These config files were loaded for project rotrou: [/Users/amg32/development/lst-sites/dsites/rotrou/.ddev/config.yaml]
name: rotrou
type: drupal10
docroot: web
php_version: 8.3
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.23.5
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.5}
project_tld: localdev.libraries.psu.edu
use_dns_when_possible: true
composer_version: 2
nodejs_version: 20
default_container_timeout: 600


======== existing project customizations ========
.ddev/docker-compose.network-mtu.yaml
.ddev/nginx_full/nginx-site.conf
.ddev/.env.web


======== installed DDEV add-ons ========
No registered add-ons were found.


======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /Users/amg32/development/lst-sites/dsites/rotrou
#ddev-generated
unmodified #ddev-generated found in .ddev/mutagen/mutagen.yml


======== Creating dummy project named tryddevproject-14238 in ../tryddevproject-14238 ========
Creating a new DDEV project config in the current directory (/Users/amg32/development/lst-sites/dsites/tryddevproject-14238)
Once completed, your configuration will be written to /Users/amg32/development/lst-sites/dsites/tryddevproject-14238/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-14238' with docroot 'web' at '/Users/amg32/development/lst-sites/dsites/tryddevproject-14238/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.


======== OS Information ========
Darwin L5-LST-AMG32 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:00:32 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6030 arm64
ProductName:		macOS
ProductVersion:		15.1.1
BuildVersion:		24B91


======== User information ========
uid=44988175(amg32) gid=357253257 groups=357253257,12(everyone),62(netaccounts),701(com.apple.sharepoint.group.1),703(com.apple.sharepoint.group.3),702(com.apple.sharepoint.group.2),704(com.apple.sharepoint.group.4)


======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.23.5                                  
 architecture     arm64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.5 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.5              
 docker           27.3.1                                   
 docker-api       1.47                                     
 docker-compose   v2.29.7                                  
 docker-platform  orbstack                                 
 global-ddev-dir  /Users/amg32/.ddev                       
 mutagen          0.17.2                                   
 os               darwin                                   
 router           ddev/ddev-traefik-router:v1.23.5         
 web              ddev/ddev-webserver:v1.23.5              



======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 


======== DDEV global info ========
developer-mode=false
disable-http2=false
fail-on-hook-fail=false
instrumentation-opt-in=true
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.23.5
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/Users/amg32/Library/Application Support/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=mutagen
project-tld=ddev.site
required-docker-compose-version=v2.29.7
router=traefik
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=


======== DOCKER provider info ========
docker client location: lrwxr-xr-x@ 1 amg32  admin  34 Sep 28 21:48 /opt/homebrew/bin/docker -> ../Cellar/docker/27.3.1/bin/docker

docker client alternate locations:
/opt/homebrew/bin/docker
/Users/amg32/.orbstack/bin/docker

Docker provider: orbstack
docker version: 
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.23.1
 Git commit:        ce1223035a
 Built:             Fri Sep 20 11:01:47 2024
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:39:57 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v2.0.0
  GitCommit:        207ad711eabd375a01713109a8a197d197ff6542
 runc:
  Version:          1.2.2
  GitCommit:        7cb363254b69e10320360b63fb73e0ffb5da7bf2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

DOCKER_DEFAULT_PLATFORM=notset
Version: 1.9.0 (1090000)
Commit: fa066983fe619a7cecfd01801b08681fae797750 (v1.9.0)
Docker platform: orbstack
Using Docker context: default (unix:///Users/amg32/.orbstack/run/docker.sock)
docker-compose: v2.29.7
Using DOCKER_HOST=unix:///Users/amg32/.orbstack/run/docker.sock
Docker version: 27.3.1
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:Filesystem                Size      Used Available Use% Mounted on
overlay                 760.8G     47.6G    713.1G   6% /


======== Existing docker containers ========
CONTAINER ID   IMAGE                           COMMAND                  CREATED      STATUS                  PORTS     NAMES
b68474d1c085   4ff492daa194                    "/bin/bash"              6 days ago   Exited (0) 6 days ago             relaxed_noether
3e7b46765e40   moby/buildkit:buildx-stable-1   "buildkitd --allow-i…"   6 days ago   Up 9 hours                        buildx_buildkit_mybuilder0


======== mkcert information ========
/opt/homebrew/bin/mkcert
/usr/local/bin/mkcert
/Users/amg32/Library/Application Support/mkcert
total 16
-r--------@ 1 amg32  357253257  2484 Nov 15 10:51 rootCA-key.pem
-rw-r--r--@ 1 amg32  357253257  1704 Nov 15 10:51 rootCA.pem


======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.224 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.224/0.224/0.224/0.000 ms


======== ddev debug rebuild ========
Rebuilding project images...
Rebuilding project tryddevproject-14238 with `/Users/amg32/.ddev/bin/docker-compose -f /Users/amg32/development/lst-sites/dsites/tryddevproject-14238/.ddev/.ddev-docker-compose-full.yaml --progress plain build web --no-cache`
#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.42kB done
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/ddev/ddev-webserver:v1.23.5
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web 1/8] FROM docker.io/ddev/ddev-webserver:v1.23.5
#4 CACHED

#5 [web 2/8] RUN (groupadd --gid 357253257 "amg32" || groupadd "amg32" || true) && (useradd  -l -m -s "/bin/bash" --gid "amg32" --comment '' --uid 44988175 "amg32" || useradd  -l -m -s "/bin/bash" --gid "amg32" --comment '' "amg32" || useradd  -l -m -s "/bin/bash" --gid "357253257" --comment '' "amg32" || useradd -l -m -s "/bin/bash" --comment '' amg32 )
#5 0.094 useradd warning: amg32's uid 44988175 outside of the UID_MIN 1000 and UID_MAX 60000 range.
#5 DONE 0.2s

#6 [web 3/8] RUN mkdir -p /home/amg32 && chown amg32 /home/amg32 && chmod 600 /home/amg32/.pgpass
#6 DONE 0.1s

#7 [web 4/8] RUN mariadb-client-install.sh || true
#7 0.087 This script is not intended to run with mariadb:10.11
#7 DONE 0.1s

#8 [web 5/8] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || log-stderr.sh composer self-update --2 || true
#8 0.204 Storing "stable" as default update channel for the next self-update run.
#8 15.23 A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
#8 15.43 The following exception probably indicates you have misconfigured DNS resolver(s)
#8 15.44 
#8 15.44 In CurlDownloader.php line 371:
#8 15.44                                                                                
#8 15.44   curl error 28 while downloading https://getcomposer.org/versions: Resolving  
#8 15.44    timed out after 10000 milliseconds                                          
#8 15.44                                                                                
#8 15.44 
#8 15.44 self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--2.2] [--set-channel-only] [--] [<version>]
#8 15.44 
#8 30.57 A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
#8 30.78 The following exception probably indicates you have misconfigured DNS resolver(s)
#8 30.78 
#8 30.80 In CurlDownloader.php line 371:
#8 30.80                                                                                
#8 30.80   curl error 28 while downloading https://getcomposer.org/versions: Resolving  
#8 30.80    timed out after 10003 milliseconds                                          
#8 30.80                                                                                
#8 30.80 
#8 30.80 self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--2.2] [--set-channel-only] [--] [<version>]
#8 30.80 
#8 45.91 A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
#8 46.11 The following exception probably indicates you have misconfigured DNS resolver(s)
#8 46.11 
#8 46.12 In CurlDownloader.php line 371:
#8 46.13                                                                                
#8 46.13   curl error 28 while downloading https://getcomposer.org/versions: Resolving  
#8 46.13    timed out after 10002 milliseconds                                          
#8 46.13                                                                                
#8 46.13 
#8 46.13 self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--2.2] [--set-channel-only] [--] [<version>]
#8 46.13 
#8 61.25 A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
#8 61.44 The following exception probably indicates you have misconfigured DNS resolver(s)
#8 61.44 
#8 61.46 In CurlDownloader.php line 371:
#8 61.46                                                                                
#8 61.46   curl error 28 while downloading https://getcomposer.org/versions: Resolving  
#8 61.46    timed out after 10004 milliseconds                                          
#8 61.46                                                                                
#8 61.46 
#8 61.46 self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--2.2] [--set-channel-only] [--] [<version>]
#8 61.46 
#8 DONE 61.5s

#9 [web 6/8] RUN apt-get update
#9 0.990 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#9 1.544 Get:2 http://nginx.org/packages/debian bookworm InRelease [2869 B]
#9 1.592 Get:3 https://packages.sury.org/php bookworm InRelease [7551 B]
#9 1.646 Get:4 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#9 1.692 Get:5 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm InRelease [3675 B]
#9 1.702 Get:6 https://packages.sury.org/php bookworm/main arm64 Packages [249 kB]
#9 1.768 Get:7 http://nginx.org/packages/debian bookworm/nginx arm64 Packages [15.3 kB]
#9 1.811 Get:8 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#9 1.863 Get:9 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm InRelease [3681 B]
#9 1.961 Get:10 http://deb.debian.org/debian bookworm/main arm64 Packages [8688 kB]
#9 2.006 Get:11 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [129 kB]
#9 2.036 Get:13 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [4422 B]
#9 2.200 Get:14 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm/main arm64 Packages [4355 B]
#9 2.274 Get:15 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm/main arm64 Packages [3336 B]
#9 2.384 Get:16 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main arm64 Packages [7918 B]
#9 2.479 Get:17 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main arm64 Packages [344 kB]
#9 2.768 Get:12 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease [4625 B]
#9 3.219 Get:18 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main arm64 Packages [34.5 kB]
#9 3.565 Get:19 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main amd64 Packages [41.2 kB]
#9 5.540 Get:20 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [8844 B]
#9 5.602 Get:21 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [213 kB]
#9 6.137 Fetched 10.0 MB in 6s (1668 kB/s)
#9 6.137 Reading package lists...
#9 DONE 6.4s

#10 [web 7/8] RUN curl -I https://www.google.com
#10 0.073   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#10 0.073                                  Dload  Upload   Total   Spent    Left  Speed
#10 0.073 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
#10 15.28 HTTP/2 200 
#10 15.28 content-type: text/html; charset=ISO-8859-1
#10 15.28 content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-SGsYzSHbUUan5W7zmP-Ibw' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
#10 15.28 accept-ch: Sec-CH-Prefers-Color-Scheme
#10 15.28 p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
#10 15.28 date: Tue, 10 Dec 2024 23:51:00 GMT
#10 15.28 server: gws
#10 15.28 x-xss-protection: 0
#10 15.28 x-frame-options: SAMEORIGIN
#10 15.28 expires: Tue, 10 Dec 2024 23:51:00 GMT
#10 15.28 cache-control: private
#10 15.28 set-cookie: AEC=AZ6Zc-WJSw3q_-BY4aiNlBxpVNKPtlkSZub-JVrmZsTM0KyNIaAAwNtcPw; expires=Sun, 08-Jun-2025 23:51:00 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#10 15.28 set-cookie: NID=520=S5vKpEFc6XCjKUsbY1vn6ppQnRScYy66BYRSqmwFlT1feD-1jGa9WDab2c-pgtBspM2v8C6GlDOOBqQuLYhAlNxmx-KEnss3DIxGcTS5OeeY-5QOYym4TsuPg81EtS1E2q4KtuQXlJnc0G5AVnIxPx8KJERN9oggWI7_2aEXKH5tCIEJQRV_OQiMaIjpLWj9P-OHdQ; expires=Wed, 11-Jun-2025 23:51:00 GMT; path=/; domain=.google.com; HttpOnly
#10 15.28 
#10 DONE 15.3s

#11 [web 8/8] RUN chmod 777 /run/php /var/log
#11 DONE 0.1s

#12 [web] exporting to image
#12 exporting layers 0.1s done
#12 writing image sha256:a1a7f10770b1c3e4cfcae8f37456aaa0b9743bfde69085b0d33de8f52fe46522 done
#12 naming to docker.io/ddev/ddev-webserver:v1.23.5-tryddevproject-14238-built done
#12 DONE 0.1s

#13 [web] resolving provenance for metadata file
#13 DONE 0.0s
Rebuilt Docker cache for project tryddevproject-14238 in 1m24s
Network ddev_default created
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
v1.23.5: Pulling from ddev/ddev-dbserver-mariadb-10.11
a186900671ab: Pulling fs layer
6b63ab2d2913: Pulling fs layer
64d62bd3ce49: Pulling fs layer
92ac870fb59b: Pulling fs layer
1cdf1dbac30e: Pulling fs layer
917ed003eab9: Pulling fs layer
fc7383346da0: Pulling fs layer
ba200ef8b472: Pulling fs layer
4f4fb700ef54: Pulling fs layer
4d87a0f16e23: Pulling fs layer
e74cd5ad1f85: Pulling fs layer
cd3104bd790b: Pulling fs layer
6f5cf99eed63: Pulling fs layer
f8c6804254ab: Pulling fs layer
68b76d0d5454: Pulling fs layer
c286f86a4947: Pulling fs layer
349fbe41cf45: Pulling fs layer
b3b294fe7aac: Pulling fs layer
6cc14faf3776: Pulling fs layer
5055a80fe060: Pulling fs layer
29c5f5f81a7e: Pulling fs layer
45be9148ba7f: Pulling fs layer
733d59aa0fbc: Pulling fs layer
92ac870fb59b: Waiting
1cdf1dbac30e: Waiting
cd3104bd790b: Waiting
6f5cf99eed63: Waiting
f8c6804254ab: Waiting
917ed003eab9: Waiting
fc7383346da0: Waiting
c286f86a4947: Waiting
68b76d0d5454: Waiting
ba200ef8b472: Waiting
349fbe41cf45: Waiting
b3b294fe7aac: Waiting
6cc14faf3776: Waiting
5055a80fe060: Waiting
29c5f5f81a7e: Waiting
45be9148ba7f: Waiting
4d87a0f16e23: Waiting
4f4fb700ef54: Waiting
e74cd5ad1f85: Waiting
733d59aa0fbc: Waiting
1ad296b7a879: Pulling fs layer
1ad296b7a879: Waiting
6b63ab2d2913: Verifying Checksum
6b63ab2d2913: Download complete
64d62bd3ce49: Verifying Checksum
64d62bd3ce49: Download complete
a186900671ab: Download complete
a186900671ab: Pull complete
6b63ab2d2913: Pull complete
64d62bd3ce49: Pull complete
92ac870fb59b: Verifying Checksum
92ac870fb59b: Download complete
1cdf1dbac30e: Verifying Checksum
1cdf1dbac30e: Download complete
92ac870fb59b: Pull complete
1cdf1dbac30e: Pull complete
917ed003eab9: Verifying Checksum
917ed003eab9: Download complete
917ed003eab9: Pull complete
ba200ef8b472: Verifying Checksum
ba200ef8b472: Download complete
fc7383346da0: Verifying Checksum
fc7383346da0: Download complete
fc7383346da0: Pull complete
ba200ef8b472: Pull complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
4d87a0f16e23: Verifying Checksum
4d87a0f16e23: Download complete
4f4fb700ef54: Pull complete
4d87a0f16e23: Pull complete
e74cd5ad1f85: Verifying Checksum
e74cd5ad1f85: Download complete
e74cd5ad1f85: Pull complete
cd3104bd790b: Verifying Checksum
cd3104bd790b: Download complete
6f5cf99eed63: Verifying Checksum
6f5cf99eed63: Download complete
f8c6804254ab: Verifying Checksum
f8c6804254ab: Download complete
cd3104bd790b: Pull complete
6f5cf99eed63: Pull complete
f8c6804254ab: Pull complete
c286f86a4947: Verifying Checksum
c286f86a4947: Download complete
68b76d0d5454: Verifying Checksum
68b76d0d5454: Download complete
68b76d0d5454: Pull complete
c286f86a4947: Pull complete
349fbe41cf45: Verifying Checksum
349fbe41cf45: Download complete
349fbe41cf45: Pull complete
6cc14faf3776: Download complete
5055a80fe060: Verifying Checksum
5055a80fe060: Download complete
b3b294fe7aac: Verifying Checksum
b3b294fe7aac: Download complete
b3b294fe7aac: Pull complete
6cc14faf3776: Pull complete
5055a80fe060: Pull complete
733d59aa0fbc: Download complete
45be9148ba7f: Verifying Checksum
45be9148ba7f: Download complete
29c5f5f81a7e: Verifying Checksum
29c5f5f81a7e: Download complete
29c5f5f81a7e: Pull complete
45be9148ba7f: Pull complete
733d59aa0fbc: Pull complete
1ad296b7a879: Verifying Checksum
1ad296b7a879: Download complete
1ad296b7a879: Pull complete
Digest: sha256:3abedc482ad3d2ed9c1eafe750522829bfe7219c0fe1a60b3c38b9095a924e57
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.11:v1.23.5
docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.5
Building project images...
...................................................................................Project images built in 1m23s.
 Network ddev-tryddevproject-14238_default  Created
 Container ddev-tryddevproject-14238-web  Created
 Container ddev-tryddevproject-14238-db  Created
 Container ddev-tryddevproject-14238-db  Started
 Container ddev-tryddevproject-14238-web  Started
Starting Mutagen sync process...
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st tryddevproject-14238 -l'
Waiting for containers to become ready: [web db]
Warning: command 'composer self-update --2' run as 'root' failed with exit code 100:
A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
The following exception probably indicates you have misconfigured DNS resolver(s)

In CurlDownloader.php line 371:
                                                                               
  curl error 28 while downloading https://getcomposer.org/versions: Resolving  
   timed out after 10004 milliseconds                                          
                                                                               

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--2.2] [--set-channel-only] [--] [<version>]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started
Some components of the project tryddevproject-14238 were not installed properly.
The project is running anyway, but see the warnings above for details.
If offline, run 'ddev restart' once you are back online.
If online, check your connection and run 'ddev restart' later.
If this seems to be a config issue, update it accordingly.


======== Project startup ========
Starting tryddevproject-14238...
2024-12-10T18:56:54.876 GetAvailableRouterPort(): Router is healthy and running
2024-12-10T18:56:54.878 GetAvailableRouterPort(): proposedPort 80 already bound on ddev-router, accepting it
2024-12-10T18:56:54.882 GetAvailableRouterPort(): Router is healthy and running
2024-12-10T18:56:54.886 GetAvailableRouterPort(): proposedPort 443 already bound on ddev-router, accepting it
2024-12-10T18:56:54.889 GetAvailableRouterPort(): Router is healthy and running
2024-12-10T18:56:54.891 GetAvailableRouterPort(): proposedPort 8025 already bound on ddev-router, accepting it
2024-12-10T18:56:54.894 GetAvailableRouterPort(): Router is healthy and running
2024-12-10T18:56:54.897 GetAvailableRouterPort(): proposedPort 8026 already bound on ddev-router, accepting it
2024-12-10T18:56:54.949 Pulled image for ddev/ddev-webserver:v1.23.5
2024-12-10T18:56:54.95 Pulled image for busybox:stable
2024-12-10T18:56:54.951 Pulled image for ddev/ddev-utilities
2024-12-10T18:56:54.953 Pulled image for ddev/ddev-ssh-agent:v1.23.5
2024-12-10T18:56:54.954 Pulled image for ddev/ddev-traefik-router:v1.23.5
2024-12-10T18:56:55.203 GetDockerContext: contextInfo='default unix:///Users/amg32/.orbstack/run/docker.sock'
2024-12-10T18:56:55.203 Using Docker context default (unix:///Users/amg32/.orbstack/run/docker.sock)
2024-12-10T18:56:55.449 chowning /mnt/ddev-global-cache and /var/lib/mysql to 44988175
2024-12-10T18:56:55.616 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 44988175
2024-12-10T18:56:55.624 host.docker.internal='' because no other case was discovered
2024-12-10T18:56:55.627 Using automatically detected timezone: TZ=America/New_York
2024-12-10T18:56:55.699 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.23.5
2024-12-10T18:56:55.7 Pulled image for ddev/ddev-webserver:v1.23.5
2024-12-10T18:56:55.7 Pulled image for ddev/ddev-ssh-agent:v1.23.5
2024-12-10T18:56:55.701 Pulled image for ddev/ddev-traefik-router:v1.23.5
Building project images...
2024-12-10T18:56:55.702 Executing docker-compose -f /Users/amg32/development/lst-sites/dsites/tryddevproject-14238/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.2024-12-10T18:56:56.94 Executing docker-compose -f /Users/amg32/development/lst-sites/dsites/tryddevproject-14238/.ddev/.ddev-docker-compose-full.yaml build web --progress=plain --no-cache
..................................................................................Project images built in 1m23s.
2024-12-10T18:58:19.03 Removing dangling images for the project ddev-tryddevproject-14238
Unable to delete sha256:ea22d5d7b8750cebc9348bceef184da43cde810db190f82c323cc29a2e3cd342: Error response from daemon: conflict: unable to delete ea22d5d7b875 (cannot be forced) - image is being used by running container 9ae1c2c0534d
2024-12-10T18:58:19.059 Executing docker-compose -f /Users/amg32/development/lst-sites/dsites/tryddevproject-14238/.ddev/.ddev-docker-compose-full.yaml up -d
 Container ddev-tryddevproject-14238-db  Recreate
 Container ddev-tryddevproject-14238-web  Recreate
 Container ddev-tryddevproject-14238-db  Recreated
 Container ddev-tryddevproject-14238-web  Recreated
 Container ddev-tryddevproject-14238-web  Started
 Container ddev-tryddevproject-14238-db  Started
2024-12-10T18:58:29.645 VIRTUAL_HOST=tryddevproject-14238.ddev.site for web
2024-12-10T18:58:29.645 HTTP_EXPOSE=80:80,8025:8025 for web
2024-12-10T18:58:29.645 HTTPS_EXPOSE=443:80,8026:8025 for web
2024-12-10T18:58:30.04 Copied /Users/amg32/development/lst-sites/dsites/tryddevproject-14238/.ddev/traefik:CopyIntoVolume_ktfgqpaapxlz into /mnt/v/traefik in 33.757041ms
2024-12-10T18:58:30.054 Exec chown -R 44988175 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-12-10T18:58:30.106 Copied Traefik certs in /Users/amg32/development/lst-sites/dsites/tryddevproject-14238/.ddev/traefik/certs to ddev-global-cache/traefik
Starting Mutagen sync process...
2024-12-10T18:58:30.168 Using Mutagen config file /Users/amg32/development/lst-sites/dsites/tryddevproject-14238/.ddev/mutagen/mutagen.yml
2024-12-10T18:58:30.949 Mutagen status after sync: ok
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st tryddevproject-14238 -l'
2024-12-10T18:58:30.95 Running /start.sh in ddev-webserver
Waiting for containers to become ready: [web db]
2024-12-10T18:58:33.312 Copied /Users/amg32/.ddev/commands:CopyIntoVolume_whvcsqwcislv into /mnt/v/global-commands in 46.060084ms
2024-12-10T18:58:33.326 Exec chown -R 44988175 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2024-12-10T18:58:33.453 Testing to see if /mnt/ddev_config is properly mounted
2024-12-10T18:58:33.513 Getting stderr output from 'log-stderr.sh --show'
Warning: command 'composer self-update --2' run as 'root' failed with exit code 100:
A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
The following exception probably indicates you have misconfigured DNS resolver(s)

In CurlDownloader.php line 371:
                                                                               
  curl error 28 while downloading https://getcomposer.org/versions: Resolving  
   timed out after 10002 milliseconds                                          
                                                                               

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--2.2] [--set-channel-only] [--] [<version>]
Starting ddev-router if necessary...
2024-12-10T18:58:33.875 Copied /Users/amg32/.ddev/traefik:CopyIntoVolume_tbfynsqvwifr into /mnt/v/traefik in 38.940958ms
2024-12-10T18:58:33.889 Exec chown -R 44988175 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-12-10T18:58:33.94 Copied global Traefik config in /Users/amg32/.ddev/traefik/certs to ddev-global-cache/traefik
 Container ddev-router  Running
2024-12-10T18:58:33.996 Waiting for ddev-router to become ready. docker inspect --format "{{json .State.Health }}" ddev-router
2024-12-10T18:58:34.503 ddev-router is ready
Some components of the project tryddevproject-14238 were not installed properly.
The project is running anyway, but see the warnings above for details.
If offline, run 'ddev restart' once you are back online.
If online, check your connection and run 'ddev restart' later.
If this seems to be a config issue, update it accordingly.
Successfully started tryddevproject-14238
Your project can be reached at https://tryddevproject-14238.ddev.site
See 'ddev describe' for alternate URLs.


======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 10 Dec 2024 23:58:35 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://127.0.0.1:32868 (web container http docker bind port) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 10 Dec 2024 23:58:35 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://tryddevproject-14238.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Tue, 10 Dec 2024 23:58:35 GMT
Server: nginx
Vary: Accept-Encoding



======== Full curl of http://tryddevproject-14238.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   286    0   286    0     0  58118      0 --:--:-- --:--:-- --:--:-- 71500
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/var/folders/0_/q7f3rmwd39377gqlr6_2c8bw1_wxrg/T/ddev-debug-test.txt</b><br />
file:///var/folders/0_/q7f3rmwd39377gqlr6_2c8bw1_wxrg/T/ddev-debug-test.txt<br />


======== Full curl of https://tryddevproject-14238.ddev.site (router https URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   286    0   286    0     0   2550      0 --:--:-- --:--:-- --:--:--  2553
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/var/folders/0_/q7f3rmwd39377gqlr6_2c8bw1_wxrg/T/ddev-debug-test.txt</b><br />
file:///var/folders/0_/q7f3rmwd39377gqlr6_2c8bw1_wxrg/T/ddev-debug-test.txt<br />


======== Curl google.com to check internet access and VPN ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-v_1IFj5ApeCORO64pkyYqQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Tue, 10 Dec 2024 23:58:40 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Tue, 10 Dec 2024 23:58:40 GMT
cache-control: private
set-cookie: AEC=AZ6Zc-U_VzLd7TsInFXzBRS3TqgxqMT9h68dcUGYq6kQCYTIDSvmNPRkr1U; expires=Sun, 08-Jun-2025 23:58:40 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: NID=520=CQIQtg78cUWeZU32KdDQTK3tkvfaaoKwfHykzgLXqsW0boixQfwxVfj9-rQZUuKxIr3KdtJczSVsR2Oiy7jGoRpjhItua0RzVM0kEhlb7tNxgTXOhdURLqUuqrtt1f8KwQNz9hxYt8QAB6p7uuC3LNkwl_PH8BzEq7oBpOPskdnw26W86E0T2Fo_8EsD5-O7xg4L1A; expires=Wed, 11-Jun-2025 23:58:40 GMT; path=/; domain=.google.com; HttpOnly



======== host.docker.internal status ========
PING host.docker.internal (0.250.250.254) 56(84) bytes of data.
64 bytes from host.orb.internal (0.250.250.254): icmp_seq=1 ttl=62 time=0.327 ms

--- host.docker.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.327/0.327/0.327/0.000 ms


======== Project ownership on host ========
drwxr-xr-x@ 4 amg32  357253257  128 Dec 10 18:49 ../tryddevproject-14238


======== Project ownership in container ========
drwxr-xr-x 1 amg32 amg32 16 Dec 10 18:58 //var/www/html


======== In-container filesystem ========
Filesystem     Type  1K-blocks     Used Available Use% Mounted on
/dev/vdb1      btrfs 797758532 50771936 746986596   7% /var/www


======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting for ddev launch to complete before deleting project


Cleanup: deleting test project tryddevproject-14238
 Container ddev-tryddevproject-14238-db  Stopped
 Container ddev-tryddevproject-14238-web  Stopped
 Container ddev-tryddevproject-14238-db  Stopped
 Container ddev-tryddevproject-14238-web  Stopped
 Container ddev-tryddevproject-14238-db  Removed
 Container ddev-tryddevproject-14238-web  Removed
 Network ddev-tryddevproject-14238_default  Removed
Volume tryddevproject-14238-mariadb for project tryddevproject-14238 was deleted
Volume tryddevproject-14238-postgres for project tryddevproject-14238 was deleted
Volume tryddevproject-14238_project_mutagen for project tryddevproject-14238 was deleted
Project tryddevproject-14238 was deleted. Your code and configuration are unchanged.

Please remove the files from this test with 'rm -r ../tryddevproject-14238'

```
</details>

### Expected Behavior

(From Discord: https://discord.com/channels/664580571770388500/1316160135202345073 )

```
cp ~/.ssh/id_ed25519* ~/.ddev-ssh-ln && \
ddev auth ssh -d ~/.ddev-ssh-ln
```
Should set the identities with the certificate for the key, id_ed25519. In v1.23.5, the following is output:
```
Identity added: id_ed25519 (user@machinename)
Certificate added: id_ed25519-cert.pub (authd-user@example.com-hash)
```

### Actual Behavior

With >= v1.24.0, the command `ddev auth ssh -d ~/.ddev-ssh-ln` outputs:
```
Identity added: id_ed25519 (user@machinename)
```
You can see that it does not pick up the certificate

### Steps To Reproduce

Attempt to use an identity that is in an identified directory with `ddev auth ssh -d <some/directory>`

In the directory should be something along these lines:
```
> ls -a ~/.ddev-ssh-ln
.                   ..                  id_ed25519          id_ed25519-cert.pub
```

### Anything else?

Items such as `ssh-add -l` will seem to indicate that they are the "same" with or without the certificate, inside or outside of the container. This is because the certificate must be used in conjunction with the key to complete authentication, but the key is the same exclusive of the certificate. This certificate is usually short lived in most deployments.

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #6832

## How This PR Solves The Issue

OpenSSH uses a [hardcoded convention](https://github.com/openssh/openssh-portable/blob/bbc9c18e84de29c83fa03e69290979fcca54a2b2/authfile.c#L308) for `-cert.pub`, we can mount it if it exists.

```c
if (asprintf(&file, "%s-cert.pub", filename) == -1)
```

## Manual Testing Instructions

To generate such a certificate, I used https://goteleport.com/blog/how-to-configure-ssh-certificate-based-authentication/

```
mkdir ssh-test && cd ssh-test

ssh-keygen -t rsa -b 4096 -f host_ca -C host_ca
ssh-keygen -t rsa -b 4096 -f user_ca -C user_ca
ssh-keygen -f ssh_host_rsa_key -N '' -b 4096 -t rsa
ssh-keygen -s host_ca -I host.example.com -h -n host.example.com -V +52w ssh_host_rsa_key.pub

# add the file:
$ ddev auth ssh -f ssh_host_rsa_key
Identity added: ssh_host_rsa_key (stas@dev)
Certificate added: ssh_host_rsa_key-cert.pub (host.example.com)

# repeat the same with directory:
$ ddev auth ssh -d .
Identity added: host_ca (host_ca)
Identity added: ssh_host_rsa_key (stas@dev)
Certificate added: ssh_host_rsa_key-cert.pub (host.example.com)
Identity added: user_ca (user_ca)
```

### CODE REVIEW

File: cmd/ddev/cmd/auth-ssh.go [hunk 1]
```diff
@@ -173,6 +177,28 @@ func fileIsPrivateKey(filePath string) bool {
...
+	certPath, err := filepath.EvalSymlinks(cert)
+	if err != nil {
+		util.Warning("Unable to read %s file: %v", cert, err)
+		return "", ""
+	}
+	if !fileutil.FileIsReadable(certPath) {
+		util.Warning("Unable to read %s file: file is not readable", certPath)
+		return "", ""
+	}
+	certPath = util.WindowsPathToCygwinPath(certPath)
```
Comment (rfay) [inline cmd/ddev/cmd/auth-ssh.go:197]: Wow, can't believe you got this in there too. Does `ddev auth ssh` even work on git-bash?

**Review by rfay — APPROVED** [review]
Code looks good. Manual testing worked fine. Thanks for chasing this down! We learned something!
