### PR TITLE
fix: default_container_timeout should work right, fixes #5133 again

### LINKED ISSUE #5133: default_container_timeout not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I have a rather large database that I snapshot, but when I try to restore it I get the following error:

```
Failed waiting for web/db containers to become ready: db container failed: log=, err=health check timed out after 2m0s: labels map[com.ddev.site-name:cufpt com.docker.compose.service:db] timed out without becoming healthy, status=
Container ddev-router  Running
Failed to restore snapshot cufpt_20230713113115 for project cufpt: failed to start project for RestoreSnapshot: container(s) failed to become healthy before their configured timeout or in 120 seconds. This may be just a problem with the healthcheck and not a functional problem. (health check timed out: labels map[com.ddev.site-name:cufpt] timed out without becoming healthy, status=, detail= ddev-cufpt-db:starting - more info with `docker inspect --format "{{json .State.Health }}" ddev-cufpt-db` )
```

I've override the default-container-timeout  variable as instructed:
`ddev config --default-container-timeout 250`

### Actual Behavior

I still get the error with the same 120 seconds:

`Failed to restore snapshot cufpt_20230713113115 for project cufpt: failed to start project for RestoreSnapshot: container(s) failed to become healthy before their configured timeout or in 120 seconds. This may be just a problem with the healthcheck and not a functional problem. (health check timed out: labels map[com.ddev.site-name:cufpt] timed out without becoming healthy, status=, detail= ddev-cufpt-db:starting - more info with `docker inspect --format "{{json .State.Health }}" ddev-cufpt-db` )`

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #5133 - over and over again

`default_container_timeout` hasn't had the behavior we expect, even though we've changed that behavior lots of times.

## TODO

- [x] app.GetMaxContainerWaitTime() needs to estimate a start_period if none is specified
- [x] Make TestConfigDefaultContainerTimeout more comprehensive (include 3rd party services)

## How This PR Solves The Issue

Resolve the differences between the docker-compose `timeout` and what we need, `start_period` or defaults for `start_period`

## Manual Testing Instructions

* Read [blog on this](https://ddev.com/blog/ddev-and-docker-healthchecks-technote)
* Try `ddev snapshot restore` with a larger snapshot
* Try it with different `default_container_timeout` - larger ones should result in more time for the snapshot restore
* Try `docker-compose.*.yaml` with a variety of healthcheck values, especially `start_period` There are a number of these for examples in the TestConfigDefaultContainerTimeout directory.

## Automated Testing Overview

New `TestConfigDefaultContainerTimeout`, maybe it can get me out of hell eventually. This has a ways to go yet.

### CODE REVIEW

**Comment by rfay** [comment]
Ready for review. Maybe I won't have to do this again for a few months???

File: pkg/ddevapp/ddevapp.go [hunk 1]
```diff
@@ -1594,31 +1594,52 @@ func FindNotOmittedImages(app *DdevApp) []string {
...
 					t := int(duration.Seconds())
-					if t > maxTimeout {
-						maxTimeout = t
+					if t > maxWaitTime {
+						maxWaitTime = t
+					}
+				} else { /* In this case we didn't have a specified start_period, so guess at one */
+					interval := 1
+					retries := 3
+					maxWaitTime = 15 /* Use a generic default for start_period/maxWaitTime based on 3*5 */
```
Comment (stasadev) [inline pkg/ddevapp/ddevapp.go:1622]: The comment is confusing.
I don't understand where `15` comes from, `3*5`, if `3` is retries, than what is `5` ?
Does it come from `600/120` ? (600 is the value I see in `snapshot.go`.)
In this case the comment about `start_period/maxWaitTime` should be `maxWaitTime/start_period`.

**Review by stasadev — APPROVED** [review]
Look good to me.

I just have one question about the default value for the guessed `maxWaitTime`.

File: pkg/ddevapp/ddevapp.go (hunk 1 above)
Comment (rfay) [reply pkg/ddevapp/ddevapp.go:1622]: 5 is the default `start_period`. If the `test` were to fail 3 times, it would be retried in 5 seconds, meaning 15 seconds or more. I'll see if I can add a comment there.

File: pkg/ddevapp/ddevapp.go [hunk 2]
```diff
@@ -1594,31 +1594,54 @@ func FindNotOmittedImages(app *DdevApp) []string {
...
-					if t > maxTimeout {
-						maxTimeout = t
+					if t > maxWaitTime {
+						maxWaitTime = t
+					}
+				} else { /* In this case we didn't have a specified start_period, so guess at one */
+					interval := 1
+					retries := 3
+					// Use a generic default for start_period/maxWaitTime based on
+					// `retries` (3) * default `interval` (5)
```
Comment (stasadev) [inline pkg/ddevapp/ddevapp.go:1623]: I believe it's `start_interval`, not `interval`, and let's add a reference to where it comes from.

```suggestion
					// https://docs.docker.com/reference/dockerfile/#healthcheck
					// `retries` (3) * default `start_interval` (5)
```

**Review by stasadev — APPROVED** [review]
It looks good 👍
