### PR TITLE
fix: improve `ddev describe` output for HTTP only, fixes #6661

### LINKED ISSUE #6661: `ddev describe` shows HTTPS URLs without mkcert installed
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>ddev status lists incorrect solr port</summary>

[ddev-debug-test.txt](https://github.com/user-attachments/files/17545861/ddev-debug-test.txt)

</details>

### Expected Behavior

Listing the solr admin URL with the correct port when running `ddev status`

### Actual Behavior

I found this confusing and it took me a while to find the solr admin based on the results of:

```dev status```

http://drupal-10-solr-fastly.ddev.site:8983/solr/#/login
vs
http://drupal-10-solr-fastly.ddev.site:8943/solr/#/login

```
├──────────┼──────┼───────────────────────────────────────────────────────┼────────────────────┤
│ solr     │ OK   │ https://drupal-10-solr-fastly.ddev.site:8943          │                    │
│          │      │ InDocker: solr:8983,8983                              │                    │
├──────────┼──────┼───────────────────────────────────────────────────────┼────────────────────┤
```

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #6661

## How This PR Solves The Issue

Adds check for HTTPS in several places.

## Manual Testing Instructions

1. `mkcert -uninstall`
2. `sudo mv $(which mkcert) $(which mkcert)-backup`
3. remove `mkcert_caroot` from `~/.ddev/global_config.yaml`
4. `ddev start && ddev describe`

Before:

```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Project: d11 ~/code/ddev/d11 http://d11.ddev.site                                                                    │
│ Docker platform: linux-docker                                                                                        │
│ Router: traefik                                                                                                      │
├──────────┬──────┬───────────────────────────────────────────────────────────────────────────────┬────────────────────┤
│ SERVICE  │ STAT │ URL/PORT                                                                      │ INFO               │
├──────────┼──────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ web      │ OK   │ https://d11.ddev.site                                                         │ php PHP8.3         │
│          │      │ InDocker: web:3000,443,80,8025                                                │ nginx-fpm          │
│          │      │ Host: 127.0.0.1:32792,32791                                                   │ docroot:''         │
│          │      │                                                                               │ Perf mode: none    │
│          │      │                                                                               │ NodeJS:20          │
├──────────┼──────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ db       │ OK   │ InDocker: db:3306                                                             │ mysql:8.0          │
│          │      │ Host: 127.0.0.1:32790                                                         │ User/Pass: 'db/db' │
│          │      │                                                                               │ or 'root/root'     │
├──────────┼──────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ solr     │ OK   │ https://d11.ddev.site:8943                                                    │                    │
│          │      │ InDocker: solr:8983,8983                                                      │                    │
├──────────┼──────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ Mailpit  │      │ Mailpit: https://d11.ddev.site:8026                                           │                    │
│          │      │ Launch: ddev mailpit                                                          │                    │
├──────────┼──────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ nodejs   │      │ InDocker: localhost:3000 https://d11.ddev.site:3000 http://d11.ddev.site:2999 │                    │
├──────────┼──────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ All URLs │      │ https://d11.ddev.site, https://127.0.0.1:32792,                               │                    │
│          │      │ http://d11.ddev.site, http://127.0.0.1:32791                                  │                    │
└──────────┴──────┴───────────────────────────────────────────────────────────────────────────────┴────────────────────┘
```

After:

```
┌─────────────────────────────────────────────────────────────────────────────────────┐
│ Project: d11 ~/code/ddev/d11 http://d11.ddev.site                                   │
│ Docker platform: linux-docker                                                       │
│ Router: traefik                                                                     │
├──────────┬──────┬──────────────────────────────────────────────┬────────────────────┤
│ SERVICE  │ STAT │ URL/PORT                                     │ INFO               │
├──────────┼──────┼──────────────────────────────────────────────┼────────────────────┤
│ web      │ OK   │ http://d11.ddev.site                         │ php PHP8.3         │
│          │      │ InDocker: web:3000,443,80,8025               │ nginx-fpm          │
│          │      │ Host: 127.0.0.1:32792,32791                  │ docroot:''         │
│          │      │                                              │ Perf mode: none    │
│          │      │                                              │ NodeJS:20          │
├──────────┼──────┼──────────────────────────────────────────────┼────────────────────┤
│ db       │ OK   │ InDocker: db:3306                            │ mysql:8.0          │
│          │      │ Host: 127.0.0.1:32790                        │ User/Pass: 'db/db' │
│          │      │                                              │ or 'root/root'     │
├──────────┼──────┼──────────────────────────────────────────────┼────────────────────┤
│ solr     │ OK   │ http://d11.ddev.site:8983                    │                    │
│          │      │ InDocker: solr:8983                          │                    │
├──────────┼──────┼──────────────────────────────────────────────┼────────────────────┤
│ Mailpit  │      │ Mailpit: http://d11.ddev.site:8025           │                    │
│          │      │ Launch: ddev mailpit                         │                    │
├──────────┼──────┼──────────────────────────────────────────────┼────────────────────┤
│ nodejs   │      │ http://d11.ddev.site:2999                    │                    │
│          │      │ InDocker: web:3000                           │                    │
├──────────┼──────┼──────────────────────────────────────────────┼────────────────────┤
│ All URLs │      │ http://d11.ddev.site, http://127.0.0.1:32791 │                    │
└──────────┴──────┴──────────────────────────────────────────────┴────────────────────┘
```

### CODE REVIEW

File: pkg/ddevapp/ddevapp.go [hunk 1]
```diff
@@ -306,7 +307,9 @@ func (app *DdevApp) Describe(short bool) (map[string]interface{}, error) {
 		services[shortName]["short_name"] = shortName
 		var ports []string
 		for pk := range c.Config.ExposedPorts {
-			ports = append(ports, pk.Port())
+			if !slices.Contains(ports, pk.Port()) {
+				ports = append(ports, pk.Port())
+			}
```
Comment (stasadev) [inline pkg/ddevapp/ddevapp.go:312]: I was wondering why `InDocker: solr:8983,8983`, the same port is listed twice.
That's where it comes from.
