### PR TITLE
fix: Use port 80 to get better headers for Codespaces, fixes #6102

### LINKED ISSUE #6102: Codespaces: Drupal redirects at unusual places
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

Codespaces should work fine with a Drupal10 instance

### Actual Behavior

From [Discord](https://discord.com/channels/664580571770388500/1229209241714163802/1229209241714163802)

* DDEV with Drupal 10 installs and launches OK
* Logging in or visiting "My Account" fails with a 404
* DDEV_DEBUG=true ddev launch shows trying to use port 8080 with http (and it warns about redirects: "HTTP may redirect to HTTPS in your browser")
```
$ DDEV_DEBUG=test ddev launch
HTTP may redirect to HTTPS in your browser
See https://ddev.readthedocs.io/en/stable/users/usage/commands/#launch
FULLURL http://127.0.0.1:8080
```

* Actual launch redirects to `https://fictional-space-fortnight-97rqv976p3ppjv-8080.app.github.dev/`, which works fine (and you can visit many other URLs)
* Until you visit "My Account" (/user) when logged in (or try to log in). Then it lands on `https://fictional-space-fortnight-97rqv976p3ppjv-8080.app.github.dev:8080/en/user/1` (note the appended port 8080). 
* $DDEV_PRIMARY_URL inside the container is `http://127.0.0.1:8080`

If you visit the URL provided by the ports tab for 8443, `https://fictional-space-fortnight-97rqv976p3ppjv-8443.app.github.dev/` then everything seems to work, including logging in or visiting /user when logged in.

It seems that codespaces wants us to use the 8443 port and a full URL for forwarding (for example, `https://fictional-space-fortnight-97rqv976p3ppjv-8443.app.github.dev`) not `localhost`

With DDEV v1.23.0-rc2, you can `ddev launch :8443` and everything seems to work right.

### Steps To Reproduce

Open a codespace using https://github.com/ddev/d10simple

Install using the web installer or `ddev drush si -y demo_umami --account-pass=admin`

`ddev launch`

Try logging in using user=admin pass=admin

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #6102 

Handling ports in HTTP is always a little complex, port 80 is default for http, port 443 for https. Codespaces seems to handle the Host header and X-Forwarded-Host incorrectly when it's forwarding a nonstandard (not port 80) port.

## How This PR Solves The Issue

Use port 80 by default in codespaces. This seems to do no harm. It affects only Codespaces.

## Manual Testing Instructions

* Run this PR in Codespaces
* Start a project
* Install Drupal 10
* Log in. If it works, it's fixed

### CODE REVIEW

File: pkg/ddevapp/ddevapp.go [hunk 1]
```diff
@@ -2061,6 +2061,12 @@ func (app *DdevApp) DockerEnv() {
...
 	//   config.yaml settings.
+	// Codespaces stumbles if not on a "standard" port like port 80
+	if nodeps.IsGitpod() || nodeps.IsCodespaces() {
+		if app.HostWebserverPort == "" {
+			app.HostWebserverPort = "80"
+		}
+	}
 	if nodeps.IsGitpod() || nodeps.IsCodespaces() {
 		if app.HostWebserverPort == "" {
 			app.HostWebserverPort = "8080"
```
Comment (stasadev) [inline pkg/ddevapp/ddevapp.go:2072]: I think it should have been here:

```suggestion
			if nodeps.IsCodespaces() {
				// Codespaces stumbles if not on a "standard" port like port 80
				app.HostWebserverPort = "80"
			} else {
				app.HostWebserverPort = "8080"
			}
```

File: pkg/ddevapp/ddevapp.go [hunk 2]
```diff
@@ -2061,6 +2061,12 @@ func (app *DdevApp) DockerEnv() {
 	// * provide default host-side port bindings, assuming only one project running,
 	//   as is usual on Gitpod, but if more than one project, can override with normal
 	//   config.yaml settings.
+	// Codespaces stumbles if not on a "standard" port like port 80
+	if nodeps.IsGitpod() || nodeps.IsCodespaces() {
+		if app.HostWebserverPort == "" {
+			app.HostWebserverPort = "80"
+		}
+	}
```
Comment (stasadev) [inline pkg/ddevapp/ddevapp.go:2069]:
```suggestion
```

**Review by stasadev — CHANGES_REQUESTED** [review]
I moved the condition because it broke Gitpod.
And I haven't tested Codespaces yet.

File: pkg/ddevapp/ddevapp.go [hunk 3]
```diff
@@ -2061,6 +2061,12 @@ func (app *DdevApp) DockerEnv() {
 	// * provide default host-side port bindings, assuming only one project running,
 	//   as is usual on Gitpod, but if more than one project, can override with normal
 	//   config.yaml settings.
+	// Codespaces stumbles if not on a "standard" port like port 80
+	if nodeps.IsGitpod() || nodeps.IsCodespaces() {
```
Comment (rfay) [inline pkg/ddevapp/ddevapp.go:2065]: What I intended:

```suggestion
	if nodeps.IsCodespaces() {
```

Thanks as always for looking closely.

**Comment by rfay** [comment]
Open to your suggestions, thanks for catching the copy/paste failure.

**Review by stasadev — APPROVED** [review]
Tested it with Drupal 10, login works.

It is mind-blowing how tricky the cloud can be 🤯
