### PR TITLE
fix: handle args with spaces in `ddev exec`, don't panic about invalid syntax in `exec_raw`, fixes #5865

### LINKED ISSUE #5865: ddev exec arguments … quoted strings with spaces are broken into individual arguments
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[32mRunning bash [-c /var/folders/4x/vpq_21450db60qqy73zjk7br0000gn/T/test_ddev.sh][0m
======= Existing project config =========
These config files were loaded for project v2.mytiki.life: [/Users/leevigraham/Sites/v2.mytiki.life.localhost/.ddev/config.yaml]
name: v2.mytiki.life
type: php
docroot: web
php_version: 8.1
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.22.7
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.3}
upload_dirs: [uploads ../storage/backups ../templates.v1 ../theme.v1]
project_tld: localhost
use_dns_when_possible: true
composer_version: 2
nodejs_version: 20
default_container_timeout: 120
web_extra_exposed_ports: [{node-vite 5173 5174 5173}]
======= Creating dummy project named  tryddevproject-24613 in ../tryddevproject-24613 =========
OS Information: Darwin Leevis-MacBook-Pro-MAX.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60
User information: uid=501(leevigraham) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),703(com.apple.sharepoint.group.3),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.22.7                                 
 architecture     arm64                                   
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.7 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.7             
 docker           25.0.2                                  
 docker-compose   v2.24.5                                 
 docker-platform  orbstack                                
 mutagen          0.17.2                                  
 os               darwin                                  
 router           ddev/ddev-traefik-router:v1.22.7        
 web              ddev/ddev-webserver:v1.22.7             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=mutagen
router-bind-all-interfaces=true
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.24.5
use-docker-compose-from-path=false
project-tld=ddev.site
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443
mailpit-http-port=8025
mailpit-https-port=8026
traefik-monitor-port=10999

======= DOCKER info =========
docker location: lrwxr-xr-x  1 leevigraham  admin  34 Oct 27 16:01 /opt/homebrew/bin/docker -> ../Cellar/docker/24.0.7/bin/docker
Docker Desktop Version: Docker Desktop for Mac File build Doesn'tDocker Desktop for Mac Exist, build WillDocker Desktop for Mac Create: build /Applications/Docker.app/Contents/Info.plistDocker Desktop for Mac File build Doesn'tDocker Desktop for Mac Exist, build WillDocker Desktop for Mac Create: build /Applications/Docker.app/Contents/Info.plist
docker version: 
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.3
 Git commit:        afdd53b4e3
 Built:             Thu Oct 26 07:06:42 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:35 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.7
  GitCommit:        8c087663b0233f6e6e2f4515cee61d49f14746a8
 runc:
  Version:          1.1.9
  GitCommit:        82f18fe0e44a59034f3e1f45e475fa5636e539aa
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.17.2
--------------------------------------------------------------------------------
Name: v2mytikilife
Identifier: sync_vVD7ReAuPc0QKvWVBRmf8EZNaKx1gVoUlYNIaxAslcu
Labels:
	com.ddev.config-hash: c92fc0b05873d471a76551e5a80b50e89336ff38
	com.ddev.volume-signature: Users-leevigraham-orbstack-run-1707909739
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/web/uploads
		/storage/backups
		/templates.v1
		/theme.v1
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/leevigraham/Sites/v2.mytiki.life.localhost
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
	Synchronizable contents:
		7981 directories
		65364 files (1.3 GB)
		17 symbolic links
Beta:
	URL: docker://ddev-v2.mytiki.life-web/var/www/html
		DOCKER_HOST=unix:///Users/leevigraham/.orbstack/run/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: Yes
	Synchronizable contents:
		7981 directories
		65364 files (1.3 GB)
		17 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
Name: spcc
Identifier: sync_ueBcrasfogwd9xVvBylciuuvLMz7rOwDVb12c79Ldz5
Labels:
	com.ddev.config-hash: 676ff5b8bf748f38f3f86c97cbadb087ea277625
	com.ddev.volume-signature: Users-leevigraham-orbstack-run-1707970984
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/public/uploads
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/leevigraham/Sites/spcc.localhost
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
	Synchronizable contents:
		7204 directories
		35258 files (1.6 GB)
		24 symbolic links
Beta:
	URL: docker://ddev-spcc-web/var/www/html
		DOCKER_HOST=unix:///Users/leevigraham/.orbstack/run/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: Yes
	Synchronizable contents:
		7204 directories
		35258 files (1.6 GB)
		24 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
Name: mytikilife
Identifier: sync_lc7npCDSIj5n3n2LVrfqBCuZeF0vWQjfnWjQHtByAmw
Labels:
	com.ddev.config-hash: f95e7c4dd55e2c17310a95a2aef0c7da4fc32fd0
	com.ddev.volume-signature: Users-leevigraham-orbstack-run-1708040104
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/web/uploads
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/leevigraham/Sites/mytiki.life.localhost
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: No
Beta:
	URL: docker://ddev-mytiki.life-web/var/www/html
		DOCKER_HOST=unix:///Users/leevigraham/.orbstack/run/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: [Paused]
--------------------------------------------------------------------------------
======= Docker Info =========
[32mDocker platform: orbstack[0m
[32mUsing Docker context: default (unix:///Users/leevigraham/.orbstack/run/docker.sock)[0m
[32mdocker-compose: v2.24.5[0m
[32mUsing DOCKER_HOST=unix:///Users/leevigraham/.orbstack/run/docker.sock[0m
[32mDocker version: 25.0.2[0m
[32mAble to run simple container that mounts a volume.[0m
[32mAble to use internet inside container.[0m
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 221.4G     31.9G    189.6G  14% /

 Container ddev-mytiki.life-db  Stopped
 Container ddev-mytiki.life-web  Stopped
 Container ddev-mytiki.life-db  Removed
 Container ddev-mytiki.life-web  Removed
 Container ddev-mytiki.life-meilisearch  Stopped
 Container ddev-mytiki.life-meilisearch  Removed
 Network ddev-mytikilife_default  Removed
[32mProject mytiki.life has been stopped.[0m
 Container ddev-spcc-db  Stopped
 Container ddev-spcc-web  Stopped
 Container ddev-spcc-web  Stopped
 Container ddev-spcc-db  Stopped
 Container ddev-spcc-db  Removed
 Container ddev-spcc-web  Removed
 Network ddev-spcc_default  Removed
[32mProject spcc has been stopped.[0m
 Container ddev-v2.mytiki.life-db  Stopped
 Container ddev-v2.mytiki.life-web  Stopped
 Container ddev-v2.mytiki.life-meilisearch  Stopped
 Container ddev-v2.mytiki.life-db  Stopped
 Container ddev-v2.mytiki.life-web  Stopped
 Container ddev-v2.mytiki.life-db  Removed
 Container ddev-v2.mytiki.life-web  Removed
 Container ddev-v2.mytiki.life-meilisearch  Stopped
 Container ddev-v2.mytiki.life-meilisearch  Removed
 Network ddev-v2mytikilife_default  Removed
[32mProject v2.mytiki.life has been stopped.[0m
[32mStopped Mutagen daemon[0m
Network ddev_default removed
Existing docker containers: 
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Network ddev_default created

[107;30m TIP OF THE DAY                                                              [0m
[107;30m DDEV allows you to rapidly profile the performance of your PHP code using   [0m
[107;30m xhprof with `ddev xhprof on`.                                               [0m

Starting tryddevproject-24613...
Network ddev-tryddevproject-24613_default created
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
v1.22.7: Pulling from ddev/ddev-dbserver-mariadb-10.4
bc5b5b7ccd1e: Pulling fs layer
9e0cf7962aa4: Pulling fs layer
06186067ba21: Pulling fs layer
78439c680642: Pulling fs layer
ffdd7468429b: Pulling fs layer
df7cbf30cd0c: Pulling fs layer
9535641f7a05: Pulling fs layer
7d8afb04fc5a: Pulling fs layer
4d38d384655e: Pulling fs layer
4f4fb700ef54: Pulling fs layer
1f0973353446: Pulling fs layer
797f8674b59d: Pulling fs layer
f702f6c2a6af: Pulling fs layer
6f1942c99ffc: Pulling fs layer
6793c5599f10: Pulling fs layer
633fa2cfa563: Pulling fs layer
0464cb2bae25: Pulling fs layer
5cc696f4d5c5: Pulling fs layer
e088fdf082dc: Pulling fs layer
ae72d21a0582: Pulling fs layer
7b75c5875ea0: Pulling fs layer
cf1a50f28cfc: Pulling fs layer
ac1f4c43c4a5: Pulling fs layer
607e68c5764e: Pulling fs layer
714606422904: Pulling fs layer
78439c680642: Waiting
ffdd7468429b: Waiting
df7cbf30cd0c: Waiting
9535641f7a05: Waiting
7d8afb04fc5a: Waiting
4d38d384655e: Waiting
4f4fb700ef54: Waiting
1f0973353446: Waiting
797f8674b59d: Waiting
f702f6c2a6af: Waiting
6f1942c99ffc: Waiting
6793c5599f10: Waiting
633fa2cfa563: Waiting
0464cb2bae25: Waiting
5cc696f4d5c5: Waiting
e088fdf082dc: Waiting
ae72d21a0582: Waiting
7b75c5875ea0: Waiting
cf1a50f28cfc: Waiting
ac1f4c43c4a5: Waiting
607e68c5764e: Waiting
714606422904: Waiting
9e0cf7962aa4: Verifying Checksum
9e0cf7962aa4: Download complete
78439c680642: Verifying Checksum
78439c680642: Download complete
06186067ba21: Verifying Checksum
06186067ba21: Download complete
ffdd7468429b: Verifying Checksum
ffdd7468429b: Download complete
9535641f7a05: Verifying Checksum
9535641f7a05: Download complete
bc5b5b7ccd1e: Verifying Checksum
bc5b5b7ccd1e: Download complete
7d8afb04fc5a: Verifying Checksum
7d8afb04fc5a: Download complete
bc5b5b7ccd1e: Pull complete
9e0cf7962aa4: Pull complete
4d38d384655e: Verifying Checksum
4d38d384655e: Download complete
06186067ba21: Pull complete
78439c680642: Pull complete
ffdd7468429b: Pull complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
1f0973353446: Verifying Checksum
1f0973353446: Download complete
f702f6c2a6af: Verifying Checksum
f702f6c2a6af: Download complete
6f1942c99ffc: Download complete
6793c5599f10: Verifying Checksum
6793c5599f10: Download complete
633fa2cfa563: Verifying Checksum
633fa2cfa563: Download complete
0464cb2bae25: Verifying Checksum
0464cb2bae25: Download complete
797f8674b59d: Verifying Checksum
797f8674b59d: Download complete
e088fdf082dc: Verifying Checksum
e088fdf082dc: Download complete
ae72d21a0582: Verifying Checksum
ae72d21a0582: Download complete
5cc696f4d5c5: Verifying Checksum
5cc696f4d5c5: Download complete
cf1a50f28cfc: Download complete
7b75c5875ea0: Verifying Checksum
7b75c5875ea0: Download complete
ac1f4c43c4a5: Verifying Checksum
ac1f4c43c4a5: Download complete
607e68c5764e: Verifying Checksum
607e68c5764e: Download complete
714606422904: Verifying Checksum
714606422904: Download complete
df7cbf30cd0c: Verifying Checksum
df7cbf30cd0c: Download complete
df7cbf30cd0c: Pull complete
9535641f7a05: Pull complete
7d8afb04fc5a: Pull complete
4d38d384655e: Pull complete
4f4fb700ef54: Pull complete
1f0973353446: Pull complete
797f8674b59d: Pull complete
f702f6c2a6af: Pull complete
6f1942c99ffc: Pull complete
6793c5599f10: Pull complete
633fa2cfa563: Pull complete
0464cb2bae25: Pull complete
5cc696f4d5c5: Pull complete
e088fdf082dc: Pull complete
ae72d21a0582: Pull complete
7b75c5875ea0: Pull complete
cf1a50f28cfc: Pull complete
ac1f4c43c4a5: Pull complete
607e68c5764e: Pull complete
714606422904: Pull complete
Digest: sha256:e3b3e4f0325bd7030c97058cef743bc971fbeb65b55bf3b277d8353e3801e067
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.4:v1.22.7
docker.io/ddev/ddev-dbserver-mariadb-10.4:v1.22.7
Building project images...
[32mProject images built in 1s.[0m
 Container ddev-tryddevproject-24613-web  Created
 Container ddev-tryddevproject-24613-db  Created
 Container ddev-tryddevproject-24613-db  Started
 Container ddev-tryddevproject-24613-web  Started
Starting Mutagen sync process...
[32mMutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st tryddevproject-24613 -l'[0m
Waiting for web/db containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started
Waiting for additional project containers to become ready...
All project containers are now ready.
[32mSuccessfully started tryddevproject-24613[0m
[32mProject can be reached at https://tryddevproject-24613.ddev.site https://127.0.0.1:32788[0m
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 18 Feb 2024 21:36:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-24613.ddev.site from outside:
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Sun, 18 Feb 2024 21:36:00 GMT
Server: nginx
Vary: Accept-Encoding

======== full curl of http://tryddevproject-24613.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-24613'
======== Project ownership on host:
drwxr-xr-x  4 leevigraham  staff  128 Feb 19 08:34 ../tryddevproject-24613
======== Project ownership in container:
drwxr-xr-x 1 leevigraham dialout 16 Feb 18 21:35 /var/www/html
======== In-container filesystem:
Filesystem     Type  1K-blocks     Used Available Use% Mounted on
/dev/vdb1      btrfs 232341276 33576852 198816424  15% /var/www
======== curl again of tryddevproject-24613 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-24613'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds

Please run cleanup after debugging with 'ddev debug testcleanup'

```
</details>         

### Expected Behavior

Arguments passed to CLI scripts should retain spaces.

### Actual Behavior

Arguments passed to CLI scripts are broken down into individual arguments.

### Steps To Reproduce

Create a new executable php file called `args.php` with the following contents:

```php
<?php var_dump($_SERVER['argv']);
```

Make it executable `sudo chmod +x ./args.php`

Run the script on the local machine (not ddev):

```sh
php ./args.php --option="argument with string"
```

Result:

```sh
array(2) {
  [0]=>
  string(10) "./args.php"
  [1]=>
  string(29) "--option=argument with string"
}
```

Run the script using `ddev exec`

```sh
 ddev exec php args.php --option="argument with string"
```

Result:

```sh
array(4) {
  [0]=>
  string(10) "./args.php"
  [1]=>
  string(17) "--option=argument"
  [2]=>
  string(4) "with"
  [3]=>
  string(6) "string"
}
```

Run the script using `ddev exec --raw`

```sh
 ddev exec --raw php args.php --option="argument with string"
```

Result:

```sh
array(2) {
  [0]=>
  string(8) "args.php"
  [1]=>
  string(29) "--option=argument with string"
}
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #5865
- #3603

## How This PR Solves The Issue

Uses the same technique I tried in:

- #6627

But this time I fixed the command with pipes `ddev exec "set | grep IS_DDEV_PROJECT"`

TODO:

- ~~I marked the `--raw` flag hidden. Mark it deprecated, remove it from the docs?~~
- ~~Remove `--raw` from tests~~
- ~~Check the hooks, maybe we can get rid of `exec_raw`~~

Edit: I decided not to remove the `--raw` flag, this PR simply runs `ddev exec` with *multiple* (2+) arguments, as it could be run using `ddev exec --raw`.

---

And it fixes panic for the wrong syntax on `ddev start` (this is indirectly related to `exec`, so I decided to fix it here):

```yaml
hooks:
    post-start:
        - exec:
          exec_raw: ls -la # the command should look like this [ls, la]
```

```
$ ddev start
...
panic: interface conversion: interface {} is string, not []interface {}
...
```

## Manual Testing Instructions

Using DDEV v1.24.2:
```bash
$ echo 'for i; do echo $i; done' > issue.sh

$ ddev exec bash issue.sh "string with spaces"
string
with
spaces

$ ddev exec bash issue.sh "string with spaces" --test="a b c"
string
with
spaces
--test=a
b
c

$ ddev exec 'bash issue.sh "string with spaces"'
string with spaces

$ ddev exec "set | grep IS_DDEV_PROJECT"
BASH_EXECUTION_STRING='set -eu && ( set | grep IS_DDEV_PROJECT)'
IS_DDEV_PROJECT=true

$ echo '<?php var_dump($_SERVER["argv"]);' > args.php

$ ddev exec php args.php --option="argument with string"
array(4) {
  [0]=>
  string(8) "args.php"
  [1]=>
  string(17) "--option=argument"
  [2]=>
  string(4) "with"
  [3]=>
  string(6) "string"
}
```

Using this PR:
```bash
$ echo 'for i; do echo $i; done' > issue.sh

$ ddev exec bash issue.sh "string with spaces"
string with spaces

$ ddev exec bash issue.sh "string with spaces" --test="a b c"
string with spaces
--test=a b c

$ ddev exec 'bash issue.sh "string with spaces"'
string with spaces

$ ddev exec "set | grep IS_DDEV_PROJECT"
BASH_EXECUTION_STRING='set -eu && ( set | grep IS_DDEV_PROJECT)'
IS_DDEV_PROJECT=true

$ echo '<?php var_dump($_SERVER["argv"]);' > args.php

$ ddev exec php args.php --option="argument with string"
array(2) {
  [0]=>
  string(8) "args.php"
  [1]=>
  string(29) "--option=argument with string"
}
```

Additionally check `ddev start` with this hook (it shouldn't panic):

```yaml
hooks:
    post-start:
        - exec:
          exec_raw: ls -la # the command should look like this [ls, la]
```

### CODE REVIEW

File: pkg/ddevapp/task.go [hunk 1]
```diff
@@ -164,17 +164,7 @@ func NewTask(app *DdevApp, ytask YAMLTask) Task {
...
-
-	} else if e, ok = ytask["exec"]; ok {
-		if v, ok := e.(string); ok {
-			t := ExecTask{app: app, exec: v}
-			if t.service, ok = ytask["service"].(string); !ok {
-				t.service = nodeps.WebContainer
-			}
-			return t
-		}
-		util.Warning("Invalid exec value, not executing it: %v", e)
```
Comment (stasadev) [inline pkg/ddevapp/task.go:177]: The above else-if condition at the line 145 is exactly the same, I believe this code is unreachable.

File: pkg/util/utils.go [hunk 2]
```diff
@@ -324,16 +324,21 @@ func Killall(processName string) {
...
+		for i := range v {
+			if s, ok := v[i].(string); ok {
+				raw[i] = s
+			} else {
+				return nil, fmt.Errorf("%v is not a string", v[i])
+			}
 		}
+		return raw, nil
+	default:
+		return nil, fmt.Errorf("unexpected type: %T", input)
```
Comment (stasadev) [inline pkg/util/utils.go:340]: I added a new type check here because DDEV threw panic on this:

```yaml
hooks:
    post-start:
        - exec:
          exec_raw: ls -la # the command should look like this [ls, la]
```

```
$ ddev start
...
panic: interface conversion: interface {} is string, not []interface {}
...
```

But it should show an error:
```
$ ddev start
...
Invalid exec/exec_raw value, not executing it: unexpected type: string 
Failed to start d11: unable to create task from map[exec:<nil> exec_raw:ls -la] 
```

File: cmd/ddev/cmd/exec.go [hunk 3]
```diff
@@ -49,11 +49,22 @@ ddev exec --raw -- ls -lR`,
...
 
-		// If they've chosen raw, use the actual passed values
-		if cmd.Flag("raw").Changed {
-			if useRaw, _ := cmd.Flags().GetBool("raw"); useRaw {
-				opts.RawCmd = args
+		// If they've chosen raw, use the actual passed values.
+		// If there are multiple arguments, treat them as a raw command.
+		// This avoids splitting quoted strings with spaces into separate arguments.
+		// Also, retrieve and preserve the current $PATH to ensure the environment is consistent.
+		if cmd.Flag("raw").Changed || len(args) > 1 {
```
Comment (stasadev) [inline cmd/ddev/cmd/exec.go:56]: After thinking about it, I decided that the `--raw` flag is fine and should be left here because users should be able to execute a raw command even with a single argument (`len(args) == 1`) if they want to.

File: cmd/ddev/cmd/exec_test.go [hunk 4]
```diff
@@ -99,13 +99,10 @@ func TestCmdExec(t *testing.T) {
...
 
-	_, err = exec.RunHostCommand(DdevBin, "exec", "true", "&&", "touch", "/var/www/html/TestCmdExec-touch-separate-args.txt")
+	// Complex commands with spaces should also work, even without the --raw flag
+	out, err = exec.RunHostCommand(DdevBin, "exec", "bash", "-c", "for i; do echo $i; done", "_", "string with spaces")
 	assert.NoError(err)
-
-	err = app.MutagenSyncFlush()
-	assert.NoError(err)
-
-	assert.FileExists(filepath.Join(site.Dir, "TestCmdExec-touch-separate-args.txt"))
```
Comment (stasadev) [inline cmd/ddev/cmd/exec_test.go:108]: This check for `TestCmdExec-touch-separate-args.txt` fails with new logic for `ddev exec`.

```
ddev exec true && touch /var/www/html/TestCmdExec-touch-separate-args.txt
```

In bash, this is done like this, so `touch` isn't even a part of `ddev exec`:

```
( ddev exec true ) && ( touch /var/www/html/TestCmdExec-touch-separate-args.txt )
```

But in v1.24.2 `exec.RunHostCommand`, it was executed like this:

```
ddev exec ( true && touch /var/www/html/TestCmdExec-touch-separate-args.txt )
```

I don't understand why this check even works with v1.24.2.

Anyway, in this PR it works the same way as it does in bash, it fails because there is file created.

I don't see the point in checking this condition, so I replaced it with another check.

**Comment by rfay** [comment]
Rebased to get the lima/colima fix

File: cmd/ddev/cmd/exec_test.go (hunk 4 above)
Comment (rfay) [reply cmd/ddev/cmd/exec_test.go:108]: We have a bit of a misunderstanding of this complicated stuff here. This worked fine in HEAD, and can be demonstrated and improved via:
```
	out, err = exec.RunHostCommand(DdevBin, "exec", "true", "&&", "touch", "/var/www/html/TestCmdExec-touch-separate-args.txt", "&&", "hostname")
	assert.NoError(err)
	out = strings.Trim(out, "\r\n ")
	assert.Equal(fmt.Sprintf("%s-web", site.Name), out)
```

In this situation, all of the args to RunHostCommand() are arguments, and they're not intercepted by bash on the host side because we're not using bash in RunHostCommand(). 

It's so very hard dealing with multiple bash interpretations. It's possible that we need some aspects of this test that do RunHostCommand using `bash -c` instead of just using DdevBin as the interpreter.

Comment (rfay) [reply cmd/ddev/cmd/exec_test.go:108]: (Taking this PR fairly slowly because of the difficulty of the terrain and the number of times we've introduced bugs that were hard to sort out in specific situations.)

Comment (stasadev) [reply cmd/ddev/cmd/exec_test.go:108]: I added two test cases to see how it works in Bash:

```
bash -c "ddev exec 'true && pwd'"
bash -c "ddev exec true && pwd"
```

I don't check for file here, because it would be not reasonable to create a `/var/www/html/TestCmdExec-touch-separate-args.txt` file on the host.

Comment (rfay) [reply cmd/ddev/cmd/exec_test.go:108]: > because it would be not reasonable to create a /var/www/html/TestCmdExec-touch-separate-args.txt file on the host

And /var/www/html doesn't exist on the host in (most) cases and where it does, needs permissions of course.

**Comment by rfay** [comment]
Rebased just because. Hopefully I'll get to it before long.

**Comment by rfay** [comment]
Rebased yet again, looking yet again :)

**Review by rfay — APPROVED** [review]
This is amazing. Thank you!

File: pkg/ddevapp/task.go [hunk 5]
```diff
@@ -164,17 +164,7 @@ func NewTask(app *DdevApp, ytask YAMLTask) Task {
...
+		util.Warning("Invalid exec/exec_raw value, not executing it: %v", e)
```
[the remark this answers is not in the document]
Comment (stasadev) [reply pkg/ddevapp/task.go:167]: This `e` here is not an error, it's a value from YAML file, I'll rename it.

The `util.Warning` that I changed above are in different scope that should use `err`.

**Comment by rfay** [comment]
Pull when you're ready for it, thanks!
