### PR TITLE
fix: solve mutagen failure, restart should check for new version, check composer.json in container, fixes #5089

### LINKED ISSUE #5089: Possible mutagen failure to sync on snapshot restore or post-start composer install
There may be a situation reported by @mglaman in [Discord](https://discord.com/channels/664580571770388500/1125076127661166674/1126320464512421969) where `ddev snapshot restore` doesn't get mutagen properly synced. 

In his situation, he was using mutagen on linux in Github CI with post-start hooks that did a composer install.

They ran successfully on ddev start, but then failed on ddev snapshot restore.

```
hooks:
  post-start:
  - exec: chmod 775 web/sites/default
  - exec: composer install --prefer-dist --no-progress --no-interaction --apcu-autoloader
  - exec: composer dumpautoload -o
  - exec: vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer,vendor/slevomat/coding-standard,vendor/pheromone/phpcs-security-audit
  - exec: npm install
  - exec: npm install -g sass
  - exec: cd web/themes/custom/THEME && npm install
```

@hanoii reported a similar situation in private discord, apparently just on `ddev start` with a composer hook. But in this case it was fixed with `ddev restart`

```
Starting catalyze... 
mutagen sync catalyze exists but unable to get label:  
 Network ddev-catalyze_default  Created 
 Container ddev-catalyze-db  Created 
 Container ddev-catalyze-web  Created 
 Container ddev-catalyze-db  Started 
 Container ddev-catalyze-web  Started 
Starting mutagen sync process... This can take some time. 
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st catalyze -l' 
 Container ddev-router  Running 
Composer could not find a composer.json file in /var/www/html
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
Task failed: Composer command '[install]' in web container: composer command failed: exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
bash: /var/www/html/.ddev/platformsh-lite-addon-post-start.sh: No such file or directory
Task failed: Exec command 'bash /var/www/html/.ddev/platformsh-lite-addon-post-start.sh' in container/service 'web': exit status 127 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
bash: line 1: cd: web/themes/custom/catalyze_tw: No such file or directory
Task failed: Exec command 'cd web/themes/custom/catalyze_tw && yarn install && npx mix --production' in container/service 'web': exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
bash: /var/www/html/.ddev/platformsh-lite-addon-post-start.sh: No such file or directory
Task failed: Exec command 'bash /var/www/html/.ddev/platformsh-lite-addon-post-start.sh' in container/service 'web': exit status 127 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
```

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #5089 

## How This PR Solves The Issue

* Fix bug where if container was not yet healthy mutagen sync didn't happen.
* Add request to poweroff on `ddev restart`
* Check inside container to make sure mutagen flush is complete (look at /var/www/html/composer.json)

## Manual Testing Instructions

* `ddev restart` with version change
* `export DDEV_DEBUG=true && ddev mutagen reset && ddev start -y` on mutagen-enabled system. It should check composer.json (and succeed)..

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5106"></a>

### CODE REVIEW

File: pkg/ddevapp/mutagen.go [hunk 1]
```diff
@@ -433,12 +434,14 @@ func (app *DdevApp) GetMutagenSyncID() (id string, err error) {
 // MutagenSyncFlush performs a mutagen sync flush, waits for result, and checks for errors
 func (app *DdevApp) MutagenSyncFlush() error {
 	status, _ := app.SiteStatus()
-	if status == SiteRunning && app.IsMutagenEnabled() {
+	// TODO: Avoid this failure by looking at all statuses?
+	if (status == SiteRunning || status == SiteUnhealthy) && app.IsMutagenEnabled() {
```
Comment (rfay) [inline pkg/ddevapp/mutagen.go:438]: This was the fundamental change. In this context (`ddev mutagen reset && ddev start -y`) the web container is not yet healthy, because mutagen hasn't finished syncing. And sadly we then skipped out of here.

Discussion needed on how to make this more robust. I think probably we should just fail if site is not in expected situation. OTOH this condition was put here for a. reason I'm sure.

**Comment by rfay** [comment]
TODO:
- [ ] Solve test failures - TestDdevAllDatabases, TestTimezoneConfig. Both imply some bad path still remains
- [ ] Evaluate all paths for project states, not just running and unhealthy. Warn if we're skipping mutagen sync.
- [ ] Consider removing some debug statements

**Review by gilbertsoft — COMMENTED** [review]
Looks good from reading! Able to test tomorrow.
