### PR TITLE
fix: don't override `generic` type in `ddev config --update`, fixes #7035

### LINKED ISSUE #7035: Command `ddev config --update` changes project type from 'generic' to 'php'
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
======== Output file will be in /tmp/ddev-debug-test.txt ========


======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev
/bin/ddev

These config files were loaded for project diabetes-app: [/home/jasper/Projects/diabetes-app/.ddev/config.yaml]
name: diabetes-app
type: generic
php_version: 8.3
webserver_type: generic
webimage: ddev/ddev-webserver:v1.24.3
additional_hostnames: [diabetes]
additional_fqdns: []
database: {mariadb 10.11}
omit_containers: [db ddev-ssh-agent]
project_tld: swisdev.nl
use_dns_when_possible: true
timezone: Europe/Amsterdam
composer_version: 2
nodejs_version: 22
default_container_timeout: 120
web_extra_exposed_ports: [{nuxt 3000 80 443} {vite 24678 24677 24678}]
ddev_version_constraint: >=1.24.3


======== existing project customizations ========
.ddev/docker-compose.communicate.yaml


======== installed DDEV add-ons ========
No registered add-ons were found.


======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /home/jasper/Projects/diabetes-app
.ddev/mutagen/mutagen.yml not found


======== Creating dummy project named tryddevproject-29920 in ../tryddevproject-29920 ========
Creating a new DDEV project config in the current directory (/home/jasper/Projects/tryddevproject-29920)
Once completed, your configuration will be written to /home/jasper/Projects/tryddevproject-29920/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-29920' with docroot 'web' at '/home/jasper/Projects/tryddevproject-29920/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.


======== OS Information ========
Linux 45KS0F3 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


======== User information ========
uid=1000(jasper) gid=1000(jasper) groups=1000(jasper),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),116(netdev),1001(docker)


======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.24.3                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.24.3 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.24.3              
 docker           28.0.1                                   
 docker-api       1.48                                     
 docker-compose   v2.33.1                                  
 docker-platform  wsl2-docker-ce                           
 global-ddev-dir  /home/jasper/.ddev                       
 mutagen          0.18.1                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.24.3         
 web              ddev/ddev-webserver:v1.24.3              



======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 


======== DDEV global info ========
developer-mode=false
fail-on-hook-fail=false
instrumentation-opt-in=true
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.24.3
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/mnt/c/Users/jasper/AppData/Local/mkcert
no-bind-mounts=false
omit-containers=[ddev-ssh-agent]
performance-mode=none
project-tld=swisdev.nl
required-docker-compose-version=v2.33.1
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=


======== DOCKER provider info ========
docker client location: -rwxr-xr-x 1 root root 43049064 Feb 26 11:41 /usr/bin/docker

docker client alternate locations:
/usr/bin/docker
/bin/docker

Docker provider: wsl2-docker-ce
docker version: 
Client: Docker Engine - Community
 Version:           28.0.1
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        068a01e
 Built:             Wed Feb 26 10:41:08 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.1
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       bbd0a17
  Built:            Wed Feb 26 10:41:08 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker context: 
NAME        DESCRIPTION                               DOCKER ENDPOINT               ERROR
default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock   
Warning: DOCKER_HOST environment variable overrides the active context. To use a context, either set the global --context flag, or unset DOCKER_HOST environment variable.


DOCKER_DEFAULT_PLATFORM=notset
Docker platform: wsl2-docker-ce
Using Docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.33.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 28.0.1
Docker API version: 1.48
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:Filesystem                Size      Used Available Use% Mounted on
overlay                1006.9G    219.4G    736.2G  23% /


======== Existing docker containers ========
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


======== mkcert information ========
/usr/bin/mkcert
/bin/mkcert
CAROOT=/mnt/c/Users/jasper/AppData/Local/mkcert WSLENV=CAROOT/up: JAVA_HOME=
/mnt/c/Users/jasper/AppData/Local/mkcert
total 8
-r-xr-xr-x 1 jasper jasper 2484 Mar 30  2023 rootCA-key.pem
-rwxrwxrwx 1 jasper jasper 1740 Mar 30  2023 rootCA.pem


======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=2.65 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 2.648/2.648/2.648/0.000 ms


======== curl information ========
/usr/bin/curl
/bin/curl


======== ddev debug rebuild ========
Rebuilding project images...
Rebuilding project tryddevproject-29920 with `/home/jasper/.ddev/bin/docker-compose -f /home/jasper/Projects/tryddevproject-29920/.ddev/.ddev-docker-compose-full.yaml --progress plain build web --no-cache`
#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.54kB done
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/ddev/ddev-webserver:v1.24.3
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web  1/10] FROM docker.io/ddev/ddev-webserver:v1.24.3
#4 CACHED

#5 [web  2/10] RUN getent group tty || groupadd tty
#5 0.424 tty:x:5:
#5 DONE 0.4s

#6 [web  3/10] RUN (groupadd --gid 1000 "jasper" || groupadd "jasper" || true) && (useradd -G tty -l -m -s "/bin/bash" --gid "jasper" --comment '' --uid 1000 "jasper" || useradd -G tty -l -m -s "/bin/bash" --gid "jasper" --comment '' "jasper" || useradd  -G tty -l -m -s "/bin/bash" --gid "1000" --comment '' "jasper" || useradd -G tty -l -m -s "/bin/bash" --comment '' jasper )
#6 DONE 0.7s

#7 [web  4/10] RUN mkdir -p /home/jasper && chown jasper /home/jasper && chmod 600 /home/jasper/.pgpass
#7 DONE 0.5s

#8 [web  5/10] RUN START_SCRIPT_TIMEOUT=30 mariadb-client-install.sh || true
#8 0.602 This script is not intended to run with mariadb:10.11
#8 DONE 0.6s

#9 [web  6/10] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || log-stderr.sh composer self-update --2 || true
#9 0.900 Storing "stable" as default update channel for the next self-update run.
#9 1.115 You are already using the latest available Composer version 2.8.6 (stable channel).
#9 1.363 You are already using the latest available Composer version 2.8.6 (2.x channel).
#9 DONE 1.4s

#10 [web  7/10] RUN timeout 30 apt-get update || true
#10 0.742 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#10 0.784 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#10 0.808 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#10 0.849 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8792 kB]
#10 1.695 Get:5 http://nginx.org/packages/debian bookworm InRelease [2869 B]
#10 1.752 Get:6 http://nginx.org/packages/debian bookworm/nginx amd64 Packages [17.8 kB]
#10 1.774 Get:7 https://packages.sury.org/php bookworm InRelease [7551 B]
#10 1.781 Get:8 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.5 kB]
#10 1.787 Get:9 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [246 kB]
#10 1.831 Get:11 https://packages.sury.org/php bookworm/main amd64 Packages [255 kB]
#10 1.915 Get:12 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm InRelease [3675 B]
#10 2.047 Get:10 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease [4628 B]
#10 2.074 Get:13 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm InRelease [3681 B]
#10 2.213 Get:14 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [4422 B]
#10 2.298 Get:15 http://packages.blackfire.io/debian any InRelease [29.2 kB]
#10 2.335 Get:16 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm/main amd64 Packages [4504 B]
#10 2.356 Get:17 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [129 kB]
#10 2.467 Get:18 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm/main amd64 Packages [3347 B]
#10 2.563 Get:19 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main amd64 Packages [8556 B]
#10 2.754 Get:20 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main amd64 Packages [42.1 kB]
#10 2.802 Get:21 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 Packages [360 kB]
#10 3.141 Get:22 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main arm64 Packages [35.2 kB]
#10 3.460 Get:23 http://packages.blackfire.io/debian any/main amd64 Packages [31.8 kB]
#10 3.484 Fetched 10.3 MB in 3s (3528 kB/s)
#10 3.484 Reading package lists...
#10 DONE 4.0s

#11 [web  8/10] RUN curl -I https://www.google.com
#11 0.464   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#11 0.464                                  Dload  Upload   Total   Spent    Left  Speed
#11 0.464 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#11 0.547 HTTP/2 200 
#11 0.547 content-type: text/html; charset=ISO-8859-1
#11 0.547 content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-N5F4L1fZ4vZF8gzIO6N2CA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
#11 0.547 accept-ch: Sec-CH-Prefers-Color-Scheme
#11 0.547 p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
#11 0.547 date: Fri, 28 Feb 2025 13:09:04 GMT
#11 0.547 server: gws
#11 0.547 x-xss-protection: 0
#11 0.547 x-frame-options: SAMEORIGIN
#11 0.547 expires: Fri, 28 Feb 2025 13:09:04 GMT
#11 0.547 cache-control: private
#11 0.547 set-cookie: AEC=AVcja2f40oWmhkHrONspV76JqfS7bQsa2WPZ7QxfvJt9Q5NdxbzEj3BeTw; expires=Wed, 27-Aug-2025 13:09:04 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#11 0.547 set-cookie: __Secure-ENID=26.SE=hoezYkN8kzHO8h0q8wi9BJVoQHZ8ATBR6bVOhAiegipePnagLvLny0SRZjVry2nIWctFY5pLU7mC5AA1zO3TfQdAqu4KNFLhO9ZDfprTXFa7b7HWMiQF4-EFAvbzjwkY9uajdEDJF7Y6B2Vx2SYlTw0wIuIx9fdyXevy5kv4XwQc1H_ZxGBizMQ66c2Vp8fB3pOPNyvLz1X-rp-3PEWh1zmzDiWfCdKru8Y2px7acvBThLlm; expires=Tue, 31-Mar-2026 05:27:22 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#11 0.547 alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
#11 0.547 
#11 DONE 0.6s

#12 [web  9/10] RUN chmod 777 /run/php /var/log
#12 DONE 0.5s

#13 [web 10/10] RUN mkdir -p /tmp/xhprof && chmod -R ugo+w /etc/php /var/lib/php /tmp/xhprof
#13 DONE 1.6s

#14 [web] exporting to image
#14 exporting layers
#14 exporting layers 0.2s done
#14 writing image sha256:43fd5f737e8350c68da503dd7f0bb96a0ddc62e30c8e89f0f04fcf6e5f9dbea9 done
#14 naming to docker.io/ddev/ddev-webserver:v1.24.3-tryddevproject-29920-built done
#14 DONE 0.2s

#15 [web] resolving provenance for metadata file
#15 DONE 0.0s
 web  Built
Rebuilt Docker cache for project tryddevproject-29920 in 11s
Network ddev_default created
Using custom web-build configuration: [
	/home/jasper/Projects/tryddevproject-29920/.ddev/web-build/Dockerfile.test
]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
v1.24.3: Pulling from ddev/ddev-dbserver-mariadb-10.11
9cb31e2e37ea: Pulling fs layer
b5d0c07e1b39: Pulling fs layer
146766f55375: Pulling fs layer
7e9e7bda14da: Pulling fs layer
4e0d8410ccaa: Pulling fs layer
e54392e56360: Pulling fs layer
c1f62eab2318: Pulling fs layer
d645c8b36c27: Pulling fs layer
4f4fb700ef54: Pulling fs layer
0d0506066f94: Pulling fs layer
cabb0df5366e: Pulling fs layer
0de630bea834: Pulling fs layer
6983a363f308: Pulling fs layer
45703da1b505: Pulling fs layer
4e0d8410ccaa: Waiting
f135cc67e118: Pulling fs layer
35d41eaf9359: Pulling fs layer
e54392e56360: Waiting
c1f62eab2318: Waiting
67db047c3421: Pulling fs layer
d645c8b36c27: Waiting
0d0506066f94: Waiting
cabb0df5366e: Waiting
d94963e1d855: Pulling fs layer
449645ada642: Pulling fs layer
0de630bea834: Waiting
609e326bc20a: Pulling fs layer
c624665b4d51: Pulling fs layer
4f4fb700ef54: Waiting
6983a363f308: Waiting
a587269fc15e: Pulling fs layer
45703da1b505: Waiting
f135cc67e118: Waiting
8c3c7766f4c7: Pulling fs layer
35d41eaf9359: Waiting
e5303f7dcc49: Pulling fs layer
84fcff9187a6: Pulling fs layer
67db047c3421: Waiting
5986183768bb: Pulling fs layer
8b35c8cf300b: Pulling fs layer
449645ada642: Waiting
d94963e1d855: Waiting
a587269fc15e: Waiting
e5303f7dcc49: Waiting
8c3c7766f4c7: Waiting
84fcff9187a6: Waiting
5986183768bb: Waiting
c624665b4d51: Waiting
8b35c8cf300b: Waiting
7e9e7bda14da: Waiting
b5d0c07e1b39: Verifying Checksum
b5d0c07e1b39: Download complete
7e9e7bda14da: Verifying Checksum
7e9e7bda14da: Download complete
4e0d8410ccaa: Verifying Checksum
4e0d8410ccaa: Download complete
146766f55375: Verifying Checksum
146766f55375: Download complete
c1f62eab2318: Verifying Checksum
c1f62eab2318: Download complete
d645c8b36c27: Verifying Checksum
4f4fb700ef54: Download complete
9cb31e2e37ea: Download complete
0d0506066f94: Verifying Checksum
0d0506066f94: Download complete
cabb0df5366e: Verifying Checksum
cabb0df5366e: Download complete
9cb31e2e37ea: Pull complete
b5d0c07e1b39: Pull complete
6983a363f308: Verifying Checksum
6983a363f308: Download complete
146766f55375: Pull complete
7e9e7bda14da: Pull complete
4e0d8410ccaa: Pull complete
45703da1b505: Verifying Checksum
45703da1b505: Download complete
f135cc67e118: Verifying Checksum
f135cc67e118: Download complete
35d41eaf9359: Download complete
67db047c3421: Verifying Checksum
67db047c3421: Download complete
d94963e1d855: Download complete
0de630bea834: Verifying Checksum
0de630bea834: Download complete
609e326bc20a: Verifying Checksum
c624665b4d51: Verifying Checksum
c624665b4d51: Download complete
e54392e56360: Verifying Checksum
e54392e56360: Download complete
a587269fc15e: Download complete
8c3c7766f4c7: Verifying Checksum
8c3c7766f4c7: Download complete
e5303f7dcc49: Download complete
449645ada642: Verifying Checksum
449645ada642: Download complete
84fcff9187a6: Verifying Checksum
84fcff9187a6: Download complete
5986183768bb: Verifying Checksum
5986183768bb: Download complete
8b35c8cf300b: Verifying Checksum
8b35c8cf300b: Download complete
e54392e56360: Pull complete
c1f62eab2318: Pull complete
d645c8b36c27: Pull complete
4f4fb700ef54: Pull complete
0d0506066f94: Pull complete
cabb0df5366e: Pull complete
0de630bea834: Pull complete
6983a363f308: Pull complete
45703da1b505: Pull complete
f135cc67e118: Pull complete
35d41eaf9359: Pull complete
67db047c3421: Pull complete
d94963e1d855: Pull complete
449645ada642: Pull complete
609e326bc20a: Pull complete
c624665b4d51: Pull complete
a587269fc15e: Pull complete
8c3c7766f4c7: Pull complete
e5303f7dcc49: Pull complete
84fcff9187a6: Pull complete
5986183768bb: Pull complete
8b35c8cf300b: Pull complete
Digest: sha256:2b9911669de0f220fef105b426e3ffff418c8072fe7822fdd9ab2d33b703b168
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.11:v1.24.3
docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.24.3
Building project images.....
Project images built in 3s.
 Network ddev-tryddevproject-29920_default  Created
 Container ddev-tryddevproject-29920-web  Created
 Container ddev-tryddevproject-29920-db  Created
 Container ddev-tryddevproject-29920-db  Started
 Container ddev-tryddevproject-29920-web  Started
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started


======== Project startup ========
Starting tryddevproject-29920...
2025-02-28T14:10:50.974 GetAvailableRouterPort(): Router is healthy and running
2025-02-28T14:10:50.975 GetAvailableRouterPort(): proposedPort 80 already bound on ddev-router, accepting it
2025-02-28T14:10:50.977 GetAvailableRouterPort(): Router is healthy and running
2025-02-28T14:10:50.978 GetAvailableRouterPort(): proposedPort 443 already bound on ddev-router, accepting it
2025-02-28T14:10:50.979 GetAvailableRouterPort(): Router is healthy and running
2025-02-28T14:10:50.98 GetAvailableRouterPort(): proposedPort 8025 already bound on ddev-router, accepting it
2025-02-28T14:10:50.981 GetAvailableRouterPort(): Router is healthy and running
2025-02-28T14:10:50.982 GetAvailableRouterPort(): proposedPort 8026 already bound on ddev-router, accepting it
2025-02-28T14:10:51.007 Pulled image for ddev/ddev-webserver:v1.24.3
2025-02-28T14:10:51.008 Pulled image for busybox:stable
2025-02-28T14:10:51.009 Pulled image for ddev/ddev-utilities
2025-02-28T14:10:51.01 Pulled image for ddev/ddev-traefik-router:v1.24.3
2025-02-28T14:10:52.469 chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
2025-02-28T14:10:56.085 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
Using custom web-build configuration: [
	/home/jasper/Projects/tryddevproject-29920/.ddev/web-build/Dockerfile.test
]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
2025-02-28T14:10:56.1 host.docker.internal='192.168.224.1' because IsWSL2 and !IsDockerDesktop; received from ip -4 route show default
2025-02-28T14:10:56.115 Using automatically detected timezone: TZ=Europe/Amsterdam
2025-02-28T14:10:56.156 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.24.3
2025-02-28T14:10:56.157 Pulled image for ddev/ddev-webserver:v1.24.3
2025-02-28T14:10:56.158 Pulled image for ddev/ddev-traefik-router:v1.24.3
Building project images...
2025-02-28T14:10:56.177 Executing docker-compose -f /home/jasper/Projects/tryddevproject-29920/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.
Project images built in 2s.
2025-02-28T14:10:57.82 Removing dangling images for the project ddev-tryddevproject-29920
2025-02-28T14:10:57.826 Executing docker-compose -f /home/jasper/Projects/tryddevproject-29920/.ddev/.ddev-docker-compose-full.yaml up -d
 Container ddev-tryddevproject-29920-web  Recreate
 Container ddev-tryddevproject-29920-db  Recreate
 Container ddev-tryddevproject-29920-db  Recreated
 Container ddev-tryddevproject-29920-web  Recreated
 Container ddev-tryddevproject-29920-db  Started
 Container ddev-tryddevproject-29920-web  Started
2025-02-28T14:11:11.034 VIRTUAL_HOST=tryddevproject-29920.swisdev.nl for web
2025-02-28T14:11:11.034 HTTP_EXPOSE=80:80,8025:8025 for web
2025-02-28T14:11:11.034 HTTPS_EXPOSE=443:80,8026:8025 for web
2025-02-28T14:11:11.461 Copied /home/jasper/Projects/tryddevproject-29920/.ddev/traefik:CopyIntoVolume_qmpouayirxrp into /mnt/v/traefik in 41.677128ms
2025-02-28T14:11:11.498 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-02-28T14:11:11.889 Copied Traefik certs in /home/jasper/Projects/tryddevproject-29920/.ddev/traefik/certs to ddev-global-cache/traefik
2025-02-28T14:11:11.889 Running /start.sh in ddev-webserver
Waiting for containers to become ready: [web db]
2025-02-28T14:11:18.808 Copied /home/jasper/.ddev/commands:CopyIntoVolume_lhicxgzrojst into /mnt/v/global-commands in 44.115324ms
2025-02-28T14:11:18.845 Exec chown -R 1000 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2025-02-28T14:11:19.31 Testing to see if /mnt/ddev_config is properly mounted
2025-02-28T14:11:19.408 Getting stderr output from 'log-stderr.sh --show'
Starting ddev-router if necessary...
2025-02-28T14:11:19.969 Copied /home/jasper/.ddev/traefik:CopyIntoVolume_rqzjpinnrayv into /mnt/v/traefik in 41.311323ms
2025-02-28T14:11:20.006 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-02-28T14:11:20.449 Copied global Traefik config in /home/jasper/.ddev/traefik/certs to ddev-global-cache/traefik
 Container ddev-router  Running
2025-02-28T14:11:20.49 Waiting for ddev-router to become ready, timeout=60
2025-02-28T14:11:20.997 ddev-router is ready
Successfully started tryddevproject-29920
Your project can be reached at https://tryddevproject-29920.swisdev.nl
See 'ddev describe' for alternate URLs.


======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 28 Feb 2025 13:11:23 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://127.0.0.1:32806 (web container http docker bind port) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 28 Feb 2025 13:11:23 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://tryddevproject-29920.swisdev.nl (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Fri, 28 Feb 2025 13:11:24 GMT
Server: nginx
Vary: Accept-Encoding



======== Full curl of http://tryddevproject-29920.swisdev.nl (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   198    0   198    0     0   2032      0 --:--:-- --:--:-- --:--:--  2041
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Full curl of https://tryddevproject-29920.swisdev.nl (router https URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   198    0   198    0     0   1565      0 --:--:-- --:--:-- --:--:--  1571
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Curl google.com to check internet access and VPN ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-r7JmmUEALkzoCscGdBCtWA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Fri, 28 Feb 2025 13:11:25 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Fri, 28 Feb 2025 13:11:25 GMT
cache-control: private
set-cookie: AEC=AVcja2evSpwBx3sS-AwFE72cz18zNxTX0yLE_fojAYQfBQ6WVfVZt4FKcQ; expires=Wed, 27-Aug-2025 13:11:25 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: __Secure-ENID=26.SE=cVY7bhDHuQpQwaZu6SXsSLkFd9l8pTLyDYipcSJpz_iPqj07_Ldnv3907cNW_qecx1JDnh8oNSdFx92rEAFkRxBGyoz92nnF6_mCqCs3O2nsM23Oszlq76nFc4VGh1HU9O-uAHML43YAd01rQeZMZzi_7D-9IDDlHsspZdc-TX2K2ON8Px1UIOAXhGtT7QY2ctO0hNkyNL5O5otWuBxzUyjAaYB1CeAR63l6ELs3Z9D4D5rkGQ; expires=Tue, 31-Mar-2026 05:29:43 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000



======== host.docker.internal status ========
PING host.docker.internal (192.168.224.1) 56(84) bytes of data.

--- host.docker.internal ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

exit status 1
Failed to execute command `ping -c 1 host.docker.internal`: exit status 1


======== Project ownership on host ========
drwxr-xr-x 4 jasper jasper 4096 Feb 28 14:08 ../tryddevproject-29920


======== Project ownership in container ========
drwxr-xr-x 4 jasper jasper 4096 Feb 28 14:08 //var/www/html


======== In-container filesystem ========
Filesystem     Type  1K-blocks      Used Available Use% Mounted on
/dev/sdc       ext4 1055762868 230775584 771283812  24% /var/www/html


======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting for ddev launch to complete before deleting project


Cleanup: deleting test project tryddevproject-29920
 Container ddev-tryddevproject-29920-db  Stopped
 Container ddev-tryddevproject-29920-web  Stopped
 Container ddev-tryddevproject-29920-db  Stopped
 Container ddev-tryddevproject-29920-web  Stopped
 Container ddev-tryddevproject-29920-db  Removed
 Container ddev-tryddevproject-29920-web  Removed
 Network ddev-tryddevproject-29920_default  Removed
Volume tryddevproject-29920-mariadb for project tryddevproject-29920 was deleted
Volume tryddevproject-29920-postgres for project tryddevproject-29920 was deleted
Volume tryddevproject-29920_project_mutagen for project tryddevproject-29920 was deleted
Project tryddevproject-29920 was deleted. Your code and configuration are unchanged.

Please remove the files from this test with 'rm -r ../tryddevproject-29920'
```
</details>

### Expected Behavior

When I run `ddev config --update` I don't expect the project type to change.

### Actual Behavior

The command changes the project type from 'generic' to 'php'.

### Steps To Reproduce

1. Follow a [Node.js quickstart](https://ddev.readthedocs.io/en/stable/users/quickstart/#nodejs)
2. Run `ddev config --update`
3. See the project type changes to 'php'

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #7035

## How This PR Solves The Issue

Ignores the app type detection for the `generic` type.

## Manual Testing Instructions

Follow any quickstart https://ddev.readthedocs.io/en/stable/users/quickstart/ and run:

```
ddev config --project-type=generic

# update should not change the project type
ddev config --update
```

### CODE REVIEW

File: pkg/ddevapp/apptypes.go [hunk 1]
```diff
@@ -397,6 +397,10 @@ func (app *DdevApp) SetApptypeSettingsPaths() {
 // DetectAppType calls each apptype's detector until it finds a match,
 // or returns 'php' as a last resort.
 func (app *DdevApp) DetectAppType() string {
+	// `generic` type should not be overridden
+	if app.Type == nodeps.AppTypeGeneric {
+		return app.Type
```
Comment (rfay) [inline pkg/ddevapp/apptypes.go:402]: Seems perfect to me.

**Review by rfay — APPROVED** [review]
Thanks!
