### PR TITLE
fix: Install matching postgresql client versions in ddev-webserver, fixes #6139

### LINKED ISSUE #6139: Version mismatch with Postgres 16 & pg_dump
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```


======== Output file will be in /var/folders/v4/f7f7b5cn2lb7nbpvkw_wxd7m0000gn/T/ddev-debug-test.txt ========


======== Existing project config ========
ddev installation alternate locations:
/opt/homebrew/bin/ddev
/usr/local/bin/ddev

These config files were loaded for project craft-4-project: [/Users/timkelty/Dev/craft-4-project/.ddev/config.yaml /Users/timkelty/Dev/craft-4-project/.ddev/config.local.yaml]
name: craft-4-project
type: craftcms
docroot: web
php_version: 8.2
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.23.0-1
xdebug_enabled: true
additional_hostnames: [www.craft-4-project.ddev.site]
database: {postgres 16}
host_db_port: 32785
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 20
default_container_timeout: 120


======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /Users/timkelty/Dev/craft-4-project
.ddev/mutagen/mutagen.yml not found


======== Creating dummy project named tryddevproject-30149 in ../tryddevproject-30149 ========
Creating a new DDEV project config in the current directory (/Users/timkelty/Dev/tryddevproject-30149)
Once completed, your configuration will be written to /Users/timkelty/Dev/tryddevproject-30149/.ddev/config.yaml

Configuring a 'php' project with docroot 'web' at /Users/timkelty/Dev/tryddevproject-30149/web
Configuration complete. You may now run 'ddev start'.


======== OS Information ========
Darwin tasha-mbp.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64
ProductName:		macOS
ProductVersion:		14.4.1
BuildVersion:		23E224


======== User information ========
uid=501(timkelty) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),333(piavpn),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)


======== ddev version ========
 ITEM             VALUE                                    
 DDEV version     v1.23.0                                  
 architecture     arm64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.0 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.0              
 docker           25.0.5                                   
 docker-api       1.44                                     
 docker-compose   v2.26.1                                  
 docker-platform  orbstack                                 
 mutagen          0.17.2                                   
 os               darwin                                   
 router           ddev/ddev-traefik-router:v1.23.0         
 web              ddev/ddev-webserver:v1.23.0-1            



======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 


======== DDEV global info ========
developer-mode=false
disable-http2=false
fail-on-hook-fail=false
instrumentation-opt-in=true
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.23.0
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/Users/timkelty/Library/Application Support/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=none
project-tld=ddev.site
required-docker-compose-version=v2.26.1
router=traefik
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=


======== DOCKER provider info ========
docker client location: /usr/local/bin/docker

docker client alternate locations:
/usr/local/bin/docker
/Users/timkelty/bin/docker
/Users/timkelty/.orbstack/bin/docker

Docker provider: orbstack
docker version: 
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:32:30 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.5
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       e63daec
  Built:            Tue Mar 19 15:05:27 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.13
  GitCommit:        7c3aca7a610df76212171d200ca3811ff6096eb8
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

DOCKER_DEFAULT_PLATFORM=notset
Version: 1.5.1 (1050100)
Commit: 4cfac15e1080617c70eb163966e1cb2009dac1c2 (v1.5.1)
Docker platform: orbstack
Using Docker context: default (unix:///Users/timkelty/.orbstack/run/docker.sock)
docker-compose: v2.26.1
Using DOCKER_HOST=unix:///Users/timkelty/.orbstack/run/docker.sock
Docker version: 25.0.5
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:Filesystem                Size      Used Available Use% Mounted on
overlay                 208.8G    116.5G     92.3G  56% /


======== Existing docker containers ========
CONTAINER ID   IMAGE                               COMMAND                  CREATED        STATUS                      PORTS                                       NAMES
e6956b642930   f52301ea79d8                        "/bref-entrypoint.sh"    25 hours ago   Exited (1) 25 hours ago                                                 great_driscoll
c17faf9d7748   phpstorm_helpers:PS-241.14494.237   "/bin/sh"                3 weeks ago    Created                                                                 phpstorm_helpers_PS-241.14494.237
6c493ba966db   europa-museum-web                   "/usr/bin/supervisor…"   4 weeks ago    Exited (0) 4 weeks ago                                                  europa-museum-web-1
50060041a31f   postgres:13-alpine                  "docker-entrypoint.s…"   4 weeks ago    Exited (0) 4 weeks ago                                                  europa-museum-postgres-1
a450b90f5055   phpstorm_helpers:PS-233.15026.12    "/bin/sh"                5 weeks ago    Created                                                                 phpstorm_helpers_PS-233.15026.12
a67e1faf5195   phpstorm_helpers:PS-233.14808.18    "/bin/sh"                6 weeks ago    Created                                                                 phpstorm_helpers_PS-233.14808.18
6b9fc09a1a58   phpstorm_helpers:PS-233.14475.35    "/bin/sh"                2 months ago   Created                                                                 phpstorm_helpers_PS-233.14475.35
6fb38a2e6174   phpstorm_helpers:PS-233.14015.96    "/bin/sh"                3 months ago   Created                                                                 phpstorm_helpers_PS-233.14015.96
3cebe3ab86fe   registry.dagger.io/engine:v0.8.7    "dagger-entrypoint.s…"   3 months ago   Exited (0) 3 weeks ago                                                  dagger-engine-be7d2e4256ad2b56
d535c7ddffc0   0c46d48f665d                        "/bref-entrypoint.sh…"   3 months ago   Exited (130) 3 months ago                                               quizzical_spence
924b3f75246f   0c46d48f665d                        "/bref-entrypoint.sh…"   3 months ago   Exited (0) 3 months ago                                                 wizardly_swirles
96592961cb01   0c46d48f665d                        "/bref-entrypoint.sh…"   3 months ago   Exited (0) 3 months ago                                                 confident_sanderson
4d994d9d5563   0c46d48f665d                        "/bref-entrypoint.sh"    3 months ago   Exited (1) 3 months ago                                                 heuristic_matsumoto
fab8535d67fd   c0690e9cc64c                        "/bin/sh"                4 months ago   Created                                                                 phpstorm_helpers_PS-233.13135.108
9871349a56e5   6fc530a6b828                        "/bin/sh"                4 months ago   Created                                                                 phpstorm_helpers_PS-233.11799.297
c22b75f614c9   e2ca35984434                        "/bin/sh"                4 months ago   Created                                                                 phpstorm_helpers_PS-233.11799.232
b95459ecf873   95cc97f035f3                        "/bref-entrypoint.sh"    4 months ago   Exited (137) 3 weeks ago                                                craftcom-bref-1
085b6d5afc52   fce266b6ff7e                        "/bin/sh -c ' mc con…"   5 months ago   Exited (0) 4 months ago                                                 craftcom-minio-mc-1
ac24ca16a7bb   2727917de685                        "/usr/bin/docker-ent…"   5 months ago   Exited (0) 4 months ago                                                 craftcom-minio-1
039db9f1e2cd   e6f5d0b64daf                        "docker-entrypoint.s…"   5 months ago   Exited (0) 4 months ago                                                 craftcom-redis-1
6a958e3fa769   c4c56fac2628                        "docker-entrypoint.s…"   5 months ago   Exited (0) 4 months ago                                                 craftcom-postgres-1
5b2f7d97db17   6a0560a40914                        "docker-entrypoint.s…"   5 months ago   Exited (0) 4 months ago                                                 craftcom-mysql-1
39b518e5f3a9   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (0) 5 months ago                                                 trusting_sanderson
be8eb603a193   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (0) 5 months ago                                                 xenodochial_cohen
5f60de3353a2   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (0) 5 months ago                                                 lucid_chebyshev
1a54d4e13271   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (2) 5 months ago                                                 reverent_davinci
0c5c8a260e0a   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (0) 5 months ago                                                 clever_banzai
17f72a9b6005   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (0) 5 months ago                                                 modest_bhaskara
6575193f409d   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (2) 5 months ago                                                 happy_wiles
ec32a8939c98   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (1) 5 months ago                                                 optimistic_mcnulty
efaa90037577   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (0) 5 months ago                                                 sharp_volhard
28139364cfa1   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (0) 5 months ago                                                 infallible_panini
b1d5a19237a7   ae27b63999c7                        "/docker-entrypoint.…"   5 months ago   Exited (0) 5 months ago                                                 boring_galileo
133fc1b74cef   9151ec042e4c                        "/bin/sh"                5 months ago   Created                                                                 phpstorm_helpers_PS-232.10227.13
2818395006f6   6a0560a40914                        "docker-entrypoint.s…"   5 months ago   Exited (130) 5 months ago                                               distracted_jackson
f123bf4d9bae   6a0560a40914                        "docker-entrypoint.s…"   5 months ago   Exited (130) 5 months ago                                               gallant_jennings
be263d535e26   6a0560a40914                        "/bin/sh -c \"ls\""      5 months ago   Created                     3306/tcp, 33060/tcp                         jovial_carver
a18354499729   6a0560a40914                        "docker-entrypoint.s…"   5 months ago   Exited (130) 5 months ago                                               jovial_tharp
7c04a9026efc   6a0560a40914                        "sh -c \"ls\""           5 months ago   Created                     3306/tcp, 33060/tcp                         heuristic_booth
de3e3a69f21a   6a0560a40914                        "sh"                     5 months ago   Exited (0) 5 months ago                                                 great_leavitt
7d6f992356fb   6a0560a40914                        "sh -c \"ls\""           6 months ago   Created                     3306/tcp, 33060/tcp                         vigorous_germain
9253da730c7f   6a0560a40914                        "sh -c ls"               6 months ago   Created                     3306/tcp, 33060/tcp                         strange_bose
7b1e3cc0dde3   6a0560a40914                        "sh"                     6 months ago   Exited (130) 6 months ago                                               fervent_almeida
89ca44fd8ab0   6a0560a40914                        "docker-entrypoint.s…"   6 months ago   Exited (130) 6 months ago                                               great_bartik
0cdbb8a082d5   6a0560a40914                        "docker-entrypoint.s…"   6 months ago   Exited (130) 6 months ago                                               clever_fermi
b094a06b1d7c   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 happy_fermi
c6859fbf2e68   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 great_shirley
41a9689e2493   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (1) 6 months ago                                                 quizzical_bhaskara
296dd54f2789   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 vigilant_booth
68729778918a   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 zen_curie
66a72c643aeb   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 practical_margulis
ca2a8b721557   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 nostalgic_borg
66cbd056aee5   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 elated_elion
946b9fc591dc   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 happy_yonath
e83b47fbfc50   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 mystifying_wilbur
a42e1e2af71e   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 unruffled_hamilton
e100bd0be648   db41f805a188                        "php craft cloud/ass…"   6 months ago   Exited (0) 6 months ago                                                 vibrant_mcnulty
86be6202287c   db41f805a188                        "/lambda-entrypoint.…"   6 months ago   Exited (142) 6 months ago                                               inspiring_mcnulty
b6ca7c8f806b   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 recursing_mclean
5446b450b13a   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 stoic_satoshi
5984d044a1b2   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 eager_fermat
50b715bf76ab   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 festive_tesla
68653f8df21b   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (1) 6 months ago                                                 hopeful_shannon
85b8055299ee   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 elastic_shamir
2d0694383272   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 stoic_wu
b4fc13cbd03a   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 pensive_panini
2f7e94e1033c   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 focused_goodall
ca1d89f3c23b   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 elegant_napier
8d268fe64b19   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 naughty_goldwasser
e1ec89a73b20   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 sleepy_noyce
75dc456f4eca   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 intelligent_napier
987e6fd00d2d   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 dreamy_leavitt
debc5ccc6285   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 magical_lewin
56dd42b78409   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 epic_hermann
588f26c7385c   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 compassionate_blackwell
98499f321568   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 compassionate_boyd
5dbfb6a67fb5   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 happy_carver
afe231a2b7d2   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 zealous_euler
11894085265d   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 ecstatic_diffie
d772ff91c937   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (1) 6 months ago                                                 relaxed_ganguly
c68af9daf875   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 determined_kowalevski
8ed33a9e4654   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 modest_taussig
dd90347835bb   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 youthful_vaughan
c6f10aafb934   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 blissful_euler
98f2943dc819   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (1) 6 months ago                                                 tender_margulis
25f921fa3726   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (1) 6 months ago                                                 strange_turing
a7f2b46163f7   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (1) 6 months ago                                                 jovial_villani
a4a2cb610dd1   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 wizardly_blackwell
5b80d7f02899   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 flamboyant_bell
e222624d84aa   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 amazing_gates
085874d35449   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 vibrant_chaplygin
3333b60bc072   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (1) 6 months ago                                                 exciting_brown
f106b725c5a2   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (1) 6 months ago                                                 clever_meninsky
9a8d4f658c85   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 inspiring_hermann
098674c68cbf   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 affectionate_kepler
f2b80b4c05c0   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 cool_joliot
e065e1d5a452   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (1) 6 months ago                                                 reverent_tharp
d90b301eb14d   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 reverent_chatterjee
a7931a25d2b0   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 laughing_buck
f4d91d7eb216   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 wonderful_jang
0615be521f59   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 compassionate_goldstine
5ad792085b94   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 vigilant_nightingale
8c4606cb3637   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 strange_roentgen
f64d57d44fbf   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 distracted_feistel
8754a1a9be51   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 cpresources-test
a4d2e4b9f4f6   bc7b2e73d12a                        "docker-php-entrypoi…"   6 months ago   Exited (0) 6 months ago                                                 funny_mestorf
c6fc48147e1c   a1dd35550311                        "docker-php-entrypoi…"   6 months ago   Exited (255) 6 months ago   9000/tcp                                    craftquest-test-queue-1
b43f053cbf00   4fb456e76ee5                        "docker-php-entrypoi…"   6 months ago   Exited (255) 6 months ago   9000/tcp                                    craftquest-test-php_xdebug-1
32500adbad2f   5f5e601702c2                        "docker-php-entrypoi…"   6 months ago   Exited (255) 6 months ago   9000/tcp                                    craftquest-test-php-1
2d689d3f3b6b   711e22a438a7                        "docker-entrypoint.s…"   6 months ago   Exited (0) 6 months ago                                                 craftquest-test-vite-1
b4a2b1d7be52   aa5e68171130                        "docker-entrypoint.s…"   6 months ago   Exited (255) 6 months ago   0.0.0.0:3336->3306/tcp, :::3336->3306/tcp   craftquest-test-mariadb-1
bfbdd79acbbe   cb2d4e9e4ba2                        "/docker-entrypoint.…"   6 months ago   Exited (255) 6 months ago   0.0.0.0:8888->80/tcp, :::8888->80/tcp       craftquest-test-nginx-1
3b3fa06f456c   67301f368169                        "docker-entrypoint.s…"   6 months ago   Exited (255) 6 months ago   6379/tcp                                    craftquest-test-redis-1
5631412f79ae   ae27b63999c7                        "/docker-entrypoint.…"   7 months ago   Created                                                                 wonderful_cartwright
d48e165c8183   1809475dc712                        "docker-entrypoint.s…"   7 months ago   Created                                                                 romantic_cray
bf42de82f32b   1809475dc712                        "docker-entrypoint.s…"   7 months ago   Created                                                                 elastic_pare


======== mkcert information ========
/opt/homebrew/bin/mkcert
/Users/timkelty/Library/Application Support/mkcert
total 16
-r--------  1 timkelty  staff  2484 May 24  2022 rootCA-key.pem
-rw-r--r--  1 timkelty  staff  1769 May 24  2022 rootCA.pem


======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.049 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.049/0.049/0.049/0.000 ms


======== Project startup ========
Network ddev_default created
Starting tryddevproject-30149...
2024-04-30T11:27:24.873 Pulled image for ddev/ddev-webserver:v1.23.0-1
2024-04-30T11:27:24.874 Pulled image for busybox:stable
2024-04-30T11:27:24.875 Pulled image for ddev/ddev-ssh-agent:v1.23.0
2024-04-30T11:27:24.875 Pulled image for ddev/ddev-traefik-router:v1.23.0
2024-04-30T11:27:25.179 chowning /mnt/ddev-global-cache and /var/lib/mysql to 501
2024-04-30T11:27:25.877 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 501
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
2024-04-30T11:27:27.778 host.docker.internal='' because no other case was discovered
v1.23.0: Pulling from ddev/ddev-dbserver-mariadb-10.11
f4bb4e8dca02: Pulling fs layer
a936dfd11bce: Pulling fs layer
58b160c94476: Pulling fs layer
2852b259badd: Pulling fs layer
58b6ddbb08c3: Pulling fs layer
0f02d97f2d89: Pulling fs layer
994fef625868: Pulling fs layer
fce07317f70b: Pulling fs layer
4f4fb700ef54: Pulling fs layer
f1a25e0cc1fd: Pulling fs layer
a9ee1b871472: Pulling fs layer
aa928ad5fde3: Pulling fs layer
da5eaca6943e: Pulling fs layer
0a97e5ce4743: Pulling fs layer
57d973e78a73: Pulling fs layer
d51c1e042342: Pulling fs layer
a7de64eac3ab: Pulling fs layer
2c3cedab13cc: Pulling fs layer
d39e383eb71b: Pulling fs layer
6682c689d7c1: Pulling fs layer
cf64f04657c5: Pulling fs layer
6a3e4c757251: Pulling fs layer
0599ccc09145: Pulling fs layer
caefbeac4cf6: Pulling fs layer
da5eaca6943e: Waiting
0a97e5ce4743: Waiting
57d973e78a73: Waiting
d51c1e042342: Waiting
a7de64eac3ab: Waiting
2c3cedab13cc: Waiting
2852b259badd: Waiting
58b6ddbb08c3: Waiting
0f02d97f2d89: Waiting
994fef625868: Waiting
fce07317f70b: Waiting
4f4fb700ef54: Waiting
f1a25e0cc1fd: Waiting
a9ee1b871472: Waiting
aa928ad5fde3: Waiting
6682c689d7c1: Waiting
cf64f04657c5: Waiting
6a3e4c757251: Waiting
0599ccc09145: Waiting
caefbeac4cf6: Waiting
d39e383eb71b: Waiting
a936dfd11bce: Verifying Checksum
a936dfd11bce: Download complete
2852b259badd: Verifying Checksum
2852b259badd: Download complete
58b160c94476: Download complete
58b6ddbb08c3: Verifying Checksum
58b6ddbb08c3: Download complete
f4bb4e8dca02: Download complete
994fef625868: Verifying Checksum
994fef625868: Download complete
fce07317f70b: Verifying Checksum
fce07317f70b: Download complete
4f4fb700ef54: Download complete
f4bb4e8dca02: Pull complete
a936dfd11bce: Pull complete
f1a25e0cc1fd: Verifying Checksum
f1a25e0cc1fd: Download complete
58b160c94476: Pull complete
2852b259badd: Pull complete
58b6ddbb08c3: Pull complete
aa928ad5fde3: Verifying Checksum
aa928ad5fde3: Download complete
da5eaca6943e: Download complete
0a97e5ce4743: Verifying Checksum
0a97e5ce4743: Download complete
57d973e78a73: Verifying Checksum
57d973e78a73: Download complete
0f02d97f2d89: Verifying Checksum
0f02d97f2d89: Download complete
d51c1e042342: Download complete
a7de64eac3ab: Verifying Checksum
a7de64eac3ab: Download complete
0f02d97f2d89: Pull complete
994fef625868: Pull complete
fce07317f70b: Pull complete
4f4fb700ef54: Pull complete
d39e383eb71b: Verifying Checksum
d39e383eb71b: Download complete
2c3cedab13cc: Verifying Checksum
2c3cedab13cc: Download complete
6682c689d7c1: Verifying Checksum
6682c689d7c1: Download complete
6a3e4c757251: Verifying Checksum
6a3e4c757251: Download complete
cf64f04657c5: Download complete
0599ccc09145: Verifying Checksum
0599ccc09145: Download complete
f1a25e0cc1fd: Pull complete
caefbeac4cf6: Verifying Checksum
caefbeac4cf6: Download complete
a9ee1b871472: Verifying Checksum
a9ee1b871472: Download complete
a9ee1b871472: Pull complete
aa928ad5fde3: Pull complete
da5eaca6943e: Pull complete
0a97e5ce4743: Pull complete
57d973e78a73: Pull complete
d51c1e042342: Pull complete
a7de64eac3ab: Pull complete
2c3cedab13cc: Pull complete
d39e383eb71b: Pull complete
6682c689d7c1: Pull complete
cf64f04657c5: Pull complete
6a3e4c757251: Pull complete
0599ccc09145: Pull complete
caefbeac4cf6: Pull complete
Digest: sha256:8616a3e0ad0554aa26c838819a8cf3e72ae600071c2e9e76e0fd6e32a8c97627
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.11:v1.23.0
docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.0
2024-04-30T11:27:43.902 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.23.0
2024-04-30T11:27:43.903 Pulled image for ddev/ddev-webserver:v1.23.0-1
2024-04-30T11:27:43.904 Pulled image for ddev/ddev-ssh-agent:v1.23.0
2024-04-30T11:27:43.904 Pulled image for ddev/ddev-traefik-router:v1.23.0
Building project images...
2024-04-30T11:27:43.979 Executing docker-compose -f /Users/timkelty/Dev/tryddevproject-30149/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.Project images built in 1s.
2024-04-30T11:27:44.984 Executing docker-compose -f /Users/timkelty/Dev/tryddevproject-30149/.ddev/.ddev-docker-compose-full.yaml up -d
 Network ddev-tryddevproject-30149_default  Created
 Container ddev-tryddevproject-30149-db  Created
 Container ddev-tryddevproject-30149-web  Created
 Container ddev-tryddevproject-30149-db  Started
 Container ddev-tryddevproject-30149-web  Started
2024-04-30T11:27:45.508 Copied /Users/timkelty/Library/Application Support/mkcert:CopyIntoVolume_xgcqlrxrqdns into /mnt/v/mkcert in 39.481667ms
2024-04-30T11:27:45.532 Exec chown -R 501 /mnt/v/mkcert stdout=, stderr=, err=<nil>
2024-04-30T11:27:45.608 Pushed mkcert rootca certs to ddev-global-cache/mkcert
2024-04-30T11:27:45.608 VIRTUAL_HOST=tryddevproject-30149.ddev.site for web
2024-04-30T11:27:45.608 HTTP_EXPOSE=80:80,8025:8025 for web
2024-04-30T11:27:45.608 HTTPS_EXPOSE=443:80,8026:8025 for web
2024-04-30T11:27:45.997 Copied /Users/timkelty/Dev/tryddevproject-30149/.ddev/traefik:CopyIntoVolume_jpktrkxvjqoy into /mnt/v/traefik in 27.406834ms
2024-04-30T11:27:46.015 Exec chown -R 501 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-04-30T11:27:46.071 Copied Traefik certs in /Users/timkelty/Dev/tryddevproject-30149/.ddev/traefik/certs to ddev-global-cache/traefik
2024-04-30T11:27:46.071 Running /start.sh in ddev-webserver
Waiting for web/db containers to become ready: [web db]
2024-04-30T11:27:54.441 Copied /Users/timkelty/.ddev/commands:CopyIntoVolume_bhwcxyxvnnbt into /mnt/v/global-commands in 35.244709ms
2024-04-30T11:27:54.461 Exec chown -R 501 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2024-04-30T11:27:54.576 Testing to see if /mnt/ddev_config is properly mounted
Starting ddev-router if necessary...
2024-04-30T11:27:55.051 Copied /Users/timkelty/.ddev/traefik:CopyIntoVolume_ncpdlyugtngh into /mnt/v/traefik in 41.901417ms
2024-04-30T11:27:55.067 Exec chown -R 501 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-04-30T11:27:55.117 Copied global Traefik config in /Users/timkelty/.ddev/traefik/certs to ddev-global-cache/traefik
 Container ddev-router  Created
 Container ddev-router  Started
2024-04-30T11:27:55.288 Waiting for ddev-router to become ready. docker inspect --format "{{json .State.Health }}" ddev-router
2024-04-30T11:27:56.808 ddev-router is ready
Waiting for additional project containers to become ready...
All project containers are now ready.
Successfully started tryddevproject-30149
Project can be reached at https://tryddevproject-30149.ddev.site https://127.0.0.1:60002


======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 30 Apr 2024 15:27:58 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://tryddevproject-30149.ddev.site from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Tue, 30 Apr 2024 15:27:58 GMT
Server: nginx
Vary: Accept-Encoding



======== Full curl of http://tryddevproject-30149.ddev.site from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   286    0   286    0     0  60967      0 --:--:-- --:--:-- --:--:-- 71500
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/var/folders/v4/f7f7b5cn2lb7nbpvkw_wxd7m0000gn/T/ddev-debug-test.txt</b><br />
file:///var/folders/v4/f7f7b5cn2lb7nbpvkw_wxd7m0000gn/T/ddev-debug-test.txt<br />


======== Full curl of https://tryddevproject-30149.ddev.site from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   286    0   286    0     0   8310      0 --:--:-- --:--:-- --:--:--  8411
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/var/folders/v4/f7f7b5cn2lb7nbpvkw_wxd7m0000gn/T/ddev-debug-test.txt</b><br />
file:///var/folders/v4/f7f7b5cn2lb7nbpvkw_wxd7m0000gn/T/ddev-debug-test.txt<br />


======== Project ownership on host ========
drwxr-xr-x  4 timkelty  staff  128 Apr 30 11:27 ../tryddevproject-30149


======== Project ownership in container ========
drwxr-xr-x 4 timkelty dialout 128 Apr 30 15:27 //var/www/html


======== In-container filesystem ========
Filesystem     Type     1K-blocks      Used Available Use% Mounted on
mac            virtiofs 971350180 863373240 107976940  89% /var/www/html


======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting 10 seconds to run ddev stop --unlist
running ddev stop --unlist
 Container ddev-tryddevproject-30149-db  Stopped
 Container ddev-tryddevproject-30149-web  Stopped
 Container ddev-tryddevproject-30149-db  Stopped
 Container ddev-tryddevproject-30149-web  Stopped
 Container ddev-tryddevproject-30149-db  Removed
 Container ddev-tryddevproject-30149-web  Removed
 Network ddev-tryddevproject-30149_default  Removed
Project tryddevproject-30149 has been stopped.

```
</details>

### Expected Behavior

`pg_dump` should work via `ddev exec pg_dump`

### Actual Behavior

```
❯ ddev exec pg_dump
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.2 (Debian 16.2-1.pgdg120+2); pg_dump version: 15.6 (Debian 15.6-0+deb12u1)
Failed to execute command pg_dump: exit status 1
```

### Steps To Reproduce

- configure project with:

```
database:
  type: postgres
  version: "16"
```
- run `ddev exec pg_restore`

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

* #6139 

## How This PR Solves The Issue

This is the (hopefully) last of a series of PRs that attempts to put the matching version of database client in the running web container as well as the db container. 

This one is about PostgreSQL, the clients `psql`, `pg_dump`, and `pg_restore`

This works for postgres 10+. For Postgres 9, it's not in the provided repository, so we use the default postgres clients

Note that this changes the *default* psql in the web container from 15 to 16. However, that shouldn't matter, because if someone is using Postgres, the version will match (unless postgres:9)

## Manual Testing Instructions

Start a project with a database of type postgres. `ddev psql --version` should show that version.

## Automated Testing Overview

Added TestWebserverPostgresDBClient

### CODE REVIEW

File: pkg/ddevapp/config.go [hunk 1]
```diff
@@ -1194,6 +1194,20 @@ RUN (apt-get -qq update || true) && DEBIAN_FRONTEND=noninteractive apt-get -qq i
 ### DDEV-injected composer update
 RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update %s || composer self-update %s || true
 `, composerSelfUpdateArg, composerSelfUpdateArg)
+
+		// For Postgres, install the relevant PostgreSQL clients
+		// PostgreSQL 9 is not supported by this approach, so skip it, and
+		// it will just get the default psql version.
+		if app.Database.Type == nodeps.Postgres && app.Database.Version != nodeps.Postgres9 {
```
Comment (stasadev) [inline pkg/ddevapp/config.go:1201]:
```suggestion
		// For Postgres, install the relevant PostgreSQL clients
		if app.Database.Type == nodeps.Postgres {
			psqlVersion := app.Database.Version
			if psqlVersion == nodeps.Postgres9 {
				psqlVersion = "9.6"
			}
```

File: pkg/ddevapp/config.go [hunk 2]
```diff
@@ -1194,6 +1194,20 @@ RUN (apt-get -qq update || true) && DEBIAN_FRONTEND=noninteractive apt-get -qq i
...
+			contents = contents + fmt.Sprintf(`
+RUN EXISTING_PSQL_VERSION=$(psql --version | awk -F '[\. ]*' '{ print $3 }'); \
+if [ "${EXISTING_PSQL_VERSION}" != "%s" ]; then \
+  apt-get remove -y postgresql-client-${EXISTING_PSQL_VERSION} && \
+  apt-get update >/dev/null && \
+  apt-get install -y postgresql-client-%s || true; \
+fi`, app.Database.Version, app.Database.Version) + "\n\n"
```
Comment (stasadev) [inline pkg/ddevapp/config.go:1208]:
```suggestion
fi`, app.Database.Version, psqlVersion) + "\n\n"
```

**Review by stasadev — CHANGES_REQUESTED** [review]
It works great!

As for PostgreSQL 9: we can support it's client with my suggestion.

**Review by stasadev — APPROVED** [review]
