### PR TITLE
fix: add Docker filter by label without value, fixes #6088

### LINKED ISSUE #6088: `ddev poweroff` should delete all containers (running or not) with the label `com.ddev.site-name`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

`ddev poweroff` should destroy all ddev-created containers (detected by label `com.ddev.site-name`)

### Actual Behavior

It doesn't destroy them

### Steps To Reproduce

`docker run -it -l com.ddev.site-name=d10 ddev/ddev-webserver:v1.23.0 bash`

then `ddev poweroff`

`docker ps -a` will still show it existing.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #6088

## How This PR Solves The Issue

The Docker filter used the old syntax from `fsouza/go-dockerclient`, and as a result, it was looking for `label=label=com.ddev.site-name` instead of `label=com.ddev.site-name`.

I also finally figured out the syntax for filtering by label only.

## Manual Testing Instructions

See #6088.

## Related Issue Link(s)

- #5787

### CODE REVIEW

File: pkg/ddevapp/poweroff.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ func PowerOff() {
 	}
 
 	// Any straggling containers that have label "com.ddev.site-name" should be removed.
-	containers, err := dockerutil.FindContainersByLabels(map[string]string{"label": "com.ddev.site-name"})
+	containers, err := dockerutil.FindContainersByLabels(map[string]string{"com.ddev.site-name": ""})
```
Comment (rfay) [inline pkg/ddevapp/poweroff.go:31]: Ah, so we *did* have this in the poweroff, it just got malformed somehow. Thanks for sorting!

**Review by rfay — COMMENTED** [review]
This is looking great. I haven't manually tested yet.

**Comment by rfay** [comment]
Testing with:
* `docker run --name=emptylabel -l com.ddev.site-name=""  ddev/ddev-webserver:v1.23.0 ls`
* ` docker run --name=withlabel -l com.ddev.site-name="withlabel"  ddev/ddev-webserve
r:v1.23.0 ls`
* ` docker run -it --name=withlabel-running -l com.ddev.site-name="withlabel-running"  ddev/ddev-webserver:v1.23.0 bash`

👍 All of these got stopped on `ddev poweroff`
