### PR TITLE
fix: detect Craft CMS version and warn user on type mismatch and introduce new env vars, fixes #4650

### LINKED ISSUE #4650: Don't manage Craft 3 .env, Fix `*_SITE_URL`
The recently added settings management for Craft projects broke my ddev / **Craft 4** project - when I came back to it after some time away - and in a way I couldn't immediately understand from this error:

```
Failed to start craft-dev: template: templateStringToFile:/home/jeremy/ddev-projects/c4-dev/.env:7: function "siteUrl" not defined
```

Prior to this the project was working fine for a few months, it was only on coming back to it that the new settings management kicked in, with a ddev upgrade.  

Thus, I think `disable_settings_management ` should definitely default to `false` for _existing_ projects. 

As per the other issue discussion, I think `PRIMARY_SITE_URL` should be added only if the existing & typical `CRAFT_SITE_URL` is not already present - otherwise it's just doubling up right?

The config setting is the default way to define this in Craft:
https://craftcms.com/knowledge-base/how-craft-determines-the-site-url
https://craftcms.com/docs/2.x/config-settings.html#siteurl

And thus, with Craft 4's new approach to .env variables, `CRAFT_SITE_URL` is the de facto default way of actually implementing this.

Personally I am not super fussed about Mailhog, other than to note that Craft has a config setting for a similar thing already:
https://docs.craftcms.com/v3/config/config-settings.html#testtoemailaddress

```
        'testToEmailAddress' => (\craft\helpers\App::env('SEND_ALL_EMAILS_TO')) ?? null,
```

So in Craft's case, Mailhog is likely to be irrelevant to most and I would expect that to be set as a matter of course in `.env` files for dev environments.

_Originally posted by @bossanova808 in https://github.com/drud/ddev/issues/4552#issuecomment-1429132626_
            
(Adding as a new issue per request)

### PR DESCRIPTION
**Pull request by gilbertsoft**
## The Issue

- #4650

## How This PR Solves The Issue

`CRAFT_WEB_URL` and `CRAFT_WEB_ROOT` are added to the `.env` file. `PRIMARY_SITE_URL` is still left untouched to not break existing installations at the moment. Additionally a version check is implemented and warns the user if using project type `craftcms` for version before 4.

## Manual Testing Instructions

Follow the quick start to setup a new Craft CMS site which should not work out-of-the-box without any additional configuration.

Setup a Craft CMS v3 or earlier with project type `craftcms` and check if a warning is properly shown.

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5108"></a>

### CODE REVIEW

File: pkg/ddevapp/ddevapp.go [hunk 1]
```diff
@@ -389,22 +389,28 @@ func (app DdevApp) GetDocroot() string {
...
+}
+
+// GetComposerRoot will determine the absolute composer root directory where
+// all Composer related commands will be executed.
+// If inContainer set to true, the absolute path in the container will be
+// returned, else the absolute path on the host.
+// If showWarning set to true, a warning containing the composer root will be
+// shown to the user to avoid confusion.
+func (app *DdevApp) GetComposerRoot(inContainer, showWarning bool) string {
+	absComposerRoot := path.Join(app.GetAbsDocroot(inContainer), app.ComposerRoot)
```
Comment (rfay) [inline pkg/ddevapp/ddevapp.go:413]: This logic isn't correct; The composer_root is not relative to the docroot. So this ends up with the wrong things in a basic craft3 download, where the composer.json is in the project root (where it should be)

**Review by rfay — CHANGES_REQUESTED** [review]
This doesn't work yet; the logic for composer root isn't correct; You can test by downloading a Craft 3 tarball (vendor and composer.json in root, docroot in web) from https://craftcms.com/docs/3.x/installation.html#downloading-an-archive-file-manually

File: pkg/ddevapp/ddevapp.go (hunk 1 above)
Comment (gilbertsoft) [reply pkg/ddevapp/ddevapp.go:413]: Oh it is correct, it has nothing changed here, but the name of the new function is wrong, should be the absolute project root instead.

Comment (gilbertsoft) [reply pkg/ddevapp/ddevapp.go:413]: True, messed up sth with the refactoring.

File: pkg/ddevapp/ddevapp.go [hunk 2]
```diff
@@ -389,22 +389,28 @@ func (app DdevApp) GetDocroot() string {
...
+	var basePath string
 
 	if inContainer {
 		basePath = "/var/www/html"
 	} else {
 		basePath = app.AppRoot
 	}
 
-	absComposerRoot := path.Join(basePath, app.ComposerRoot)
+	return path.Join(basePath, app.GetDocroot())
```
[the remark this answers is not in the document]
Comment (gilbertsoft) [reply pkg/ddevapp/ddevapp.go:403]: Yes, would be probably better. But so far it seems to work also with path on host. Will change...

**Review by rfay — CHANGES_REQUESTED** [review]
This can't work until 

* https://github.com/ddev/ddev/pull/5128

```
$ ddev start
You seem to have a new DDEV version.
During an upgrade it's important to `ddev poweroff`.
May I do `ddev poweroff` before continuing?
This does no harm and loses no data. [Y/n] (yes):
panic: interface conversion: interface {} is bool, not ddevapp.UploadDirs

goroutine 1 [running]:
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).validateUploadDirs(0xc000177500)
        /home/rfay/workspace/ddev/pkg/ddevapp/upload_dirs.go:230 +0x485
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).LoadConfigYamlFile(0xc000177500, {0xc00002a840?, 0xc00056ef70?})
        /home/rfay/workspace/ddev/pkg/ddevapp/config.go:356 +0x1b2
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).ReadConfig(0xc000177500, 0x1)
        /home/rfay/workspace/ddev/pkg/ddevapp/config.go:310 +0x4b
github.com/ddev/ddev/pkg/ddevapp.NewApp({0xc0000292f0, 0x18}, 0x97?)
        /home/rfay/workspace/ddev/pkg/ddevapp/config.go:112 +0x7fc
github.com/ddev/ddev/pkg/ddevapp.GetProjects(0x1)
        /home/rfay/workspace/ddev/pkg/ddevapp/utils.go:343 +0x1e7
github.com/ddev/ddev/pkg/ddevapp.PowerOff()
        /home/rfay/workspace/ddev/pkg/ddevapp/poweroff.go:11 +0x33
github.com/ddev/ddev/cmd/ddev/cmd.checkDdevVersionAndOptInInstrumentation(0x0)
        /home/rfay/workspace/ddev/cmd/ddev/cmd/root.go:225 +0x2ce
github.com/ddev/ddev/cmd/ddev/cmd.glob..func57(0x10efb20?, {0x1130d80, 0x0, 0x0})
        /home/rfay/workspace/ddev/cmd/ddev/cmd/start.go:73 +0x335
github.com/spf13/cobra.(*Command).execute(0x10efb20, {0x1130d80, 0x0, 0x0})
        /home/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x10ee4a0)
        /home/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:902
github.com/ddev/ddev/cmd/ddev/cmd.Execute()
        /home/rfay/workspace/ddev/cmd/ddev/cmd/root.go:155 +0x25
main.main()
        /home/rfay/workspace/ddev/cmd/ddev/main.go:28 +0xc5
```

File: pkg/ddevapp/craftcms.go [hunk 3]
```diff
@@ -68,6 +69,14 @@ func craftCmsPostStartAction(app *DdevApp) error {
 		return nil
 	}
 
+	// Check version is v4 or higher or warn user about app type mismatch.
+	if !isCraftCms4orHigher(app) {
+		util.Warning("It looks like the installed Craft CMS is lower than version 4 where it's recommended to use project type `php` or disable settings management with `ddev config --disable-settings-management`")
+		if !util.Confirm("Would you like to continue anyway with the automatic configuration?") {
```
Comment (rfay) [inline pkg/ddevapp/craftcms.go:75]: I sure wish we had an option to offer "no" as the default. Should we do that?

**Review by rfay — COMMENTED** [review]
I did experiment with squashing #5128 onto this and it seemed to do what we want with Craft 3.

File: pkg/ddevapp/craftcms.go [hunk 4]
```diff
@@ -124,9 +134,11 @@ func craftCmsPostStartAction(app *DdevApp) error {
 			"CRAFT_DB_DATABASE":     "db",
 			"CRAFT_DB_USER":         "db",
 			"CRAFT_DB_PASSWORD":     "db",
+			"CRAFT_WEB_URL":         app.GetPrimaryURL(),
+			"CRAFT_WEB_ROOT":        app.GetAbsDocroot(true),
 			"MAILHOG_SMTP_HOSTNAME": "127.0.0.1",
 			"MAILHOG_SMTP_PORT":     "1025",
-			"PRIMARY_SITE_URL":      app.GetPrimaryURL(),
+			"PRIMARY_SITE_URL":      app.GetPrimaryURL(), // for backward compatibility only
```
Comment (rfay) [inline pkg/ddevapp/craftcms.go:141]: I thought the decision in https://github.com/ddev/ddev/issues/4650 was not to include this.

File: pkg/ddevapp/craftcms.go (hunk 3 above)
Comment (gilbertsoft) [reply pkg/ddevapp/craftcms.go:75]: Or rephrase the question to invert it.

File: pkg/ddevapp/craftcms.go (hunk 4 above)
Comment (gilbertsoft) [reply pkg/ddevapp/craftcms.go:141]: Removal is breaking and imho we should give the users some time to use the new config.

Comment (rfay) [reply pkg/ddevapp/craftcms.go:141]: I think this would only affect new projects.

File: pkg/ddevapp/craftcms.go (hunk 3 above)
Comment (rfay) [reply pkg/ddevapp/craftcms.go:75]: That's not a bad idea.

File: pkg/ddevapp/ddevapp.go [hunk 5]
```diff
@@ -389,23 +389,41 @@ func (app DdevApp) GetDocroot() string {
...
+	if inContainer {
+		return path.Join(app.GetAbsAppRoot(true), app.GetDocroot())
+	}
+
+	return filepath.Join(app.GetAbsAppRoot(false), app.GetDocroot())
+}
+
+// GetAbsAppRoot returns the absolute path to the project root on the host or if
+// inContainer is set to true in the container.
+func (app DdevApp) GetAbsAppRoot(inContainer bool) string {
```
Comment (rfay) [inline pkg/ddevapp/ddevapp.go:404]: I am very happy to have this in there :)

**Review by rfay — APPROVED** [review]
Let's do it!
